// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: bom/v1/bom.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BomService_UploadBOM_FullMethodName             = "/api.bom.v1.BomService/UploadBOM"
	BomService_SearchQuotes_FullMethodName          = "/api.bom.v1.BomService/SearchQuotes"
	BomService_AutoMatch_FullMethodName             = "/api.bom.v1.BomService/AutoMatch"
	BomService_DownloadTemplate_FullMethodName      = "/api.bom.v1.BomService/DownloadTemplate"
	BomService_GetBOM_FullMethodName                = "/api.bom.v1.BomService/GetBOM"
	BomService_GetMatchResult_FullMethodName        = "/api.bom.v1.BomService/GetMatchResult"
	BomService_CreateSession_FullMethodName         = "/api.bom.v1.BomService/CreateSession"
	BomService_GetSession_FullMethodName            = "/api.bom.v1.BomService/GetSession"
	BomService_PutPlatforms_FullMethodName          = "/api.bom.v1.BomService/PutPlatforms"
	BomService_GetReadiness_FullMethodName          = "/api.bom.v1.BomService/GetReadiness"
	BomService_GetBOMLines_FullMethodName           = "/api.bom.v1.BomService/GetBOMLines"
	BomService_RetrySearchTasks_FullMethodName      = "/api.bom.v1.BomService/RetrySearchTasks"
	BomService_SubmitBomSearchResult_FullMethodName = "/api.bom.v1.BomService/SubmitBomSearchResult"
	BomService_ExportSession_FullMethodName         = "/api.bom.v1.BomService/ExportSession"
	BomService_ListMatchHistory_FullMethodName      = "/api.bom.v1.BomService/ListMatchHistory"
	BomService_GetMatchHistory_FullMethodName       = "/api.bom.v1.BomService/GetMatchHistory"
)

// BomServiceClient is the client API for BomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BOM 配单服务
type BomServiceClient interface {
	// 上传并解析 BOM
	UploadBOM(ctx context.Context, in *UploadBOMRequest, opts ...grpc.CallOption) (*UploadBOMReply, error)
	// 多平台搜索报价
	SearchQuotes(ctx context.Context, in *SearchQuotesRequest, opts ...grpc.CallOption) (*SearchQuotesReply, error)
	// 自动配单
	AutoMatch(ctx context.Context, in *AutoMatchRequest, opts ...grpc.CallOption) (*AutoMatchReply, error)
	// 下载 BOM 模板
	DownloadTemplate(ctx context.Context, in *DownloadTemplateRequest, opts ...grpc.CallOption) (*DownloadTemplateReply, error)
	// 获取 BOM 详情（含解析结果）
	GetBOM(ctx context.Context, in *GetBOMRequest, opts ...grpc.CallOption) (*GetBOMReply, error)
	// 获取配单结果
	GetMatchResult(ctx context.Context, in *GetMatchResultRequest, opts ...grpc.CallOption) (*GetMatchResultReply, error)
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionReply, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionReply, error)
	PutPlatforms(ctx context.Context, in *PutPlatformsRequest, opts ...grpc.CallOption) (*PutPlatformsReply, error)
	GetReadiness(ctx context.Context, in *GetReadinessRequest, opts ...grpc.CallOption) (*GetReadinessReply, error)
	GetBOMLines(ctx context.Context, in *GetBOMLinesRequest, opts ...grpc.CallOption) (*GetBOMLinesReply, error)
	RetrySearchTasks(ctx context.Context, in *RetrySearchTasksRequest, opts ...grpc.CallOption) (*RetrySearchTasksReply, error)
	// Agent 回写单行搜索任务结果（写 bom_search_task + bom_quote_cache）
	SubmitBomSearchResult(ctx context.Context, in *SubmitBomSearchResultRequest, opts ...grpc.CallOption) (*SubmitBomSearchResultReply, error)
	// 导出会话 BOM 行（Excel/CSV），见 docs/BOM货源搜索-接口清单.md §7
	ExportSession(ctx context.Context, in *ExportSessionRequest, opts ...grpc.CallOption) (*ExportSessionReply, error)
	// 配单历史列表
	ListMatchHistory(ctx context.Context, in *ListMatchHistoryRequest, opts ...grpc.CallOption) (*ListMatchHistoryReply, error)
	// 配单历史详情（快照）
	GetMatchHistory(ctx context.Context, in *GetMatchHistoryRequest, opts ...grpc.CallOption) (*GetMatchHistoryReply, error)
}

type bomServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBomServiceClient(cc grpc.ClientConnInterface) BomServiceClient {
	return &bomServiceClient{cc}
}

func (c *bomServiceClient) UploadBOM(ctx context.Context, in *UploadBOMRequest, opts ...grpc.CallOption) (*UploadBOMReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadBOMReply)
	err := c.cc.Invoke(ctx, BomService_UploadBOM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) SearchQuotes(ctx context.Context, in *SearchQuotesRequest, opts ...grpc.CallOption) (*SearchQuotesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchQuotesReply)
	err := c.cc.Invoke(ctx, BomService_SearchQuotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) AutoMatch(ctx context.Context, in *AutoMatchRequest, opts ...grpc.CallOption) (*AutoMatchReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AutoMatchReply)
	err := c.cc.Invoke(ctx, BomService_AutoMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) DownloadTemplate(ctx context.Context, in *DownloadTemplateRequest, opts ...grpc.CallOption) (*DownloadTemplateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadTemplateReply)
	err := c.cc.Invoke(ctx, BomService_DownloadTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) GetBOM(ctx context.Context, in *GetBOMRequest, opts ...grpc.CallOption) (*GetBOMReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBOMReply)
	err := c.cc.Invoke(ctx, BomService_GetBOM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) GetMatchResult(ctx context.Context, in *GetMatchResultRequest, opts ...grpc.CallOption) (*GetMatchResultReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMatchResultReply)
	err := c.cc.Invoke(ctx, BomService_GetMatchResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionReply)
	err := c.cc.Invoke(ctx, BomService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionReply)
	err := c.cc.Invoke(ctx, BomService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) PutPlatforms(ctx context.Context, in *PutPlatformsRequest, opts ...grpc.CallOption) (*PutPlatformsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutPlatformsReply)
	err := c.cc.Invoke(ctx, BomService_PutPlatforms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) GetReadiness(ctx context.Context, in *GetReadinessRequest, opts ...grpc.CallOption) (*GetReadinessReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReadinessReply)
	err := c.cc.Invoke(ctx, BomService_GetReadiness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) GetBOMLines(ctx context.Context, in *GetBOMLinesRequest, opts ...grpc.CallOption) (*GetBOMLinesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBOMLinesReply)
	err := c.cc.Invoke(ctx, BomService_GetBOMLines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) RetrySearchTasks(ctx context.Context, in *RetrySearchTasksRequest, opts ...grpc.CallOption) (*RetrySearchTasksReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrySearchTasksReply)
	err := c.cc.Invoke(ctx, BomService_RetrySearchTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) SubmitBomSearchResult(ctx context.Context, in *SubmitBomSearchResultRequest, opts ...grpc.CallOption) (*SubmitBomSearchResultReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitBomSearchResultReply)
	err := c.cc.Invoke(ctx, BomService_SubmitBomSearchResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) ExportSession(ctx context.Context, in *ExportSessionRequest, opts ...grpc.CallOption) (*ExportSessionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportSessionReply)
	err := c.cc.Invoke(ctx, BomService_ExportSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) ListMatchHistory(ctx context.Context, in *ListMatchHistoryRequest, opts ...grpc.CallOption) (*ListMatchHistoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMatchHistoryReply)
	err := c.cc.Invoke(ctx, BomService_ListMatchHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) GetMatchHistory(ctx context.Context, in *GetMatchHistoryRequest, opts ...grpc.CallOption) (*GetMatchHistoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMatchHistoryReply)
	err := c.cc.Invoke(ctx, BomService_GetMatchHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BomServiceServer is the server API for BomService service.
// All implementations must embed UnimplementedBomServiceServer
// for forward compatibility.
//
// BOM 配单服务
type BomServiceServer interface {
	// 上传并解析 BOM
	UploadBOM(context.Context, *UploadBOMRequest) (*UploadBOMReply, error)
	// 多平台搜索报价
	SearchQuotes(context.Context, *SearchQuotesRequest) (*SearchQuotesReply, error)
	// 自动配单
	AutoMatch(context.Context, *AutoMatchRequest) (*AutoMatchReply, error)
	// 下载 BOM 模板
	DownloadTemplate(context.Context, *DownloadTemplateRequest) (*DownloadTemplateReply, error)
	// 获取 BOM 详情（含解析结果）
	GetBOM(context.Context, *GetBOMRequest) (*GetBOMReply, error)
	// 获取配单结果
	GetMatchResult(context.Context, *GetMatchResultRequest) (*GetMatchResultReply, error)
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionReply, error)
	GetSession(context.Context, *GetSessionRequest) (*GetSessionReply, error)
	PutPlatforms(context.Context, *PutPlatformsRequest) (*PutPlatformsReply, error)
	GetReadiness(context.Context, *GetReadinessRequest) (*GetReadinessReply, error)
	GetBOMLines(context.Context, *GetBOMLinesRequest) (*GetBOMLinesReply, error)
	RetrySearchTasks(context.Context, *RetrySearchTasksRequest) (*RetrySearchTasksReply, error)
	// Agent 回写单行搜索任务结果（写 bom_search_task + bom_quote_cache）
	SubmitBomSearchResult(context.Context, *SubmitBomSearchResultRequest) (*SubmitBomSearchResultReply, error)
	// 导出会话 BOM 行（Excel/CSV），见 docs/BOM货源搜索-接口清单.md §7
	ExportSession(context.Context, *ExportSessionRequest) (*ExportSessionReply, error)
	// 配单历史列表
	ListMatchHistory(context.Context, *ListMatchHistoryRequest) (*ListMatchHistoryReply, error)
	// 配单历史详情（快照）
	GetMatchHistory(context.Context, *GetMatchHistoryRequest) (*GetMatchHistoryReply, error)
	mustEmbedUnimplementedBomServiceServer()
}

// UnimplementedBomServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBomServiceServer struct{}

func (UnimplementedBomServiceServer) UploadBOM(context.Context, *UploadBOMRequest) (*UploadBOMReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadBOM not implemented")
}
func (UnimplementedBomServiceServer) SearchQuotes(context.Context, *SearchQuotesRequest) (*SearchQuotesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchQuotes not implemented")
}
func (UnimplementedBomServiceServer) AutoMatch(context.Context, *AutoMatchRequest) (*AutoMatchReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AutoMatch not implemented")
}
func (UnimplementedBomServiceServer) DownloadTemplate(context.Context, *DownloadTemplateRequest) (*DownloadTemplateReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadTemplate not implemented")
}
func (UnimplementedBomServiceServer) GetBOM(context.Context, *GetBOMRequest) (*GetBOMReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBOM not implemented")
}
func (UnimplementedBomServiceServer) GetMatchResult(context.Context, *GetMatchResultRequest) (*GetMatchResultReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMatchResult not implemented")
}
func (UnimplementedBomServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedBomServiceServer) GetSession(context.Context, *GetSessionRequest) (*GetSessionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedBomServiceServer) PutPlatforms(context.Context, *PutPlatformsRequest) (*PutPlatformsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PutPlatforms not implemented")
}
func (UnimplementedBomServiceServer) GetReadiness(context.Context, *GetReadinessRequest) (*GetReadinessReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReadiness not implemented")
}
func (UnimplementedBomServiceServer) GetBOMLines(context.Context, *GetBOMLinesRequest) (*GetBOMLinesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBOMLines not implemented")
}
func (UnimplementedBomServiceServer) RetrySearchTasks(context.Context, *RetrySearchTasksRequest) (*RetrySearchTasksReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrySearchTasks not implemented")
}
func (UnimplementedBomServiceServer) SubmitBomSearchResult(context.Context, *SubmitBomSearchResultRequest) (*SubmitBomSearchResultReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitBomSearchResult not implemented")
}
func (UnimplementedBomServiceServer) ExportSession(context.Context, *ExportSessionRequest) (*ExportSessionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportSession not implemented")
}
func (UnimplementedBomServiceServer) ListMatchHistory(context.Context, *ListMatchHistoryRequest) (*ListMatchHistoryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMatchHistory not implemented")
}
func (UnimplementedBomServiceServer) GetMatchHistory(context.Context, *GetMatchHistoryRequest) (*GetMatchHistoryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMatchHistory not implemented")
}
func (UnimplementedBomServiceServer) mustEmbedUnimplementedBomServiceServer() {}
func (UnimplementedBomServiceServer) testEmbeddedByValue()                    {}

// UnsafeBomServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BomServiceServer will
// result in compilation errors.
type UnsafeBomServiceServer interface {
	mustEmbedUnimplementedBomServiceServer()
}

func RegisterBomServiceServer(s grpc.ServiceRegistrar, srv BomServiceServer) {
	// If the following call panics, it indicates UnimplementedBomServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BomService_ServiceDesc, srv)
}

func _BomService_UploadBOM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadBOMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).UploadBOM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_UploadBOM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).UploadBOM(ctx, req.(*UploadBOMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_SearchQuotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchQuotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).SearchQuotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_SearchQuotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).SearchQuotes(ctx, req.(*SearchQuotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_AutoMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutoMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).AutoMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_AutoMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).AutoMatch(ctx, req.(*AutoMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_DownloadTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).DownloadTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_DownloadTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).DownloadTemplate(ctx, req.(*DownloadTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_GetBOM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBOMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).GetBOM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_GetBOM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).GetBOM(ctx, req.(*GetBOMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_GetMatchResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).GetMatchResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_GetMatchResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).GetMatchResult(ctx, req.(*GetMatchResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_PutPlatforms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutPlatformsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).PutPlatforms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_PutPlatforms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).PutPlatforms(ctx, req.(*PutPlatformsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_GetReadiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReadinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).GetReadiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_GetReadiness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).GetReadiness(ctx, req.(*GetReadinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_GetBOMLines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBOMLinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).GetBOMLines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_GetBOMLines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).GetBOMLines(ctx, req.(*GetBOMLinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_RetrySearchTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrySearchTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).RetrySearchTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_RetrySearchTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).RetrySearchTasks(ctx, req.(*RetrySearchTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_SubmitBomSearchResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitBomSearchResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).SubmitBomSearchResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_SubmitBomSearchResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).SubmitBomSearchResult(ctx, req.(*SubmitBomSearchResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_ExportSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).ExportSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_ExportSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).ExportSession(ctx, req.(*ExportSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_ListMatchHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMatchHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).ListMatchHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_ListMatchHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).ListMatchHistory(ctx, req.(*ListMatchHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_GetMatchHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).GetMatchHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_GetMatchHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).GetMatchHistory(ctx, req.(*GetMatchHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BomService_ServiceDesc is the grpc.ServiceDesc for BomService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BomService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.bom.v1.BomService",
	HandlerType: (*BomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadBOM",
			Handler:    _BomService_UploadBOM_Handler,
		},
		{
			MethodName: "SearchQuotes",
			Handler:    _BomService_SearchQuotes_Handler,
		},
		{
			MethodName: "AutoMatch",
			Handler:    _BomService_AutoMatch_Handler,
		},
		{
			MethodName: "DownloadTemplate",
			Handler:    _BomService_DownloadTemplate_Handler,
		},
		{
			MethodName: "GetBOM",
			Handler:    _BomService_GetBOM_Handler,
		},
		{
			MethodName: "GetMatchResult",
			Handler:    _BomService_GetMatchResult_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _BomService_CreateSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _BomService_GetSession_Handler,
		},
		{
			MethodName: "PutPlatforms",
			Handler:    _BomService_PutPlatforms_Handler,
		},
		{
			MethodName: "GetReadiness",
			Handler:    _BomService_GetReadiness_Handler,
		},
		{
			MethodName: "GetBOMLines",
			Handler:    _BomService_GetBOMLines_Handler,
		},
		{
			MethodName: "RetrySearchTasks",
			Handler:    _BomService_RetrySearchTasks_Handler,
		},
		{
			MethodName: "SubmitBomSearchResult",
			Handler:    _BomService_SubmitBomSearchResult_Handler,
		},
		{
			MethodName: "ExportSession",
			Handler:    _BomService_ExportSession_Handler,
		},
		{
			MethodName: "ListMatchHistory",
			Handler:    _BomService_ListMatchHistory_Handler,
		},
		{
			MethodName: "GetMatchHistory",
			Handler:    _BomService_GetMatchHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bom/v1/bom.proto",
}
