// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: bom/v1/bom.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BomService_UploadBOM_FullMethodName                              = "/api.bom.v1.BomService/UploadBOM"
	BomService_SearchQuotes_FullMethodName                           = "/api.bom.v1.BomService/SearchQuotes"
	BomService_AutoMatch_FullMethodName                              = "/api.bom.v1.BomService/AutoMatch"
	BomService_DownloadTemplate_FullMethodName                       = "/api.bom.v1.BomService/DownloadTemplate"
	BomService_ListManufacturerCanonicals_FullMethodName             = "/api.bom.v1.BomService/ListManufacturerCanonicals"
	BomService_CreateManufacturerAlias_FullMethodName                = "/api.bom.v1.BomService/CreateManufacturerAlias"
	BomService_ListSessionLineMfrCandidates_FullMethodName           = "/api.bom.v1.BomService/ListSessionLineMfrCandidates"
	BomService_ApproveSessionLineMfrCleaning_FullMethodName          = "/api.bom.v1.BomService/ApproveSessionLineMfrCleaning"
	BomService_ListQuoteItemMfrReviews_FullMethodName                = "/api.bom.v1.BomService/ListQuoteItemMfrReviews"
	BomService_SubmitQuoteItemMfrReview_FullMethodName               = "/api.bom.v1.BomService/SubmitQuoteItemMfrReview"
	BomService_ApplyKnownManufacturerAliasesToSession_FullMethodName = "/api.bom.v1.BomService/ApplyKnownManufacturerAliasesToSession"
	BomService_GetBOM_FullMethodName                                 = "/api.bom.v1.BomService/GetBOM"
	BomService_GetMatchResult_FullMethodName                         = "/api.bom.v1.BomService/GetMatchResult"
	BomService_ListMatchSources_FullMethodName                       = "/api.bom.v1.BomService/ListMatchSources"
	BomService_GetMatchSourceDetail_FullMethodName                   = "/api.bom.v1.BomService/GetMatchSourceDetail"
	BomService_GetBomLineQuoteItems_FullMethodName                   = "/api.bom.v1.BomService/GetBomLineQuoteItems"
	BomService_CreateSession_FullMethodName                          = "/api.bom.v1.BomService/CreateSession"
	BomService_GetSession_FullMethodName                             = "/api.bom.v1.BomService/GetSession"
	BomService_ListSessions_FullMethodName                           = "/api.bom.v1.BomService/ListSessions"
	BomService_PatchSession_FullMethodName                           = "/api.bom.v1.BomService/PatchSession"
	BomService_PutPlatforms_FullMethodName                           = "/api.bom.v1.BomService/PutPlatforms"
	BomService_GetReadiness_FullMethodName                           = "/api.bom.v1.BomService/GetReadiness"
	BomService_GetBOMLines_FullMethodName                            = "/api.bom.v1.BomService/GetBOMLines"
	BomService_GetSessionSearchTaskCoverage_FullMethodName           = "/api.bom.v1.BomService/GetSessionSearchTaskCoverage"
	BomService_ListSessionSearchTasks_FullMethodName                 = "/api.bom.v1.BomService/ListSessionSearchTasks"
	BomService_CreateSessionLine_FullMethodName                      = "/api.bom.v1.BomService/CreateSessionLine"
	BomService_PatchSessionLine_FullMethodName                       = "/api.bom.v1.BomService/PatchSessionLine"
	BomService_DeleteSessionLine_FullMethodName                      = "/api.bom.v1.BomService/DeleteSessionLine"
	BomService_RetrySearchTasks_FullMethodName                       = "/api.bom.v1.BomService/RetrySearchTasks"
	BomService_SubmitBomSearchResult_FullMethodName                  = "/api.bom.v1.BomService/SubmitBomSearchResult"
	BomService_ListLineGaps_FullMethodName                           = "/api.bom.v1.BomService/ListLineGaps"
	BomService_ResolveLineGapManualQuote_FullMethodName              = "/api.bom.v1.BomService/ResolveLineGapManualQuote"
	BomService_SelectLineGapSubstitute_FullMethodName                = "/api.bom.v1.BomService/SelectLineGapSubstitute"
	BomService_SaveMatchRun_FullMethodName                           = "/api.bom.v1.BomService/SaveMatchRun"
	BomService_ListMatchRuns_FullMethodName                          = "/api.bom.v1.BomService/ListMatchRuns"
	BomService_GetMatchRun_FullMethodName                            = "/api.bom.v1.BomService/GetMatchRun"
	BomService_ExportSession_FullMethodName                          = "/api.bom.v1.BomService/ExportSession"
)

// BomServiceClient is the client API for BomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BOM 配单服务
type BomServiceClient interface {
	// 上传并解析 BOM
	UploadBOM(ctx context.Context, in *UploadBOMRequest, opts ...grpc.CallOption) (*UploadBOMReply, error)
	// 多平台搜索报价
	SearchQuotes(ctx context.Context, in *SearchQuotesRequest, opts ...grpc.CallOption) (*SearchQuotesReply, error)
	// 自动配单
	AutoMatch(ctx context.Context, in *AutoMatchRequest, opts ...grpc.CallOption) (*AutoMatchReply, error)
	// 下载 BOM 模板
	DownloadTemplate(ctx context.Context, in *DownloadTemplateRequest, opts ...grpc.CallOption) (*DownloadTemplateReply, error)
	// 厂牌别名：规范 ID 下拉数据 + 写入 t_bom_manufacturer_alias（配单页「厂牌别名审核」）
	ListManufacturerCanonicals(ctx context.Context, in *ListManufacturerCanonicalsRequest, opts ...grpc.CallOption) (*ListManufacturerCanonicalsReply, error)
	CreateManufacturerAlias(ctx context.Context, in *CreateManufacturerAliasRequest, opts ...grpc.CallOption) (*CreateManufacturerAliasReply, error)
	// 厂牌两阶段清洗 — 阶段一：需求行候选 + 审批（仅回填 session_line）
	ListSessionLineMfrCandidates(ctx context.Context, in *ListSessionLineMfrCandidatesRequest, opts ...grpc.CallOption) (*ListSessionLineMfrCandidatesReply, error)
	ApproveSessionLineMfrCleaning(ctx context.Context, in *ApproveSessionLineMfrCleaningRequest, opts ...grpc.CallOption) (*ApproveSessionLineMfrCleaningReply, error)
	// 厂牌两阶段清洗 — 阶段二：报价明细评审列表（与 GetReadiness.include_quote_item_mfr_reviews 同源；保留独立 GET 供旧客户端）
	ListQuoteItemMfrReviews(ctx context.Context, in *ListQuoteItemMfrReviewsRequest, opts ...grpc.CallOption) (*ListQuoteItemMfrReviewsReply, error)
	SubmitQuoteItemMfrReview(ctx context.Context, in *SubmitQuoteItemMfrReviewRequest, opts ...grpc.CallOption) (*SubmitQuoteItemMfrReviewReply, error)
	ApplyKnownManufacturerAliasesToSession(ctx context.Context, in *ApplyKnownManufacturerAliasesToSessionRequest, opts ...grpc.CallOption) (*ApplyKnownManufacturerAliasesToSessionReply, error)
	// 获取 BOM 详情（含解析结果）
	GetBOM(ctx context.Context, in *GetBOMRequest, opts ...grpc.CallOption) (*GetBOMReply, error)
	// 获取配单结果
	GetMatchResult(ctx context.Context, in *GetMatchResultRequest, opts ...grpc.CallOption) (*GetMatchResultReply, error)
	// 配单诊断：各行 × 会话勾选平台的报价缓存命中与跳过原因（不要求 BOM_NOT_READY）
	ListMatchSources(ctx context.Context, in *ListMatchSourcesRequest, opts ...grpc.CallOption) (*ListMatchSourcesReply, error)
	// 单行单平台：原始 quotes_json / no_mpn_detail（与 web/src/api/bomMatchExtras.ts 对齐）
	GetMatchSourceDetail(ctx context.Context, in *GetMatchSourceDetailRequest, opts ...grpc.CallOption) (*GetMatchSourceDetailReply, error)
	// 单行：t_bom_session_line 原始需求 + 经 t_bom_quote_cache 关联的 t_bom_quote_item 全表明细（运营审查）
	GetBomLineQuoteItems(ctx context.Context, in *GetBomLineQuoteItemsRequest, opts ...grpc.CallOption) (*GetBomLineQuoteItemsReply, error)
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionReply, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionReply, error)
	// 会话列表（分页、筛选）
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsReply, error)
	// 更新会话头信息（标题、客户联系方式等）
	PatchSession(ctx context.Context, in *PatchSessionRequest, opts ...grpc.CallOption) (*GetSessionReply, error)
	PutPlatforms(ctx context.Context, in *PutPlatformsRequest, opts ...grpc.CallOption) (*PutPlatformsReply, error)
	GetReadiness(ctx context.Context, in *GetReadinessRequest, opts ...grpc.CallOption) (*GetReadinessReply, error)
	GetBOMLines(ctx context.Context, in *GetBOMLinesRequest, opts ...grpc.CallOption) (*GetBOMLinesReply, error)
	// 只读：检查当前行×勾选平台 与 bom_search_task 是否对齐（不写入）
	GetSessionSearchTaskCoverage(ctx context.Context, in *GetSessionSearchTaskCoverageRequest, opts ...grpc.CallOption) (*GetSessionSearchTaskCoverageReply, error)
	ListSessionSearchTasks(ctx context.Context, in *ListSessionSearchTasksRequest, opts ...grpc.CallOption) (*ListSessionSearchTasksReply, error)
	// 追加一行
	CreateSessionLine(ctx context.Context, in *CreateSessionLineRequest, opts ...grpc.CallOption) (*CreateSessionLineReply, error)
	// 更新一行
	PatchSessionLine(ctx context.Context, in *PatchSessionLineRequest, opts ...grpc.CallOption) (*PatchSessionLineReply, error)
	// 删除一行
	DeleteSessionLine(ctx context.Context, in *DeleteSessionLineRequest, opts ...grpc.CallOption) (*DeleteSessionLineReply, error)
	RetrySearchTasks(ctx context.Context, in *RetrySearchTasksRequest, opts ...grpc.CallOption) (*RetrySearchTasksReply, error)
	// Agent 回写单行搜索任务结果（写 bom_search_task + bom_quote_cache）
	SubmitBomSearchResult(ctx context.Context, in *SubmitBomSearchResultRequest, opts ...grpc.CallOption) (*SubmitBomSearchResultReply, error)
	// 导出会话 BOM 行（Excel/CSV），见 docs/BOM货源搜索-接口清单.md §7
	ListLineGaps(ctx context.Context, in *ListLineGapsRequest, opts ...grpc.CallOption) (*ListLineGapsReply, error)
	ResolveLineGapManualQuote(ctx context.Context, in *ResolveLineGapManualQuoteRequest, opts ...grpc.CallOption) (*ResolveLineGapManualQuoteReply, error)
	SelectLineGapSubstitute(ctx context.Context, in *SelectLineGapSubstituteRequest, opts ...grpc.CallOption) (*SelectLineGapSubstituteReply, error)
	SaveMatchRun(ctx context.Context, in *SaveMatchRunRequest, opts ...grpc.CallOption) (*SaveMatchRunReply, error)
	ListMatchRuns(ctx context.Context, in *ListMatchRunsRequest, opts ...grpc.CallOption) (*ListMatchRunsReply, error)
	GetMatchRun(ctx context.Context, in *GetMatchRunRequest, opts ...grpc.CallOption) (*GetMatchRunReply, error)
	ExportSession(ctx context.Context, in *ExportSessionRequest, opts ...grpc.CallOption) (*ExportSessionReply, error)
}

type bomServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBomServiceClient(cc grpc.ClientConnInterface) BomServiceClient {
	return &bomServiceClient{cc}
}

func (c *bomServiceClient) UploadBOM(ctx context.Context, in *UploadBOMRequest, opts ...grpc.CallOption) (*UploadBOMReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadBOMReply)
	err := c.cc.Invoke(ctx, BomService_UploadBOM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) SearchQuotes(ctx context.Context, in *SearchQuotesRequest, opts ...grpc.CallOption) (*SearchQuotesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchQuotesReply)
	err := c.cc.Invoke(ctx, BomService_SearchQuotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) AutoMatch(ctx context.Context, in *AutoMatchRequest, opts ...grpc.CallOption) (*AutoMatchReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AutoMatchReply)
	err := c.cc.Invoke(ctx, BomService_AutoMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) DownloadTemplate(ctx context.Context, in *DownloadTemplateRequest, opts ...grpc.CallOption) (*DownloadTemplateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadTemplateReply)
	err := c.cc.Invoke(ctx, BomService_DownloadTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) ListManufacturerCanonicals(ctx context.Context, in *ListManufacturerCanonicalsRequest, opts ...grpc.CallOption) (*ListManufacturerCanonicalsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListManufacturerCanonicalsReply)
	err := c.cc.Invoke(ctx, BomService_ListManufacturerCanonicals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) CreateManufacturerAlias(ctx context.Context, in *CreateManufacturerAliasRequest, opts ...grpc.CallOption) (*CreateManufacturerAliasReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateManufacturerAliasReply)
	err := c.cc.Invoke(ctx, BomService_CreateManufacturerAlias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) ListSessionLineMfrCandidates(ctx context.Context, in *ListSessionLineMfrCandidatesRequest, opts ...grpc.CallOption) (*ListSessionLineMfrCandidatesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionLineMfrCandidatesReply)
	err := c.cc.Invoke(ctx, BomService_ListSessionLineMfrCandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) ApproveSessionLineMfrCleaning(ctx context.Context, in *ApproveSessionLineMfrCleaningRequest, opts ...grpc.CallOption) (*ApproveSessionLineMfrCleaningReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveSessionLineMfrCleaningReply)
	err := c.cc.Invoke(ctx, BomService_ApproveSessionLineMfrCleaning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) ListQuoteItemMfrReviews(ctx context.Context, in *ListQuoteItemMfrReviewsRequest, opts ...grpc.CallOption) (*ListQuoteItemMfrReviewsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListQuoteItemMfrReviewsReply)
	err := c.cc.Invoke(ctx, BomService_ListQuoteItemMfrReviews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) SubmitQuoteItemMfrReview(ctx context.Context, in *SubmitQuoteItemMfrReviewRequest, opts ...grpc.CallOption) (*SubmitQuoteItemMfrReviewReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitQuoteItemMfrReviewReply)
	err := c.cc.Invoke(ctx, BomService_SubmitQuoteItemMfrReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) ApplyKnownManufacturerAliasesToSession(ctx context.Context, in *ApplyKnownManufacturerAliasesToSessionRequest, opts ...grpc.CallOption) (*ApplyKnownManufacturerAliasesToSessionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyKnownManufacturerAliasesToSessionReply)
	err := c.cc.Invoke(ctx, BomService_ApplyKnownManufacturerAliasesToSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) GetBOM(ctx context.Context, in *GetBOMRequest, opts ...grpc.CallOption) (*GetBOMReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBOMReply)
	err := c.cc.Invoke(ctx, BomService_GetBOM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) GetMatchResult(ctx context.Context, in *GetMatchResultRequest, opts ...grpc.CallOption) (*GetMatchResultReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMatchResultReply)
	err := c.cc.Invoke(ctx, BomService_GetMatchResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) ListMatchSources(ctx context.Context, in *ListMatchSourcesRequest, opts ...grpc.CallOption) (*ListMatchSourcesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMatchSourcesReply)
	err := c.cc.Invoke(ctx, BomService_ListMatchSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) GetMatchSourceDetail(ctx context.Context, in *GetMatchSourceDetailRequest, opts ...grpc.CallOption) (*GetMatchSourceDetailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMatchSourceDetailReply)
	err := c.cc.Invoke(ctx, BomService_GetMatchSourceDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) GetBomLineQuoteItems(ctx context.Context, in *GetBomLineQuoteItemsRequest, opts ...grpc.CallOption) (*GetBomLineQuoteItemsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBomLineQuoteItemsReply)
	err := c.cc.Invoke(ctx, BomService_GetBomLineQuoteItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionReply)
	err := c.cc.Invoke(ctx, BomService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionReply)
	err := c.cc.Invoke(ctx, BomService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsReply)
	err := c.cc.Invoke(ctx, BomService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) PatchSession(ctx context.Context, in *PatchSessionRequest, opts ...grpc.CallOption) (*GetSessionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionReply)
	err := c.cc.Invoke(ctx, BomService_PatchSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) PutPlatforms(ctx context.Context, in *PutPlatformsRequest, opts ...grpc.CallOption) (*PutPlatformsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutPlatformsReply)
	err := c.cc.Invoke(ctx, BomService_PutPlatforms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) GetReadiness(ctx context.Context, in *GetReadinessRequest, opts ...grpc.CallOption) (*GetReadinessReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReadinessReply)
	err := c.cc.Invoke(ctx, BomService_GetReadiness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) GetBOMLines(ctx context.Context, in *GetBOMLinesRequest, opts ...grpc.CallOption) (*GetBOMLinesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBOMLinesReply)
	err := c.cc.Invoke(ctx, BomService_GetBOMLines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) GetSessionSearchTaskCoverage(ctx context.Context, in *GetSessionSearchTaskCoverageRequest, opts ...grpc.CallOption) (*GetSessionSearchTaskCoverageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionSearchTaskCoverageReply)
	err := c.cc.Invoke(ctx, BomService_GetSessionSearchTaskCoverage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) ListSessionSearchTasks(ctx context.Context, in *ListSessionSearchTasksRequest, opts ...grpc.CallOption) (*ListSessionSearchTasksReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionSearchTasksReply)
	err := c.cc.Invoke(ctx, BomService_ListSessionSearchTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) CreateSessionLine(ctx context.Context, in *CreateSessionLineRequest, opts ...grpc.CallOption) (*CreateSessionLineReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionLineReply)
	err := c.cc.Invoke(ctx, BomService_CreateSessionLine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) PatchSessionLine(ctx context.Context, in *PatchSessionLineRequest, opts ...grpc.CallOption) (*PatchSessionLineReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatchSessionLineReply)
	err := c.cc.Invoke(ctx, BomService_PatchSessionLine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) DeleteSessionLine(ctx context.Context, in *DeleteSessionLineRequest, opts ...grpc.CallOption) (*DeleteSessionLineReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSessionLineReply)
	err := c.cc.Invoke(ctx, BomService_DeleteSessionLine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) RetrySearchTasks(ctx context.Context, in *RetrySearchTasksRequest, opts ...grpc.CallOption) (*RetrySearchTasksReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrySearchTasksReply)
	err := c.cc.Invoke(ctx, BomService_RetrySearchTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) SubmitBomSearchResult(ctx context.Context, in *SubmitBomSearchResultRequest, opts ...grpc.CallOption) (*SubmitBomSearchResultReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitBomSearchResultReply)
	err := c.cc.Invoke(ctx, BomService_SubmitBomSearchResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) ListLineGaps(ctx context.Context, in *ListLineGapsRequest, opts ...grpc.CallOption) (*ListLineGapsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLineGapsReply)
	err := c.cc.Invoke(ctx, BomService_ListLineGaps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) ResolveLineGapManualQuote(ctx context.Context, in *ResolveLineGapManualQuoteRequest, opts ...grpc.CallOption) (*ResolveLineGapManualQuoteReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveLineGapManualQuoteReply)
	err := c.cc.Invoke(ctx, BomService_ResolveLineGapManualQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) SelectLineGapSubstitute(ctx context.Context, in *SelectLineGapSubstituteRequest, opts ...grpc.CallOption) (*SelectLineGapSubstituteReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectLineGapSubstituteReply)
	err := c.cc.Invoke(ctx, BomService_SelectLineGapSubstitute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) SaveMatchRun(ctx context.Context, in *SaveMatchRunRequest, opts ...grpc.CallOption) (*SaveMatchRunReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveMatchRunReply)
	err := c.cc.Invoke(ctx, BomService_SaveMatchRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) ListMatchRuns(ctx context.Context, in *ListMatchRunsRequest, opts ...grpc.CallOption) (*ListMatchRunsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMatchRunsReply)
	err := c.cc.Invoke(ctx, BomService_ListMatchRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) GetMatchRun(ctx context.Context, in *GetMatchRunRequest, opts ...grpc.CallOption) (*GetMatchRunReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMatchRunReply)
	err := c.cc.Invoke(ctx, BomService_GetMatchRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bomServiceClient) ExportSession(ctx context.Context, in *ExportSessionRequest, opts ...grpc.CallOption) (*ExportSessionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportSessionReply)
	err := c.cc.Invoke(ctx, BomService_ExportSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BomServiceServer is the server API for BomService service.
// All implementations must embed UnimplementedBomServiceServer
// for forward compatibility.
//
// BOM 配单服务
type BomServiceServer interface {
	// 上传并解析 BOM
	UploadBOM(context.Context, *UploadBOMRequest) (*UploadBOMReply, error)
	// 多平台搜索报价
	SearchQuotes(context.Context, *SearchQuotesRequest) (*SearchQuotesReply, error)
	// 自动配单
	AutoMatch(context.Context, *AutoMatchRequest) (*AutoMatchReply, error)
	// 下载 BOM 模板
	DownloadTemplate(context.Context, *DownloadTemplateRequest) (*DownloadTemplateReply, error)
	// 厂牌别名：规范 ID 下拉数据 + 写入 t_bom_manufacturer_alias（配单页「厂牌别名审核」）
	ListManufacturerCanonicals(context.Context, *ListManufacturerCanonicalsRequest) (*ListManufacturerCanonicalsReply, error)
	CreateManufacturerAlias(context.Context, *CreateManufacturerAliasRequest) (*CreateManufacturerAliasReply, error)
	// 厂牌两阶段清洗 — 阶段一：需求行候选 + 审批（仅回填 session_line）
	ListSessionLineMfrCandidates(context.Context, *ListSessionLineMfrCandidatesRequest) (*ListSessionLineMfrCandidatesReply, error)
	ApproveSessionLineMfrCleaning(context.Context, *ApproveSessionLineMfrCleaningRequest) (*ApproveSessionLineMfrCleaningReply, error)
	// 厂牌两阶段清洗 — 阶段二：报价明细评审列表（与 GetReadiness.include_quote_item_mfr_reviews 同源；保留独立 GET 供旧客户端）
	ListQuoteItemMfrReviews(context.Context, *ListQuoteItemMfrReviewsRequest) (*ListQuoteItemMfrReviewsReply, error)
	SubmitQuoteItemMfrReview(context.Context, *SubmitQuoteItemMfrReviewRequest) (*SubmitQuoteItemMfrReviewReply, error)
	ApplyKnownManufacturerAliasesToSession(context.Context, *ApplyKnownManufacturerAliasesToSessionRequest) (*ApplyKnownManufacturerAliasesToSessionReply, error)
	// 获取 BOM 详情（含解析结果）
	GetBOM(context.Context, *GetBOMRequest) (*GetBOMReply, error)
	// 获取配单结果
	GetMatchResult(context.Context, *GetMatchResultRequest) (*GetMatchResultReply, error)
	// 配单诊断：各行 × 会话勾选平台的报价缓存命中与跳过原因（不要求 BOM_NOT_READY）
	ListMatchSources(context.Context, *ListMatchSourcesRequest) (*ListMatchSourcesReply, error)
	// 单行单平台：原始 quotes_json / no_mpn_detail（与 web/src/api/bomMatchExtras.ts 对齐）
	GetMatchSourceDetail(context.Context, *GetMatchSourceDetailRequest) (*GetMatchSourceDetailReply, error)
	// 单行：t_bom_session_line 原始需求 + 经 t_bom_quote_cache 关联的 t_bom_quote_item 全表明细（运营审查）
	GetBomLineQuoteItems(context.Context, *GetBomLineQuoteItemsRequest) (*GetBomLineQuoteItemsReply, error)
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionReply, error)
	GetSession(context.Context, *GetSessionRequest) (*GetSessionReply, error)
	// 会话列表（分页、筛选）
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsReply, error)
	// 更新会话头信息（标题、客户联系方式等）
	PatchSession(context.Context, *PatchSessionRequest) (*GetSessionReply, error)
	PutPlatforms(context.Context, *PutPlatformsRequest) (*PutPlatformsReply, error)
	GetReadiness(context.Context, *GetReadinessRequest) (*GetReadinessReply, error)
	GetBOMLines(context.Context, *GetBOMLinesRequest) (*GetBOMLinesReply, error)
	// 只读：检查当前行×勾选平台 与 bom_search_task 是否对齐（不写入）
	GetSessionSearchTaskCoverage(context.Context, *GetSessionSearchTaskCoverageRequest) (*GetSessionSearchTaskCoverageReply, error)
	ListSessionSearchTasks(context.Context, *ListSessionSearchTasksRequest) (*ListSessionSearchTasksReply, error)
	// 追加一行
	CreateSessionLine(context.Context, *CreateSessionLineRequest) (*CreateSessionLineReply, error)
	// 更新一行
	PatchSessionLine(context.Context, *PatchSessionLineRequest) (*PatchSessionLineReply, error)
	// 删除一行
	DeleteSessionLine(context.Context, *DeleteSessionLineRequest) (*DeleteSessionLineReply, error)
	RetrySearchTasks(context.Context, *RetrySearchTasksRequest) (*RetrySearchTasksReply, error)
	// Agent 回写单行搜索任务结果（写 bom_search_task + bom_quote_cache）
	SubmitBomSearchResult(context.Context, *SubmitBomSearchResultRequest) (*SubmitBomSearchResultReply, error)
	// 导出会话 BOM 行（Excel/CSV），见 docs/BOM货源搜索-接口清单.md §7
	ListLineGaps(context.Context, *ListLineGapsRequest) (*ListLineGapsReply, error)
	ResolveLineGapManualQuote(context.Context, *ResolveLineGapManualQuoteRequest) (*ResolveLineGapManualQuoteReply, error)
	SelectLineGapSubstitute(context.Context, *SelectLineGapSubstituteRequest) (*SelectLineGapSubstituteReply, error)
	SaveMatchRun(context.Context, *SaveMatchRunRequest) (*SaveMatchRunReply, error)
	ListMatchRuns(context.Context, *ListMatchRunsRequest) (*ListMatchRunsReply, error)
	GetMatchRun(context.Context, *GetMatchRunRequest) (*GetMatchRunReply, error)
	ExportSession(context.Context, *ExportSessionRequest) (*ExportSessionReply, error)
	mustEmbedUnimplementedBomServiceServer()
}

// UnimplementedBomServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBomServiceServer struct{}

func (UnimplementedBomServiceServer) UploadBOM(context.Context, *UploadBOMRequest) (*UploadBOMReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadBOM not implemented")
}
func (UnimplementedBomServiceServer) SearchQuotes(context.Context, *SearchQuotesRequest) (*SearchQuotesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchQuotes not implemented")
}
func (UnimplementedBomServiceServer) AutoMatch(context.Context, *AutoMatchRequest) (*AutoMatchReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AutoMatch not implemented")
}
func (UnimplementedBomServiceServer) DownloadTemplate(context.Context, *DownloadTemplateRequest) (*DownloadTemplateReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadTemplate not implemented")
}
func (UnimplementedBomServiceServer) ListManufacturerCanonicals(context.Context, *ListManufacturerCanonicalsRequest) (*ListManufacturerCanonicalsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListManufacturerCanonicals not implemented")
}
func (UnimplementedBomServiceServer) CreateManufacturerAlias(context.Context, *CreateManufacturerAliasRequest) (*CreateManufacturerAliasReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateManufacturerAlias not implemented")
}
func (UnimplementedBomServiceServer) ListSessionLineMfrCandidates(context.Context, *ListSessionLineMfrCandidatesRequest) (*ListSessionLineMfrCandidatesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessionLineMfrCandidates not implemented")
}
func (UnimplementedBomServiceServer) ApproveSessionLineMfrCleaning(context.Context, *ApproveSessionLineMfrCleaningRequest) (*ApproveSessionLineMfrCleaningReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveSessionLineMfrCleaning not implemented")
}
func (UnimplementedBomServiceServer) ListQuoteItemMfrReviews(context.Context, *ListQuoteItemMfrReviewsRequest) (*ListQuoteItemMfrReviewsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListQuoteItemMfrReviews not implemented")
}
func (UnimplementedBomServiceServer) SubmitQuoteItemMfrReview(context.Context, *SubmitQuoteItemMfrReviewRequest) (*SubmitQuoteItemMfrReviewReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitQuoteItemMfrReview not implemented")
}
func (UnimplementedBomServiceServer) ApplyKnownManufacturerAliasesToSession(context.Context, *ApplyKnownManufacturerAliasesToSessionRequest) (*ApplyKnownManufacturerAliasesToSessionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyKnownManufacturerAliasesToSession not implemented")
}
func (UnimplementedBomServiceServer) GetBOM(context.Context, *GetBOMRequest) (*GetBOMReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBOM not implemented")
}
func (UnimplementedBomServiceServer) GetMatchResult(context.Context, *GetMatchResultRequest) (*GetMatchResultReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMatchResult not implemented")
}
func (UnimplementedBomServiceServer) ListMatchSources(context.Context, *ListMatchSourcesRequest) (*ListMatchSourcesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMatchSources not implemented")
}
func (UnimplementedBomServiceServer) GetMatchSourceDetail(context.Context, *GetMatchSourceDetailRequest) (*GetMatchSourceDetailReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMatchSourceDetail not implemented")
}
func (UnimplementedBomServiceServer) GetBomLineQuoteItems(context.Context, *GetBomLineQuoteItemsRequest) (*GetBomLineQuoteItemsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBomLineQuoteItems not implemented")
}
func (UnimplementedBomServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedBomServiceServer) GetSession(context.Context, *GetSessionRequest) (*GetSessionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedBomServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedBomServiceServer) PatchSession(context.Context, *PatchSessionRequest) (*GetSessionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PatchSession not implemented")
}
func (UnimplementedBomServiceServer) PutPlatforms(context.Context, *PutPlatformsRequest) (*PutPlatformsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PutPlatforms not implemented")
}
func (UnimplementedBomServiceServer) GetReadiness(context.Context, *GetReadinessRequest) (*GetReadinessReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReadiness not implemented")
}
func (UnimplementedBomServiceServer) GetBOMLines(context.Context, *GetBOMLinesRequest) (*GetBOMLinesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBOMLines not implemented")
}
func (UnimplementedBomServiceServer) GetSessionSearchTaskCoverage(context.Context, *GetSessionSearchTaskCoverageRequest) (*GetSessionSearchTaskCoverageReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionSearchTaskCoverage not implemented")
}
func (UnimplementedBomServiceServer) ListSessionSearchTasks(context.Context, *ListSessionSearchTasksRequest) (*ListSessionSearchTasksReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessionSearchTasks not implemented")
}
func (UnimplementedBomServiceServer) CreateSessionLine(context.Context, *CreateSessionLineRequest) (*CreateSessionLineReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSessionLine not implemented")
}
func (UnimplementedBomServiceServer) PatchSessionLine(context.Context, *PatchSessionLineRequest) (*PatchSessionLineReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PatchSessionLine not implemented")
}
func (UnimplementedBomServiceServer) DeleteSessionLine(context.Context, *DeleteSessionLineRequest) (*DeleteSessionLineReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSessionLine not implemented")
}
func (UnimplementedBomServiceServer) RetrySearchTasks(context.Context, *RetrySearchTasksRequest) (*RetrySearchTasksReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RetrySearchTasks not implemented")
}
func (UnimplementedBomServiceServer) SubmitBomSearchResult(context.Context, *SubmitBomSearchResultRequest) (*SubmitBomSearchResultReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitBomSearchResult not implemented")
}
func (UnimplementedBomServiceServer) ListLineGaps(context.Context, *ListLineGapsRequest) (*ListLineGapsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLineGaps not implemented")
}
func (UnimplementedBomServiceServer) ResolveLineGapManualQuote(context.Context, *ResolveLineGapManualQuoteRequest) (*ResolveLineGapManualQuoteReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveLineGapManualQuote not implemented")
}
func (UnimplementedBomServiceServer) SelectLineGapSubstitute(context.Context, *SelectLineGapSubstituteRequest) (*SelectLineGapSubstituteReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SelectLineGapSubstitute not implemented")
}
func (UnimplementedBomServiceServer) SaveMatchRun(context.Context, *SaveMatchRunRequest) (*SaveMatchRunReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveMatchRun not implemented")
}
func (UnimplementedBomServiceServer) ListMatchRuns(context.Context, *ListMatchRunsRequest) (*ListMatchRunsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMatchRuns not implemented")
}
func (UnimplementedBomServiceServer) GetMatchRun(context.Context, *GetMatchRunRequest) (*GetMatchRunReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMatchRun not implemented")
}
func (UnimplementedBomServiceServer) ExportSession(context.Context, *ExportSessionRequest) (*ExportSessionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportSession not implemented")
}
func (UnimplementedBomServiceServer) mustEmbedUnimplementedBomServiceServer() {}
func (UnimplementedBomServiceServer) testEmbeddedByValue()                    {}

// UnsafeBomServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BomServiceServer will
// result in compilation errors.
type UnsafeBomServiceServer interface {
	mustEmbedUnimplementedBomServiceServer()
}

func RegisterBomServiceServer(s grpc.ServiceRegistrar, srv BomServiceServer) {
	// If the following call panics, it indicates UnimplementedBomServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BomService_ServiceDesc, srv)
}

func _BomService_UploadBOM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadBOMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).UploadBOM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_UploadBOM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).UploadBOM(ctx, req.(*UploadBOMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_SearchQuotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchQuotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).SearchQuotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_SearchQuotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).SearchQuotes(ctx, req.(*SearchQuotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_AutoMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutoMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).AutoMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_AutoMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).AutoMatch(ctx, req.(*AutoMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_DownloadTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).DownloadTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_DownloadTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).DownloadTemplate(ctx, req.(*DownloadTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_ListManufacturerCanonicals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListManufacturerCanonicalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).ListManufacturerCanonicals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_ListManufacturerCanonicals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).ListManufacturerCanonicals(ctx, req.(*ListManufacturerCanonicalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_CreateManufacturerAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateManufacturerAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).CreateManufacturerAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_CreateManufacturerAlias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).CreateManufacturerAlias(ctx, req.(*CreateManufacturerAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_ListSessionLineMfrCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionLineMfrCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).ListSessionLineMfrCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_ListSessionLineMfrCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).ListSessionLineMfrCandidates(ctx, req.(*ListSessionLineMfrCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_ApproveSessionLineMfrCleaning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveSessionLineMfrCleaningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).ApproveSessionLineMfrCleaning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_ApproveSessionLineMfrCleaning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).ApproveSessionLineMfrCleaning(ctx, req.(*ApproveSessionLineMfrCleaningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_ListQuoteItemMfrReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQuoteItemMfrReviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).ListQuoteItemMfrReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_ListQuoteItemMfrReviews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).ListQuoteItemMfrReviews(ctx, req.(*ListQuoteItemMfrReviewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_SubmitQuoteItemMfrReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitQuoteItemMfrReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).SubmitQuoteItemMfrReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_SubmitQuoteItemMfrReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).SubmitQuoteItemMfrReview(ctx, req.(*SubmitQuoteItemMfrReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_ApplyKnownManufacturerAliasesToSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyKnownManufacturerAliasesToSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).ApplyKnownManufacturerAliasesToSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_ApplyKnownManufacturerAliasesToSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).ApplyKnownManufacturerAliasesToSession(ctx, req.(*ApplyKnownManufacturerAliasesToSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_GetBOM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBOMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).GetBOM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_GetBOM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).GetBOM(ctx, req.(*GetBOMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_GetMatchResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).GetMatchResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_GetMatchResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).GetMatchResult(ctx, req.(*GetMatchResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_ListMatchSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMatchSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).ListMatchSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_ListMatchSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).ListMatchSources(ctx, req.(*ListMatchSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_GetMatchSourceDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchSourceDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).GetMatchSourceDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_GetMatchSourceDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).GetMatchSourceDetail(ctx, req.(*GetMatchSourceDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_GetBomLineQuoteItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBomLineQuoteItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).GetBomLineQuoteItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_GetBomLineQuoteItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).GetBomLineQuoteItems(ctx, req.(*GetBomLineQuoteItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_PatchSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).PatchSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_PatchSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).PatchSession(ctx, req.(*PatchSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_PutPlatforms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutPlatformsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).PutPlatforms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_PutPlatforms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).PutPlatforms(ctx, req.(*PutPlatformsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_GetReadiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReadinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).GetReadiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_GetReadiness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).GetReadiness(ctx, req.(*GetReadinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_GetBOMLines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBOMLinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).GetBOMLines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_GetBOMLines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).GetBOMLines(ctx, req.(*GetBOMLinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_GetSessionSearchTaskCoverage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionSearchTaskCoverageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).GetSessionSearchTaskCoverage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_GetSessionSearchTaskCoverage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).GetSessionSearchTaskCoverage(ctx, req.(*GetSessionSearchTaskCoverageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_ListSessionSearchTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionSearchTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).ListSessionSearchTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_ListSessionSearchTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).ListSessionSearchTasks(ctx, req.(*ListSessionSearchTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_CreateSessionLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).CreateSessionLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_CreateSessionLine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).CreateSessionLine(ctx, req.(*CreateSessionLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_PatchSessionLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchSessionLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).PatchSessionLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_PatchSessionLine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).PatchSessionLine(ctx, req.(*PatchSessionLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_DeleteSessionLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).DeleteSessionLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_DeleteSessionLine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).DeleteSessionLine(ctx, req.(*DeleteSessionLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_RetrySearchTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrySearchTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).RetrySearchTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_RetrySearchTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).RetrySearchTasks(ctx, req.(*RetrySearchTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_SubmitBomSearchResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitBomSearchResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).SubmitBomSearchResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_SubmitBomSearchResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).SubmitBomSearchResult(ctx, req.(*SubmitBomSearchResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_ListLineGaps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLineGapsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).ListLineGaps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_ListLineGaps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).ListLineGaps(ctx, req.(*ListLineGapsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_ResolveLineGapManualQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveLineGapManualQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).ResolveLineGapManualQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_ResolveLineGapManualQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).ResolveLineGapManualQuote(ctx, req.(*ResolveLineGapManualQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_SelectLineGapSubstitute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectLineGapSubstituteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).SelectLineGapSubstitute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_SelectLineGapSubstitute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).SelectLineGapSubstitute(ctx, req.(*SelectLineGapSubstituteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_SaveMatchRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMatchRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).SaveMatchRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_SaveMatchRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).SaveMatchRun(ctx, req.(*SaveMatchRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_ListMatchRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMatchRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).ListMatchRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_ListMatchRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).ListMatchRuns(ctx, req.(*ListMatchRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_GetMatchRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).GetMatchRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_GetMatchRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).GetMatchRun(ctx, req.(*GetMatchRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BomService_ExportSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BomServiceServer).ExportSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BomService_ExportSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BomServiceServer).ExportSession(ctx, req.(*ExportSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BomService_ServiceDesc is the grpc.ServiceDesc for BomService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BomService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.bom.v1.BomService",
	HandlerType: (*BomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadBOM",
			Handler:    _BomService_UploadBOM_Handler,
		},
		{
			MethodName: "SearchQuotes",
			Handler:    _BomService_SearchQuotes_Handler,
		},
		{
			MethodName: "AutoMatch",
			Handler:    _BomService_AutoMatch_Handler,
		},
		{
			MethodName: "DownloadTemplate",
			Handler:    _BomService_DownloadTemplate_Handler,
		},
		{
			MethodName: "ListManufacturerCanonicals",
			Handler:    _BomService_ListManufacturerCanonicals_Handler,
		},
		{
			MethodName: "CreateManufacturerAlias",
			Handler:    _BomService_CreateManufacturerAlias_Handler,
		},
		{
			MethodName: "ListSessionLineMfrCandidates",
			Handler:    _BomService_ListSessionLineMfrCandidates_Handler,
		},
		{
			MethodName: "ApproveSessionLineMfrCleaning",
			Handler:    _BomService_ApproveSessionLineMfrCleaning_Handler,
		},
		{
			MethodName: "ListQuoteItemMfrReviews",
			Handler:    _BomService_ListQuoteItemMfrReviews_Handler,
		},
		{
			MethodName: "SubmitQuoteItemMfrReview",
			Handler:    _BomService_SubmitQuoteItemMfrReview_Handler,
		},
		{
			MethodName: "ApplyKnownManufacturerAliasesToSession",
			Handler:    _BomService_ApplyKnownManufacturerAliasesToSession_Handler,
		},
		{
			MethodName: "GetBOM",
			Handler:    _BomService_GetBOM_Handler,
		},
		{
			MethodName: "GetMatchResult",
			Handler:    _BomService_GetMatchResult_Handler,
		},
		{
			MethodName: "ListMatchSources",
			Handler:    _BomService_ListMatchSources_Handler,
		},
		{
			MethodName: "GetMatchSourceDetail",
			Handler:    _BomService_GetMatchSourceDetail_Handler,
		},
		{
			MethodName: "GetBomLineQuoteItems",
			Handler:    _BomService_GetBomLineQuoteItems_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _BomService_CreateSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _BomService_GetSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _BomService_ListSessions_Handler,
		},
		{
			MethodName: "PatchSession",
			Handler:    _BomService_PatchSession_Handler,
		},
		{
			MethodName: "PutPlatforms",
			Handler:    _BomService_PutPlatforms_Handler,
		},
		{
			MethodName: "GetReadiness",
			Handler:    _BomService_GetReadiness_Handler,
		},
		{
			MethodName: "GetBOMLines",
			Handler:    _BomService_GetBOMLines_Handler,
		},
		{
			MethodName: "GetSessionSearchTaskCoverage",
			Handler:    _BomService_GetSessionSearchTaskCoverage_Handler,
		},
		{
			MethodName: "ListSessionSearchTasks",
			Handler:    _BomService_ListSessionSearchTasks_Handler,
		},
		{
			MethodName: "CreateSessionLine",
			Handler:    _BomService_CreateSessionLine_Handler,
		},
		{
			MethodName: "PatchSessionLine",
			Handler:    _BomService_PatchSessionLine_Handler,
		},
		{
			MethodName: "DeleteSessionLine",
			Handler:    _BomService_DeleteSessionLine_Handler,
		},
		{
			MethodName: "RetrySearchTasks",
			Handler:    _BomService_RetrySearchTasks_Handler,
		},
		{
			MethodName: "SubmitBomSearchResult",
			Handler:    _BomService_SubmitBomSearchResult_Handler,
		},
		{
			MethodName: "ListLineGaps",
			Handler:    _BomService_ListLineGaps_Handler,
		},
		{
			MethodName: "ResolveLineGapManualQuote",
			Handler:    _BomService_ResolveLineGapManualQuote_Handler,
		},
		{
			MethodName: "SelectLineGapSubstitute",
			Handler:    _BomService_SelectLineGapSubstitute_Handler,
		},
		{
			MethodName: "SaveMatchRun",
			Handler:    _BomService_SaveMatchRun_Handler,
		},
		{
			MethodName: "ListMatchRuns",
			Handler:    _BomService_ListMatchRuns_Handler,
		},
		{
			MethodName: "GetMatchRun",
			Handler:    _BomService_GetMatchRun_Handler,
		},
		{
			MethodName: "ExportSession",
			Handler:    _BomService_ExportSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bom/v1/bom.proto",
}

const (
	HsResolveService_ResolveByModel_FullMethodName          = "/api.bom.v1.HsResolveService/ResolveByModel"
	HsResolveService_GetResolveTask_FullMethodName          = "/api.bom.v1.HsResolveService/GetResolveTask"
	HsResolveService_ConfirmResolve_FullMethodName          = "/api.bom.v1.HsResolveService/ConfirmResolve"
	HsResolveService_GetResolveHistory_FullMethodName       = "/api.bom.v1.HsResolveService/GetResolveHistory"
	HsResolveService_UploadHsManualDatasheet_FullMethodName = "/api.bom.v1.HsResolveService/UploadHsManualDatasheet"
)

// HsResolveServiceClient is the client API for HsResolveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HS 型号解析服务
type HsResolveServiceClient interface {
	// 按型号触发解析；在同步超时内完成则直接返回，否则返回 task_id 供轮询
	ResolveByModel(ctx context.Context, in *HsResolveByModelRequest, opts ...grpc.CallOption) (*HsResolveByModelReply, error)
	// 查询单个任务状态与结果
	GetResolveTask(ctx context.Context, in *HsResolveTaskRequest, opts ...grpc.CallOption) (*HsResolveTaskReply, error)
	// 人工确认候选
	ConfirmResolve(ctx context.Context, in *HsResolveConfirmRequest, opts ...grpc.CallOption) (*HsResolveConfirmReply, error)
	// 查询历史结果与候选
	GetResolveHistory(ctx context.Context, in *HsResolveHistoryRequest, opts ...grpc.CallOption) (*HsResolveHistoryReply, error)
	// 上传手册 PDF（二进制走 file；HTTP 亦可 multipart，由服务端自定义路由绑定）
	UploadHsManualDatasheet(ctx context.Context, in *UploadHsManualDatasheetRequest, opts ...grpc.CallOption) (*UploadHsManualDatasheetReply, error)
}

type hsResolveServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHsResolveServiceClient(cc grpc.ClientConnInterface) HsResolveServiceClient {
	return &hsResolveServiceClient{cc}
}

func (c *hsResolveServiceClient) ResolveByModel(ctx context.Context, in *HsResolveByModelRequest, opts ...grpc.CallOption) (*HsResolveByModelReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HsResolveByModelReply)
	err := c.cc.Invoke(ctx, HsResolveService_ResolveByModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hsResolveServiceClient) GetResolveTask(ctx context.Context, in *HsResolveTaskRequest, opts ...grpc.CallOption) (*HsResolveTaskReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HsResolveTaskReply)
	err := c.cc.Invoke(ctx, HsResolveService_GetResolveTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hsResolveServiceClient) ConfirmResolve(ctx context.Context, in *HsResolveConfirmRequest, opts ...grpc.CallOption) (*HsResolveConfirmReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HsResolveConfirmReply)
	err := c.cc.Invoke(ctx, HsResolveService_ConfirmResolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hsResolveServiceClient) GetResolveHistory(ctx context.Context, in *HsResolveHistoryRequest, opts ...grpc.CallOption) (*HsResolveHistoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HsResolveHistoryReply)
	err := c.cc.Invoke(ctx, HsResolveService_GetResolveHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hsResolveServiceClient) UploadHsManualDatasheet(ctx context.Context, in *UploadHsManualDatasheetRequest, opts ...grpc.CallOption) (*UploadHsManualDatasheetReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadHsManualDatasheetReply)
	err := c.cc.Invoke(ctx, HsResolveService_UploadHsManualDatasheet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HsResolveServiceServer is the server API for HsResolveService service.
// All implementations must embed UnimplementedHsResolveServiceServer
// for forward compatibility.
//
// HS 型号解析服务
type HsResolveServiceServer interface {
	// 按型号触发解析；在同步超时内完成则直接返回，否则返回 task_id 供轮询
	ResolveByModel(context.Context, *HsResolveByModelRequest) (*HsResolveByModelReply, error)
	// 查询单个任务状态与结果
	GetResolveTask(context.Context, *HsResolveTaskRequest) (*HsResolveTaskReply, error)
	// 人工确认候选
	ConfirmResolve(context.Context, *HsResolveConfirmRequest) (*HsResolveConfirmReply, error)
	// 查询历史结果与候选
	GetResolveHistory(context.Context, *HsResolveHistoryRequest) (*HsResolveHistoryReply, error)
	// 上传手册 PDF（二进制走 file；HTTP 亦可 multipart，由服务端自定义路由绑定）
	UploadHsManualDatasheet(context.Context, *UploadHsManualDatasheetRequest) (*UploadHsManualDatasheetReply, error)
	mustEmbedUnimplementedHsResolveServiceServer()
}

// UnimplementedHsResolveServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHsResolveServiceServer struct{}

func (UnimplementedHsResolveServiceServer) ResolveByModel(context.Context, *HsResolveByModelRequest) (*HsResolveByModelReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveByModel not implemented")
}
func (UnimplementedHsResolveServiceServer) GetResolveTask(context.Context, *HsResolveTaskRequest) (*HsResolveTaskReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResolveTask not implemented")
}
func (UnimplementedHsResolveServiceServer) ConfirmResolve(context.Context, *HsResolveConfirmRequest) (*HsResolveConfirmReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmResolve not implemented")
}
func (UnimplementedHsResolveServiceServer) GetResolveHistory(context.Context, *HsResolveHistoryRequest) (*HsResolveHistoryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResolveHistory not implemented")
}
func (UnimplementedHsResolveServiceServer) UploadHsManualDatasheet(context.Context, *UploadHsManualDatasheetRequest) (*UploadHsManualDatasheetReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadHsManualDatasheet not implemented")
}
func (UnimplementedHsResolveServiceServer) mustEmbedUnimplementedHsResolveServiceServer() {}
func (UnimplementedHsResolveServiceServer) testEmbeddedByValue()                          {}

// UnsafeHsResolveServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HsResolveServiceServer will
// result in compilation errors.
type UnsafeHsResolveServiceServer interface {
	mustEmbedUnimplementedHsResolveServiceServer()
}

func RegisterHsResolveServiceServer(s grpc.ServiceRegistrar, srv HsResolveServiceServer) {
	// If the following call panics, it indicates UnimplementedHsResolveServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HsResolveService_ServiceDesc, srv)
}

func _HsResolveService_ResolveByModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HsResolveByModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HsResolveServiceServer).ResolveByModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HsResolveService_ResolveByModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HsResolveServiceServer).ResolveByModel(ctx, req.(*HsResolveByModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HsResolveService_GetResolveTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HsResolveTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HsResolveServiceServer).GetResolveTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HsResolveService_GetResolveTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HsResolveServiceServer).GetResolveTask(ctx, req.(*HsResolveTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HsResolveService_ConfirmResolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HsResolveConfirmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HsResolveServiceServer).ConfirmResolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HsResolveService_ConfirmResolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HsResolveServiceServer).ConfirmResolve(ctx, req.(*HsResolveConfirmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HsResolveService_GetResolveHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HsResolveHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HsResolveServiceServer).GetResolveHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HsResolveService_GetResolveHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HsResolveServiceServer).GetResolveHistory(ctx, req.(*HsResolveHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HsResolveService_UploadHsManualDatasheet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadHsManualDatasheetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HsResolveServiceServer).UploadHsManualDatasheet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HsResolveService_UploadHsManualDatasheet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HsResolveServiceServer).UploadHsManualDatasheet(ctx, req.(*UploadHsManualDatasheetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HsResolveService_ServiceDesc is the grpc.ServiceDesc for HsResolveService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HsResolveService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.bom.v1.HsResolveService",
	HandlerType: (*HsResolveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveByModel",
			Handler:    _HsResolveService_ResolveByModel_Handler,
		},
		{
			MethodName: "GetResolveTask",
			Handler:    _HsResolveService_GetResolveTask_Handler,
		},
		{
			MethodName: "ConfirmResolve",
			Handler:    _HsResolveService_ConfirmResolve_Handler,
		},
		{
			MethodName: "GetResolveHistory",
			Handler:    _HsResolveService_GetResolveHistory_Handler,
		},
		{
			MethodName: "UploadHsManualDatasheet",
			Handler:    _HsResolveService_UploadHsManualDatasheet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bom/v1/bom.proto",
}

const (
	HsMetaService_ListHsMeta_FullMethodName   = "/api.bom.v1.HsMetaService/ListHsMeta"
	HsMetaService_CreateHsMeta_FullMethodName = "/api.bom.v1.HsMetaService/CreateHsMeta"
	HsMetaService_UpdateHsMeta_FullMethodName = "/api.bom.v1.HsMetaService/UpdateHsMeta"
	HsMetaService_DeleteHsMeta_FullMethodName = "/api.bom.v1.HsMetaService/DeleteHsMeta"
)

// HsMetaServiceClient is the client API for HsMetaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HsMetaServiceClient interface {
	ListHsMeta(ctx context.Context, in *HsMetaListRequest, opts ...grpc.CallOption) (*HsMetaListReply, error)
	CreateHsMeta(ctx context.Context, in *HsMetaCreateRequest, opts ...grpc.CallOption) (*HsMetaMutationReply, error)
	UpdateHsMeta(ctx context.Context, in *HsMetaUpdateRequest, opts ...grpc.CallOption) (*HsMetaMutationReply, error)
	DeleteHsMeta(ctx context.Context, in *HsMetaDeleteRequest, opts ...grpc.CallOption) (*HsMetaMutationReply, error)
}

type hsMetaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHsMetaServiceClient(cc grpc.ClientConnInterface) HsMetaServiceClient {
	return &hsMetaServiceClient{cc}
}

func (c *hsMetaServiceClient) ListHsMeta(ctx context.Context, in *HsMetaListRequest, opts ...grpc.CallOption) (*HsMetaListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HsMetaListReply)
	err := c.cc.Invoke(ctx, HsMetaService_ListHsMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hsMetaServiceClient) CreateHsMeta(ctx context.Context, in *HsMetaCreateRequest, opts ...grpc.CallOption) (*HsMetaMutationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HsMetaMutationReply)
	err := c.cc.Invoke(ctx, HsMetaService_CreateHsMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hsMetaServiceClient) UpdateHsMeta(ctx context.Context, in *HsMetaUpdateRequest, opts ...grpc.CallOption) (*HsMetaMutationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HsMetaMutationReply)
	err := c.cc.Invoke(ctx, HsMetaService_UpdateHsMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hsMetaServiceClient) DeleteHsMeta(ctx context.Context, in *HsMetaDeleteRequest, opts ...grpc.CallOption) (*HsMetaMutationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HsMetaMutationReply)
	err := c.cc.Invoke(ctx, HsMetaService_DeleteHsMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HsMetaServiceServer is the server API for HsMetaService service.
// All implementations must embed UnimplementedHsMetaServiceServer
// for forward compatibility.
type HsMetaServiceServer interface {
	ListHsMeta(context.Context, *HsMetaListRequest) (*HsMetaListReply, error)
	CreateHsMeta(context.Context, *HsMetaCreateRequest) (*HsMetaMutationReply, error)
	UpdateHsMeta(context.Context, *HsMetaUpdateRequest) (*HsMetaMutationReply, error)
	DeleteHsMeta(context.Context, *HsMetaDeleteRequest) (*HsMetaMutationReply, error)
	mustEmbedUnimplementedHsMetaServiceServer()
}

// UnimplementedHsMetaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHsMetaServiceServer struct{}

func (UnimplementedHsMetaServiceServer) ListHsMeta(context.Context, *HsMetaListRequest) (*HsMetaListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHsMeta not implemented")
}
func (UnimplementedHsMetaServiceServer) CreateHsMeta(context.Context, *HsMetaCreateRequest) (*HsMetaMutationReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateHsMeta not implemented")
}
func (UnimplementedHsMetaServiceServer) UpdateHsMeta(context.Context, *HsMetaUpdateRequest) (*HsMetaMutationReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateHsMeta not implemented")
}
func (UnimplementedHsMetaServiceServer) DeleteHsMeta(context.Context, *HsMetaDeleteRequest) (*HsMetaMutationReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteHsMeta not implemented")
}
func (UnimplementedHsMetaServiceServer) mustEmbedUnimplementedHsMetaServiceServer() {}
func (UnimplementedHsMetaServiceServer) testEmbeddedByValue()                       {}

// UnsafeHsMetaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HsMetaServiceServer will
// result in compilation errors.
type UnsafeHsMetaServiceServer interface {
	mustEmbedUnimplementedHsMetaServiceServer()
}

func RegisterHsMetaServiceServer(s grpc.ServiceRegistrar, srv HsMetaServiceServer) {
	// If the following call panics, it indicates UnimplementedHsMetaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HsMetaService_ServiceDesc, srv)
}

func _HsMetaService_ListHsMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HsMetaListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HsMetaServiceServer).ListHsMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HsMetaService_ListHsMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HsMetaServiceServer).ListHsMeta(ctx, req.(*HsMetaListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HsMetaService_CreateHsMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HsMetaCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HsMetaServiceServer).CreateHsMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HsMetaService_CreateHsMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HsMetaServiceServer).CreateHsMeta(ctx, req.(*HsMetaCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HsMetaService_UpdateHsMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HsMetaUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HsMetaServiceServer).UpdateHsMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HsMetaService_UpdateHsMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HsMetaServiceServer).UpdateHsMeta(ctx, req.(*HsMetaUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HsMetaService_DeleteHsMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HsMetaDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HsMetaServiceServer).DeleteHsMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HsMetaService_DeleteHsMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HsMetaServiceServer).DeleteHsMeta(ctx, req.(*HsMetaDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HsMetaService_ServiceDesc is the grpc.ServiceDesc for HsMetaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HsMetaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.bom.v1.HsMetaService",
	HandlerType: (*HsMetaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListHsMeta",
			Handler:    _HsMetaService_ListHsMeta_Handler,
		},
		{
			MethodName: "CreateHsMeta",
			Handler:    _HsMetaService_CreateHsMeta_Handler,
		},
		{
			MethodName: "UpdateHsMeta",
			Handler:    _HsMetaService_UpdateHsMeta_Handler,
		},
		{
			MethodName: "DeleteHsMeta",
			Handler:    _HsMetaService_DeleteHsMeta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bom/v1/bom.proto",
}
