// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.0
// source: bom/v1/bom.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationBomServiceAutoMatch = "/api.bom.v1.BomService/AutoMatch"
const OperationBomServiceCreateManufacturerAlias = "/api.bom.v1.BomService/CreateManufacturerAlias"
const OperationBomServiceCreateSession = "/api.bom.v1.BomService/CreateSession"
const OperationBomServiceCreateSessionLine = "/api.bom.v1.BomService/CreateSessionLine"
const OperationBomServiceDeleteSessionLine = "/api.bom.v1.BomService/DeleteSessionLine"
const OperationBomServiceDownloadTemplate = "/api.bom.v1.BomService/DownloadTemplate"
const OperationBomServiceExportSession = "/api.bom.v1.BomService/ExportSession"
const OperationBomServiceGetBOM = "/api.bom.v1.BomService/GetBOM"
const OperationBomServiceGetBOMLines = "/api.bom.v1.BomService/GetBOMLines"
const OperationBomServiceGetMatchResult = "/api.bom.v1.BomService/GetMatchResult"
const OperationBomServiceGetMatchRun = "/api.bom.v1.BomService/GetMatchRun"
const OperationBomServiceGetMatchSourceDetail = "/api.bom.v1.BomService/GetMatchSourceDetail"
const OperationBomServiceGetReadiness = "/api.bom.v1.BomService/GetReadiness"
const OperationBomServiceGetSession = "/api.bom.v1.BomService/GetSession"
const OperationBomServiceGetSessionSearchTaskCoverage = "/api.bom.v1.BomService/GetSessionSearchTaskCoverage"
const OperationBomServiceListLineGaps = "/api.bom.v1.BomService/ListLineGaps"
const OperationBomServiceListManufacturerCanonicals = "/api.bom.v1.BomService/ListManufacturerCanonicals"
const OperationBomServiceListMatchRuns = "/api.bom.v1.BomService/ListMatchRuns"
const OperationBomServiceListMatchSources = "/api.bom.v1.BomService/ListMatchSources"
const OperationBomServiceListSessionSearchTasks = "/api.bom.v1.BomService/ListSessionSearchTasks"
const OperationBomServiceListSessions = "/api.bom.v1.BomService/ListSessions"
const OperationBomServicePatchSession = "/api.bom.v1.BomService/PatchSession"
const OperationBomServicePatchSessionLine = "/api.bom.v1.BomService/PatchSessionLine"
const OperationBomServicePutPlatforms = "/api.bom.v1.BomService/PutPlatforms"
const OperationBomServiceResolveLineGapManualQuote = "/api.bom.v1.BomService/ResolveLineGapManualQuote"
const OperationBomServiceRetrySearchTasks = "/api.bom.v1.BomService/RetrySearchTasks"
const OperationBomServiceSaveMatchRun = "/api.bom.v1.BomService/SaveMatchRun"
const OperationBomServiceSearchQuotes = "/api.bom.v1.BomService/SearchQuotes"
const OperationBomServiceSelectLineGapSubstitute = "/api.bom.v1.BomService/SelectLineGapSubstitute"
const OperationBomServiceSubmitBomSearchResult = "/api.bom.v1.BomService/SubmitBomSearchResult"
const OperationBomServiceUploadBOM = "/api.bom.v1.BomService/UploadBOM"

type BomServiceHTTPServer interface {
	// AutoMatch 自动配单
	AutoMatch(context.Context, *AutoMatchRequest) (*AutoMatchReply, error)
	CreateManufacturerAlias(context.Context, *CreateManufacturerAliasRequest) (*CreateManufacturerAliasReply, error)
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionReply, error)
	// CreateSessionLine 追加一行
	CreateSessionLine(context.Context, *CreateSessionLineRequest) (*CreateSessionLineReply, error)
	// DeleteSessionLine 删除一行
	DeleteSessionLine(context.Context, *DeleteSessionLineRequest) (*DeleteSessionLineReply, error)
	// DownloadTemplate 下载 BOM 模板
	DownloadTemplate(context.Context, *DownloadTemplateRequest) (*DownloadTemplateReply, error)
	ExportSession(context.Context, *ExportSessionRequest) (*ExportSessionReply, error)
	// GetBOM 获取 BOM 详情（含解析结果）
	GetBOM(context.Context, *GetBOMRequest) (*GetBOMReply, error)
	GetBOMLines(context.Context, *GetBOMLinesRequest) (*GetBOMLinesReply, error)
	// GetMatchResult 获取配单结果
	GetMatchResult(context.Context, *GetMatchResultRequest) (*GetMatchResultReply, error)
	GetMatchRun(context.Context, *GetMatchRunRequest) (*GetMatchRunReply, error)
	// GetMatchSourceDetail 单行单平台：原始 quotes_json / no_mpn_detail（与 web/src/api/bomMatchExtras.ts 对齐）
	GetMatchSourceDetail(context.Context, *GetMatchSourceDetailRequest) (*GetMatchSourceDetailReply, error)
	GetReadiness(context.Context, *GetReadinessRequest) (*GetReadinessReply, error)
	GetSession(context.Context, *GetSessionRequest) (*GetSessionReply, error)
	// GetSessionSearchTaskCoverage 只读：检查当前行×勾选平台 与 bom_search_task 是否对齐（不写入）
	GetSessionSearchTaskCoverage(context.Context, *GetSessionSearchTaskCoverageRequest) (*GetSessionSearchTaskCoverageReply, error)
	// ListLineGaps 导出会话 BOM 行（Excel/CSV），见 docs/BOM货源搜索-接口清单.md §7
	ListLineGaps(context.Context, *ListLineGapsRequest) (*ListLineGapsReply, error)
	// ListManufacturerCanonicals 厂牌别名：规范 ID 下拉数据 + 写入 t_bom_manufacturer_alias（配单页「厂牌别名审核」）
	ListManufacturerCanonicals(context.Context, *ListManufacturerCanonicalsRequest) (*ListManufacturerCanonicalsReply, error)
	ListMatchRuns(context.Context, *ListMatchRunsRequest) (*ListMatchRunsReply, error)
	// ListMatchSources 配单诊断：各行 × 会话勾选平台的报价缓存命中与跳过原因（不要求 BOM_NOT_READY）
	ListMatchSources(context.Context, *ListMatchSourcesRequest) (*ListMatchSourcesReply, error)
	ListSessionSearchTasks(context.Context, *ListSessionSearchTasksRequest) (*ListSessionSearchTasksReply, error)
	// ListSessions 会话列表（分页、筛选）
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsReply, error)
	// PatchSession 更新会话头信息（标题、客户联系方式等）
	PatchSession(context.Context, *PatchSessionRequest) (*GetSessionReply, error)
	// PatchSessionLine 更新一行
	PatchSessionLine(context.Context, *PatchSessionLineRequest) (*PatchSessionLineReply, error)
	PutPlatforms(context.Context, *PutPlatformsRequest) (*PutPlatformsReply, error)
	ResolveLineGapManualQuote(context.Context, *ResolveLineGapManualQuoteRequest) (*ResolveLineGapManualQuoteReply, error)
	RetrySearchTasks(context.Context, *RetrySearchTasksRequest) (*RetrySearchTasksReply, error)
	SaveMatchRun(context.Context, *SaveMatchRunRequest) (*SaveMatchRunReply, error)
	// SearchQuotes 多平台搜索报价
	SearchQuotes(context.Context, *SearchQuotesRequest) (*SearchQuotesReply, error)
	SelectLineGapSubstitute(context.Context, *SelectLineGapSubstituteRequest) (*SelectLineGapSubstituteReply, error)
	// SubmitBomSearchResult Agent 回写单行搜索任务结果（写 bom_search_task + bom_quote_cache）
	SubmitBomSearchResult(context.Context, *SubmitBomSearchResultRequest) (*SubmitBomSearchResultReply, error)
	// UploadBOM 上传并解析 BOM
	UploadBOM(context.Context, *UploadBOMRequest) (*UploadBOMReply, error)
}

func RegisterBomServiceHTTPServer(s *http.Server, srv BomServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/bom/upload", _BomService_UploadBOM0_HTTP_Handler(srv))
	r.POST("/api/v1/bom/search", _BomService_SearchQuotes0_HTTP_Handler(srv))
	r.POST("/api/v1/bom/match", _BomService_AutoMatch0_HTTP_Handler(srv))
	r.GET("/api/v1/bom/template", _BomService_DownloadTemplate0_HTTP_Handler(srv))
	r.GET("/api/v1/bom/{bom_id}", _BomService_GetBOM0_HTTP_Handler(srv))
	r.GET("/api/v1/bom/{bom_id}/match", _BomService_GetMatchResult0_HTTP_Handler(srv))
	r.GET("/api/v1/bom/{bom_id}/match-sources", _BomService_ListMatchSources0_HTTP_Handler(srv))
	r.GET("/api/v1/bom/{bom_id}/match-sources/{line_no}/{platform}", _BomService_GetMatchSourceDetail0_HTTP_Handler(srv))
	r.GET("/api/v1/bom/manufacturer-canonicals", _BomService_ListManufacturerCanonicals0_HTTP_Handler(srv))
	r.POST("/api/v1/bom/manufacturer-aliases", _BomService_CreateManufacturerAlias0_HTTP_Handler(srv))
	r.POST("/api/v1/bom-sessions", _BomService_CreateSession0_HTTP_Handler(srv))
	r.GET("/api/v1/bom-sessions/{session_id}", _BomService_GetSession0_HTTP_Handler(srv))
	r.GET("/api/v1/bom-sessions", _BomService_ListSessions0_HTTP_Handler(srv))
	r.PATCH("/api/v1/bom-sessions/{session_id}", _BomService_PatchSession0_HTTP_Handler(srv))
	r.PUT("/api/v1/bom-sessions/{session_id}/platforms", _BomService_PutPlatforms0_HTTP_Handler(srv))
	r.GET("/api/v1/bom-sessions/{session_id}/readiness", _BomService_GetReadiness0_HTTP_Handler(srv))
	r.GET("/api/v1/bom-sessions/{session_id}/lines", _BomService_GetBOMLines0_HTTP_Handler(srv))
	r.GET("/api/v1/bom-sessions/{session_id}/search-tasks/coverage", _BomService_GetSessionSearchTaskCoverage0_HTTP_Handler(srv))
	r.GET("/api/v1/bom-sessions/{session_id}/search-tasks", _BomService_ListSessionSearchTasks0_HTTP_Handler(srv))
	r.POST("/api/v1/bom-sessions/{session_id}/lines", _BomService_CreateSessionLine0_HTTP_Handler(srv))
	r.PATCH("/api/v1/bom-sessions/{session_id}/lines/{line_id}", _BomService_PatchSessionLine0_HTTP_Handler(srv))
	r.DELETE("/api/v1/bom-sessions/{session_id}/lines/{line_id}", _BomService_DeleteSessionLine0_HTTP_Handler(srv))
	r.POST("/api/v1/bom-sessions/{session_id}/search-tasks/retry", _BomService_RetrySearchTasks0_HTTP_Handler(srv))
	r.POST("/api/v1/bom-sessions/{session_id}/search-results", _BomService_SubmitBomSearchResult0_HTTP_Handler(srv))
	r.GET("/api/bom/sessions/{session_id}/gaps", _BomService_ListLineGaps0_HTTP_Handler(srv))
	r.POST("/api/bom/gaps/{gap_id}/manual-quote", _BomService_ResolveLineGapManualQuote0_HTTP_Handler(srv))
	r.POST("/api/bom/gaps/{gap_id}/substitute", _BomService_SelectLineGapSubstitute0_HTTP_Handler(srv))
	r.POST("/api/bom/sessions/{session_id}/match-runs", _BomService_SaveMatchRun0_HTTP_Handler(srv))
	r.GET("/api/bom/sessions/{session_id}/match-runs", _BomService_ListMatchRuns0_HTTP_Handler(srv))
	r.GET("/api/bom/match-runs/{run_id}", _BomService_GetMatchRun0_HTTP_Handler(srv))
	r.GET("/api/v1/bom-sessions/{session_id}/export", _BomService_ExportSession0_HTTP_Handler(srv))
}

func _BomService_UploadBOM0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UploadBOMRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceUploadBOM)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UploadBOM(ctx, req.(*UploadBOMRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UploadBOMReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_SearchQuotes0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchQuotesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceSearchQuotes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SearchQuotes(ctx, req.(*SearchQuotesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SearchQuotesReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_AutoMatch0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AutoMatchRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceAutoMatch)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AutoMatch(ctx, req.(*AutoMatchRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AutoMatchReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_DownloadTemplate0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DownloadTemplateRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceDownloadTemplate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DownloadTemplate(ctx, req.(*DownloadTemplateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DownloadTemplateReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_GetBOM0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetBOMRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceGetBOM)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBOM(ctx, req.(*GetBOMRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetBOMReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_GetMatchResult0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMatchResultRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceGetMatchResult)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMatchResult(ctx, req.(*GetMatchResultRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMatchResultReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_ListMatchSources0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMatchSourcesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceListMatchSources)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMatchSources(ctx, req.(*ListMatchSourcesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMatchSourcesReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_GetMatchSourceDetail0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMatchSourceDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceGetMatchSourceDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMatchSourceDetail(ctx, req.(*GetMatchSourceDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMatchSourceDetailReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_ListManufacturerCanonicals0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListManufacturerCanonicalsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceListManufacturerCanonicals)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListManufacturerCanonicals(ctx, req.(*ListManufacturerCanonicalsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListManufacturerCanonicalsReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_CreateManufacturerAlias0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateManufacturerAliasRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceCreateManufacturerAlias)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateManufacturerAlias(ctx, req.(*CreateManufacturerAliasRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateManufacturerAliasReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_CreateSession0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSessionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceCreateSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSession(ctx, req.(*CreateSessionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateSessionReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_GetSession0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSessionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceGetSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSession(ctx, req.(*GetSessionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSessionReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_ListSessions0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSessionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceListSessions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSessions(ctx, req.(*ListSessionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSessionsReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_PatchSession0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PatchSessionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServicePatchSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PatchSession(ctx, req.(*PatchSessionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSessionReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_PutPlatforms0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PutPlatformsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServicePutPlatforms)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PutPlatforms(ctx, req.(*PutPlatformsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PutPlatformsReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_GetReadiness0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetReadinessRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceGetReadiness)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetReadiness(ctx, req.(*GetReadinessRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetReadinessReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_GetBOMLines0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetBOMLinesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceGetBOMLines)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBOMLines(ctx, req.(*GetBOMLinesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetBOMLinesReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_GetSessionSearchTaskCoverage0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSessionSearchTaskCoverageRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceGetSessionSearchTaskCoverage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSessionSearchTaskCoverage(ctx, req.(*GetSessionSearchTaskCoverageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSessionSearchTaskCoverageReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_ListSessionSearchTasks0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSessionSearchTasksRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceListSessionSearchTasks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSessionSearchTasks(ctx, req.(*ListSessionSearchTasksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSessionSearchTasksReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_CreateSessionLine0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSessionLineRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceCreateSessionLine)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSessionLine(ctx, req.(*CreateSessionLineRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateSessionLineReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_PatchSessionLine0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PatchSessionLineRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServicePatchSessionLine)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PatchSessionLine(ctx, req.(*PatchSessionLineRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PatchSessionLineReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_DeleteSessionLine0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteSessionLineRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceDeleteSessionLine)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteSessionLine(ctx, req.(*DeleteSessionLineRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteSessionLineReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_RetrySearchTasks0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RetrySearchTasksRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceRetrySearchTasks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RetrySearchTasks(ctx, req.(*RetrySearchTasksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RetrySearchTasksReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_SubmitBomSearchResult0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SubmitBomSearchResultRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceSubmitBomSearchResult)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitBomSearchResult(ctx, req.(*SubmitBomSearchResultRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SubmitBomSearchResultReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_ListLineGaps0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListLineGapsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceListLineGaps)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListLineGaps(ctx, req.(*ListLineGapsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListLineGapsReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_ResolveLineGapManualQuote0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ResolveLineGapManualQuoteRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceResolveLineGapManualQuote)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ResolveLineGapManualQuote(ctx, req.(*ResolveLineGapManualQuoteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ResolveLineGapManualQuoteReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_SelectLineGapSubstitute0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SelectLineGapSubstituteRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceSelectLineGapSubstitute)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SelectLineGapSubstitute(ctx, req.(*SelectLineGapSubstituteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SelectLineGapSubstituteReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_SaveMatchRun0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SaveMatchRunRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceSaveMatchRun)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaveMatchRun(ctx, req.(*SaveMatchRunRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SaveMatchRunReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_ListMatchRuns0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMatchRunsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceListMatchRuns)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMatchRuns(ctx, req.(*ListMatchRunsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMatchRunsReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_GetMatchRun0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMatchRunRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceGetMatchRun)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMatchRun(ctx, req.(*GetMatchRunRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMatchRunReply)
		return ctx.Result(200, reply)
	}
}

func _BomService_ExportSession0_HTTP_Handler(srv BomServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExportSessionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBomServiceExportSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExportSession(ctx, req.(*ExportSessionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExportSessionReply)
		return ctx.Result(200, reply)
	}
}

type BomServiceHTTPClient interface {
	// AutoMatch 自动配单
	AutoMatch(ctx context.Context, req *AutoMatchRequest, opts ...http.CallOption) (rsp *AutoMatchReply, err error)
	CreateManufacturerAlias(ctx context.Context, req *CreateManufacturerAliasRequest, opts ...http.CallOption) (rsp *CreateManufacturerAliasReply, err error)
	CreateSession(ctx context.Context, req *CreateSessionRequest, opts ...http.CallOption) (rsp *CreateSessionReply, err error)
	// CreateSessionLine 追加一行
	CreateSessionLine(ctx context.Context, req *CreateSessionLineRequest, opts ...http.CallOption) (rsp *CreateSessionLineReply, err error)
	// DeleteSessionLine 删除一行
	DeleteSessionLine(ctx context.Context, req *DeleteSessionLineRequest, opts ...http.CallOption) (rsp *DeleteSessionLineReply, err error)
	// DownloadTemplate 下载 BOM 模板
	DownloadTemplate(ctx context.Context, req *DownloadTemplateRequest, opts ...http.CallOption) (rsp *DownloadTemplateReply, err error)
	ExportSession(ctx context.Context, req *ExportSessionRequest, opts ...http.CallOption) (rsp *ExportSessionReply, err error)
	// GetBOM 获取 BOM 详情（含解析结果）
	GetBOM(ctx context.Context, req *GetBOMRequest, opts ...http.CallOption) (rsp *GetBOMReply, err error)
	GetBOMLines(ctx context.Context, req *GetBOMLinesRequest, opts ...http.CallOption) (rsp *GetBOMLinesReply, err error)
	// GetMatchResult 获取配单结果
	GetMatchResult(ctx context.Context, req *GetMatchResultRequest, opts ...http.CallOption) (rsp *GetMatchResultReply, err error)
	GetMatchRun(ctx context.Context, req *GetMatchRunRequest, opts ...http.CallOption) (rsp *GetMatchRunReply, err error)
	// GetMatchSourceDetail 单行单平台：原始 quotes_json / no_mpn_detail（与 web/src/api/bomMatchExtras.ts 对齐）
	GetMatchSourceDetail(ctx context.Context, req *GetMatchSourceDetailRequest, opts ...http.CallOption) (rsp *GetMatchSourceDetailReply, err error)
	GetReadiness(ctx context.Context, req *GetReadinessRequest, opts ...http.CallOption) (rsp *GetReadinessReply, err error)
	GetSession(ctx context.Context, req *GetSessionRequest, opts ...http.CallOption) (rsp *GetSessionReply, err error)
	// GetSessionSearchTaskCoverage 只读：检查当前行×勾选平台 与 bom_search_task 是否对齐（不写入）
	GetSessionSearchTaskCoverage(ctx context.Context, req *GetSessionSearchTaskCoverageRequest, opts ...http.CallOption) (rsp *GetSessionSearchTaskCoverageReply, err error)
	// ListLineGaps 导出会话 BOM 行（Excel/CSV），见 docs/BOM货源搜索-接口清单.md §7
	ListLineGaps(ctx context.Context, req *ListLineGapsRequest, opts ...http.CallOption) (rsp *ListLineGapsReply, err error)
	// ListManufacturerCanonicals 厂牌别名：规范 ID 下拉数据 + 写入 t_bom_manufacturer_alias（配单页「厂牌别名审核」）
	ListManufacturerCanonicals(ctx context.Context, req *ListManufacturerCanonicalsRequest, opts ...http.CallOption) (rsp *ListManufacturerCanonicalsReply, err error)
	ListMatchRuns(ctx context.Context, req *ListMatchRunsRequest, opts ...http.CallOption) (rsp *ListMatchRunsReply, err error)
	// ListMatchSources 配单诊断：各行 × 会话勾选平台的报价缓存命中与跳过原因（不要求 BOM_NOT_READY）
	ListMatchSources(ctx context.Context, req *ListMatchSourcesRequest, opts ...http.CallOption) (rsp *ListMatchSourcesReply, err error)
	ListSessionSearchTasks(ctx context.Context, req *ListSessionSearchTasksRequest, opts ...http.CallOption) (rsp *ListSessionSearchTasksReply, err error)
	// ListSessions 会话列表（分页、筛选）
	ListSessions(ctx context.Context, req *ListSessionsRequest, opts ...http.CallOption) (rsp *ListSessionsReply, err error)
	// PatchSession 更新会话头信息（标题、客户联系方式等）
	PatchSession(ctx context.Context, req *PatchSessionRequest, opts ...http.CallOption) (rsp *GetSessionReply, err error)
	// PatchSessionLine 更新一行
	PatchSessionLine(ctx context.Context, req *PatchSessionLineRequest, opts ...http.CallOption) (rsp *PatchSessionLineReply, err error)
	PutPlatforms(ctx context.Context, req *PutPlatformsRequest, opts ...http.CallOption) (rsp *PutPlatformsReply, err error)
	ResolveLineGapManualQuote(ctx context.Context, req *ResolveLineGapManualQuoteRequest, opts ...http.CallOption) (rsp *ResolveLineGapManualQuoteReply, err error)
	RetrySearchTasks(ctx context.Context, req *RetrySearchTasksRequest, opts ...http.CallOption) (rsp *RetrySearchTasksReply, err error)
	SaveMatchRun(ctx context.Context, req *SaveMatchRunRequest, opts ...http.CallOption) (rsp *SaveMatchRunReply, err error)
	// SearchQuotes 多平台搜索报价
	SearchQuotes(ctx context.Context, req *SearchQuotesRequest, opts ...http.CallOption) (rsp *SearchQuotesReply, err error)
	SelectLineGapSubstitute(ctx context.Context, req *SelectLineGapSubstituteRequest, opts ...http.CallOption) (rsp *SelectLineGapSubstituteReply, err error)
	// SubmitBomSearchResult Agent 回写单行搜索任务结果（写 bom_search_task + bom_quote_cache）
	SubmitBomSearchResult(ctx context.Context, req *SubmitBomSearchResultRequest, opts ...http.CallOption) (rsp *SubmitBomSearchResultReply, err error)
	// UploadBOM 上传并解析 BOM
	UploadBOM(ctx context.Context, req *UploadBOMRequest, opts ...http.CallOption) (rsp *UploadBOMReply, err error)
}

type BomServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewBomServiceHTTPClient(client *http.Client) BomServiceHTTPClient {
	return &BomServiceHTTPClientImpl{client}
}

// AutoMatch 自动配单
func (c *BomServiceHTTPClientImpl) AutoMatch(ctx context.Context, in *AutoMatchRequest, opts ...http.CallOption) (*AutoMatchReply, error) {
	var out AutoMatchReply
	pattern := "/api/v1/bom/match"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBomServiceAutoMatch))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *BomServiceHTTPClientImpl) CreateManufacturerAlias(ctx context.Context, in *CreateManufacturerAliasRequest, opts ...http.CallOption) (*CreateManufacturerAliasReply, error) {
	var out CreateManufacturerAliasReply
	pattern := "/api/v1/bom/manufacturer-aliases"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBomServiceCreateManufacturerAlias))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *BomServiceHTTPClientImpl) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...http.CallOption) (*CreateSessionReply, error) {
	var out CreateSessionReply
	pattern := "/api/v1/bom-sessions"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBomServiceCreateSession))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateSessionLine 追加一行
func (c *BomServiceHTTPClientImpl) CreateSessionLine(ctx context.Context, in *CreateSessionLineRequest, opts ...http.CallOption) (*CreateSessionLineReply, error) {
	var out CreateSessionLineReply
	pattern := "/api/v1/bom-sessions/{session_id}/lines"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBomServiceCreateSessionLine))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteSessionLine 删除一行
func (c *BomServiceHTTPClientImpl) DeleteSessionLine(ctx context.Context, in *DeleteSessionLineRequest, opts ...http.CallOption) (*DeleteSessionLineReply, error) {
	var out DeleteSessionLineReply
	pattern := "/api/v1/bom-sessions/{session_id}/lines/{line_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBomServiceDeleteSessionLine))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DownloadTemplate 下载 BOM 模板
func (c *BomServiceHTTPClientImpl) DownloadTemplate(ctx context.Context, in *DownloadTemplateRequest, opts ...http.CallOption) (*DownloadTemplateReply, error) {
	var out DownloadTemplateReply
	pattern := "/api/v1/bom/template"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBomServiceDownloadTemplate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *BomServiceHTTPClientImpl) ExportSession(ctx context.Context, in *ExportSessionRequest, opts ...http.CallOption) (*ExportSessionReply, error) {
	var out ExportSessionReply
	pattern := "/api/v1/bom-sessions/{session_id}/export"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBomServiceExportSession))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetBOM 获取 BOM 详情（含解析结果）
func (c *BomServiceHTTPClientImpl) GetBOM(ctx context.Context, in *GetBOMRequest, opts ...http.CallOption) (*GetBOMReply, error) {
	var out GetBOMReply
	pattern := "/api/v1/bom/{bom_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBomServiceGetBOM))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *BomServiceHTTPClientImpl) GetBOMLines(ctx context.Context, in *GetBOMLinesRequest, opts ...http.CallOption) (*GetBOMLinesReply, error) {
	var out GetBOMLinesReply
	pattern := "/api/v1/bom-sessions/{session_id}/lines"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBomServiceGetBOMLines))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMatchResult 获取配单结果
func (c *BomServiceHTTPClientImpl) GetMatchResult(ctx context.Context, in *GetMatchResultRequest, opts ...http.CallOption) (*GetMatchResultReply, error) {
	var out GetMatchResultReply
	pattern := "/api/v1/bom/{bom_id}/match"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBomServiceGetMatchResult))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *BomServiceHTTPClientImpl) GetMatchRun(ctx context.Context, in *GetMatchRunRequest, opts ...http.CallOption) (*GetMatchRunReply, error) {
	var out GetMatchRunReply
	pattern := "/api/bom/match-runs/{run_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBomServiceGetMatchRun))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMatchSourceDetail 单行单平台：原始 quotes_json / no_mpn_detail（与 web/src/api/bomMatchExtras.ts 对齐）
func (c *BomServiceHTTPClientImpl) GetMatchSourceDetail(ctx context.Context, in *GetMatchSourceDetailRequest, opts ...http.CallOption) (*GetMatchSourceDetailReply, error) {
	var out GetMatchSourceDetailReply
	pattern := "/api/v1/bom/{bom_id}/match-sources/{line_no}/{platform}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBomServiceGetMatchSourceDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *BomServiceHTTPClientImpl) GetReadiness(ctx context.Context, in *GetReadinessRequest, opts ...http.CallOption) (*GetReadinessReply, error) {
	var out GetReadinessReply
	pattern := "/api/v1/bom-sessions/{session_id}/readiness"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBomServiceGetReadiness))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *BomServiceHTTPClientImpl) GetSession(ctx context.Context, in *GetSessionRequest, opts ...http.CallOption) (*GetSessionReply, error) {
	var out GetSessionReply
	pattern := "/api/v1/bom-sessions/{session_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBomServiceGetSession))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSessionSearchTaskCoverage 只读：检查当前行×勾选平台 与 bom_search_task 是否对齐（不写入）
func (c *BomServiceHTTPClientImpl) GetSessionSearchTaskCoverage(ctx context.Context, in *GetSessionSearchTaskCoverageRequest, opts ...http.CallOption) (*GetSessionSearchTaskCoverageReply, error) {
	var out GetSessionSearchTaskCoverageReply
	pattern := "/api/v1/bom-sessions/{session_id}/search-tasks/coverage"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBomServiceGetSessionSearchTaskCoverage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListLineGaps 导出会话 BOM 行（Excel/CSV），见 docs/BOM货源搜索-接口清单.md §7
func (c *BomServiceHTTPClientImpl) ListLineGaps(ctx context.Context, in *ListLineGapsRequest, opts ...http.CallOption) (*ListLineGapsReply, error) {
	var out ListLineGapsReply
	pattern := "/api/bom/sessions/{session_id}/gaps"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBomServiceListLineGaps))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListManufacturerCanonicals 厂牌别名：规范 ID 下拉数据 + 写入 t_bom_manufacturer_alias（配单页「厂牌别名审核」）
func (c *BomServiceHTTPClientImpl) ListManufacturerCanonicals(ctx context.Context, in *ListManufacturerCanonicalsRequest, opts ...http.CallOption) (*ListManufacturerCanonicalsReply, error) {
	var out ListManufacturerCanonicalsReply
	pattern := "/api/v1/bom/manufacturer-canonicals"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBomServiceListManufacturerCanonicals))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *BomServiceHTTPClientImpl) ListMatchRuns(ctx context.Context, in *ListMatchRunsRequest, opts ...http.CallOption) (*ListMatchRunsReply, error) {
	var out ListMatchRunsReply
	pattern := "/api/bom/sessions/{session_id}/match-runs"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBomServiceListMatchRuns))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListMatchSources 配单诊断：各行 × 会话勾选平台的报价缓存命中与跳过原因（不要求 BOM_NOT_READY）
func (c *BomServiceHTTPClientImpl) ListMatchSources(ctx context.Context, in *ListMatchSourcesRequest, opts ...http.CallOption) (*ListMatchSourcesReply, error) {
	var out ListMatchSourcesReply
	pattern := "/api/v1/bom/{bom_id}/match-sources"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBomServiceListMatchSources))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *BomServiceHTTPClientImpl) ListSessionSearchTasks(ctx context.Context, in *ListSessionSearchTasksRequest, opts ...http.CallOption) (*ListSessionSearchTasksReply, error) {
	var out ListSessionSearchTasksReply
	pattern := "/api/v1/bom-sessions/{session_id}/search-tasks"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBomServiceListSessionSearchTasks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSessions 会话列表（分页、筛选）
func (c *BomServiceHTTPClientImpl) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...http.CallOption) (*ListSessionsReply, error) {
	var out ListSessionsReply
	pattern := "/api/v1/bom-sessions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBomServiceListSessions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PatchSession 更新会话头信息（标题、客户联系方式等）
func (c *BomServiceHTTPClientImpl) PatchSession(ctx context.Context, in *PatchSessionRequest, opts ...http.CallOption) (*GetSessionReply, error) {
	var out GetSessionReply
	pattern := "/api/v1/bom-sessions/{session_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBomServicePatchSession))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PatchSessionLine 更新一行
func (c *BomServiceHTTPClientImpl) PatchSessionLine(ctx context.Context, in *PatchSessionLineRequest, opts ...http.CallOption) (*PatchSessionLineReply, error) {
	var out PatchSessionLineReply
	pattern := "/api/v1/bom-sessions/{session_id}/lines/{line_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBomServicePatchSessionLine))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *BomServiceHTTPClientImpl) PutPlatforms(ctx context.Context, in *PutPlatformsRequest, opts ...http.CallOption) (*PutPlatformsReply, error) {
	var out PutPlatformsReply
	pattern := "/api/v1/bom-sessions/{session_id}/platforms"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBomServicePutPlatforms))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *BomServiceHTTPClientImpl) ResolveLineGapManualQuote(ctx context.Context, in *ResolveLineGapManualQuoteRequest, opts ...http.CallOption) (*ResolveLineGapManualQuoteReply, error) {
	var out ResolveLineGapManualQuoteReply
	pattern := "/api/bom/gaps/{gap_id}/manual-quote"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBomServiceResolveLineGapManualQuote))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *BomServiceHTTPClientImpl) RetrySearchTasks(ctx context.Context, in *RetrySearchTasksRequest, opts ...http.CallOption) (*RetrySearchTasksReply, error) {
	var out RetrySearchTasksReply
	pattern := "/api/v1/bom-sessions/{session_id}/search-tasks/retry"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBomServiceRetrySearchTasks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *BomServiceHTTPClientImpl) SaveMatchRun(ctx context.Context, in *SaveMatchRunRequest, opts ...http.CallOption) (*SaveMatchRunReply, error) {
	var out SaveMatchRunReply
	pattern := "/api/bom/sessions/{session_id}/match-runs"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBomServiceSaveMatchRun))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SearchQuotes 多平台搜索报价
func (c *BomServiceHTTPClientImpl) SearchQuotes(ctx context.Context, in *SearchQuotesRequest, opts ...http.CallOption) (*SearchQuotesReply, error) {
	var out SearchQuotesReply
	pattern := "/api/v1/bom/search"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBomServiceSearchQuotes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *BomServiceHTTPClientImpl) SelectLineGapSubstitute(ctx context.Context, in *SelectLineGapSubstituteRequest, opts ...http.CallOption) (*SelectLineGapSubstituteReply, error) {
	var out SelectLineGapSubstituteReply
	pattern := "/api/bom/gaps/{gap_id}/substitute"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBomServiceSelectLineGapSubstitute))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SubmitBomSearchResult Agent 回写单行搜索任务结果（写 bom_search_task + bom_quote_cache）
func (c *BomServiceHTTPClientImpl) SubmitBomSearchResult(ctx context.Context, in *SubmitBomSearchResultRequest, opts ...http.CallOption) (*SubmitBomSearchResultReply, error) {
	var out SubmitBomSearchResultReply
	pattern := "/api/v1/bom-sessions/{session_id}/search-results"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBomServiceSubmitBomSearchResult))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UploadBOM 上传并解析 BOM
func (c *BomServiceHTTPClientImpl) UploadBOM(ctx context.Context, in *UploadBOMRequest, opts ...http.CallOption) (*UploadBOMReply, error) {
	var out UploadBOMReply
	pattern := "/api/v1/bom/upload"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBomServiceUploadBOM))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationHsResolveServiceConfirmResolve = "/api.bom.v1.HsResolveService/ConfirmResolve"
const OperationHsResolveServiceGetResolveHistory = "/api.bom.v1.HsResolveService/GetResolveHistory"
const OperationHsResolveServiceGetResolveTask = "/api.bom.v1.HsResolveService/GetResolveTask"
const OperationHsResolveServiceResolveByModel = "/api.bom.v1.HsResolveService/ResolveByModel"

type HsResolveServiceHTTPServer interface {
	// ConfirmResolve 人工确认候选
	ConfirmResolve(context.Context, *HsResolveConfirmRequest) (*HsResolveConfirmReply, error)
	// GetResolveHistory 查询历史结果与候选
	GetResolveHistory(context.Context, *HsResolveHistoryRequest) (*HsResolveHistoryReply, error)
	// GetResolveTask 查询单个任务状态与结果
	GetResolveTask(context.Context, *HsResolveTaskRequest) (*HsResolveTaskReply, error)
	// ResolveByModel 按型号触发解析；在同步超时内完成则直接返回，否则返回 task_id 供轮询
	ResolveByModel(context.Context, *HsResolveByModelRequest) (*HsResolveByModelReply, error)
}

func RegisterHsResolveServiceHTTPServer(s *http.Server, srv HsResolveServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/hs/resolve/by-model", _HsResolveService_ResolveByModel0_HTTP_Handler(srv))
	r.GET("/api/hs/resolve/task", _HsResolveService_GetResolveTask0_HTTP_Handler(srv))
	r.POST("/api/hs/resolve/confirm", _HsResolveService_ConfirmResolve0_HTTP_Handler(srv))
	r.GET("/api/hs/resolve/history", _HsResolveService_GetResolveHistory0_HTTP_Handler(srv))
}

func _HsResolveService_ResolveByModel0_HTTP_Handler(srv HsResolveServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HsResolveByModelRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHsResolveServiceResolveByModel)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ResolveByModel(ctx, req.(*HsResolveByModelRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HsResolveByModelReply)
		return ctx.Result(200, reply)
	}
}

func _HsResolveService_GetResolveTask0_HTTP_Handler(srv HsResolveServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HsResolveTaskRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHsResolveServiceGetResolveTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetResolveTask(ctx, req.(*HsResolveTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HsResolveTaskReply)
		return ctx.Result(200, reply)
	}
}

func _HsResolveService_ConfirmResolve0_HTTP_Handler(srv HsResolveServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HsResolveConfirmRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHsResolveServiceConfirmResolve)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ConfirmResolve(ctx, req.(*HsResolveConfirmRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HsResolveConfirmReply)
		return ctx.Result(200, reply)
	}
}

func _HsResolveService_GetResolveHistory0_HTTP_Handler(srv HsResolveServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HsResolveHistoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHsResolveServiceGetResolveHistory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetResolveHistory(ctx, req.(*HsResolveHistoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HsResolveHistoryReply)
		return ctx.Result(200, reply)
	}
}

type HsResolveServiceHTTPClient interface {
	// ConfirmResolve 人工确认候选
	ConfirmResolve(ctx context.Context, req *HsResolveConfirmRequest, opts ...http.CallOption) (rsp *HsResolveConfirmReply, err error)
	// GetResolveHistory 查询历史结果与候选
	GetResolveHistory(ctx context.Context, req *HsResolveHistoryRequest, opts ...http.CallOption) (rsp *HsResolveHistoryReply, err error)
	// GetResolveTask 查询单个任务状态与结果
	GetResolveTask(ctx context.Context, req *HsResolveTaskRequest, opts ...http.CallOption) (rsp *HsResolveTaskReply, err error)
	// ResolveByModel 按型号触发解析；在同步超时内完成则直接返回，否则返回 task_id 供轮询
	ResolveByModel(ctx context.Context, req *HsResolveByModelRequest, opts ...http.CallOption) (rsp *HsResolveByModelReply, err error)
}

type HsResolveServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewHsResolveServiceHTTPClient(client *http.Client) HsResolveServiceHTTPClient {
	return &HsResolveServiceHTTPClientImpl{client}
}

// ConfirmResolve 人工确认候选
func (c *HsResolveServiceHTTPClientImpl) ConfirmResolve(ctx context.Context, in *HsResolveConfirmRequest, opts ...http.CallOption) (*HsResolveConfirmReply, error) {
	var out HsResolveConfirmReply
	pattern := "/api/hs/resolve/confirm"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHsResolveServiceConfirmResolve))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetResolveHistory 查询历史结果与候选
func (c *HsResolveServiceHTTPClientImpl) GetResolveHistory(ctx context.Context, in *HsResolveHistoryRequest, opts ...http.CallOption) (*HsResolveHistoryReply, error) {
	var out HsResolveHistoryReply
	pattern := "/api/hs/resolve/history"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHsResolveServiceGetResolveHistory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetResolveTask 查询单个任务状态与结果
func (c *HsResolveServiceHTTPClientImpl) GetResolveTask(ctx context.Context, in *HsResolveTaskRequest, opts ...http.CallOption) (*HsResolveTaskReply, error) {
	var out HsResolveTaskReply
	pattern := "/api/hs/resolve/task"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHsResolveServiceGetResolveTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ResolveByModel 按型号触发解析；在同步超时内完成则直接返回，否则返回 task_id 供轮询
func (c *HsResolveServiceHTTPClientImpl) ResolveByModel(ctx context.Context, in *HsResolveByModelRequest, opts ...http.CallOption) (*HsResolveByModelReply, error) {
	var out HsResolveByModelReply
	pattern := "/api/hs/resolve/by-model"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHsResolveServiceResolveByModel))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationHsMetaServiceCreateHsMeta = "/api.bom.v1.HsMetaService/CreateHsMeta"
const OperationHsMetaServiceDeleteHsMeta = "/api.bom.v1.HsMetaService/DeleteHsMeta"
const OperationHsMetaServiceListHsMeta = "/api.bom.v1.HsMetaService/ListHsMeta"
const OperationHsMetaServiceUpdateHsMeta = "/api.bom.v1.HsMetaService/UpdateHsMeta"

type HsMetaServiceHTTPServer interface {
	CreateHsMeta(context.Context, *HsMetaCreateRequest) (*HsMetaMutationReply, error)
	DeleteHsMeta(context.Context, *HsMetaDeleteRequest) (*HsMetaMutationReply, error)
	ListHsMeta(context.Context, *HsMetaListRequest) (*HsMetaListReply, error)
	UpdateHsMeta(context.Context, *HsMetaUpdateRequest) (*HsMetaMutationReply, error)
}

func RegisterHsMetaServiceHTTPServer(s *http.Server, srv HsMetaServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/hs/meta/list", _HsMetaService_ListHsMeta0_HTTP_Handler(srv))
	r.POST("/api/hs/meta/create", _HsMetaService_CreateHsMeta0_HTTP_Handler(srv))
	r.POST("/api/hs/meta/update", _HsMetaService_UpdateHsMeta0_HTTP_Handler(srv))
	r.POST("/api/hs/meta/delete", _HsMetaService_DeleteHsMeta0_HTTP_Handler(srv))
}

func _HsMetaService_ListHsMeta0_HTTP_Handler(srv HsMetaServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HsMetaListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHsMetaServiceListHsMeta)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListHsMeta(ctx, req.(*HsMetaListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HsMetaListReply)
		return ctx.Result(200, reply)
	}
}

func _HsMetaService_CreateHsMeta0_HTTP_Handler(srv HsMetaServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HsMetaCreateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHsMetaServiceCreateHsMeta)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateHsMeta(ctx, req.(*HsMetaCreateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HsMetaMutationReply)
		return ctx.Result(200, reply)
	}
}

func _HsMetaService_UpdateHsMeta0_HTTP_Handler(srv HsMetaServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HsMetaUpdateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHsMetaServiceUpdateHsMeta)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateHsMeta(ctx, req.(*HsMetaUpdateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HsMetaMutationReply)
		return ctx.Result(200, reply)
	}
}

func _HsMetaService_DeleteHsMeta0_HTTP_Handler(srv HsMetaServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HsMetaDeleteRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHsMetaServiceDeleteHsMeta)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteHsMeta(ctx, req.(*HsMetaDeleteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HsMetaMutationReply)
		return ctx.Result(200, reply)
	}
}

type HsMetaServiceHTTPClient interface {
	CreateHsMeta(ctx context.Context, req *HsMetaCreateRequest, opts ...http.CallOption) (rsp *HsMetaMutationReply, err error)
	DeleteHsMeta(ctx context.Context, req *HsMetaDeleteRequest, opts ...http.CallOption) (rsp *HsMetaMutationReply, err error)
	ListHsMeta(ctx context.Context, req *HsMetaListRequest, opts ...http.CallOption) (rsp *HsMetaListReply, err error)
	UpdateHsMeta(ctx context.Context, req *HsMetaUpdateRequest, opts ...http.CallOption) (rsp *HsMetaMutationReply, err error)
}

type HsMetaServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewHsMetaServiceHTTPClient(client *http.Client) HsMetaServiceHTTPClient {
	return &HsMetaServiceHTTPClientImpl{client}
}

func (c *HsMetaServiceHTTPClientImpl) CreateHsMeta(ctx context.Context, in *HsMetaCreateRequest, opts ...http.CallOption) (*HsMetaMutationReply, error) {
	var out HsMetaMutationReply
	pattern := "/api/hs/meta/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHsMetaServiceCreateHsMeta))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HsMetaServiceHTTPClientImpl) DeleteHsMeta(ctx context.Context, in *HsMetaDeleteRequest, opts ...http.CallOption) (*HsMetaMutationReply, error) {
	var out HsMetaMutationReply
	pattern := "/api/hs/meta/delete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHsMetaServiceDeleteHsMeta))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HsMetaServiceHTTPClientImpl) ListHsMeta(ctx context.Context, in *HsMetaListRequest, opts ...http.CallOption) (*HsMetaListReply, error) {
	var out HsMetaListReply
	pattern := "/api/hs/meta/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHsMetaServiceListHsMeta))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HsMetaServiceHTTPClientImpl) UpdateHsMeta(ctx context.Context, in *HsMetaUpdateRequest, opts ...http.CallOption) (*HsMetaMutationReply, error) {
	var out HsMetaMutationReply
	pattern := "/api/hs/meta/update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHsMetaServiceUpdateHsMeta))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
