// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: admin/v1/agent_admin.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentAdminService_ListAgents_FullMethodName                = "/api.admin.v1.AgentAdminService/ListAgents"
	AgentAdminService_ListAgentLeasedTasks_FullMethodName      = "/api.admin.v1.AgentAdminService/ListAgentLeasedTasks"
	AgentAdminService_ListAgentInstalledScripts_FullMethodName = "/api.admin.v1.AgentAdminService/ListAgentInstalledScripts"
	AgentAdminService_ListAgentScriptAuths_FullMethodName      = "/api.admin.v1.AgentAdminService/ListAgentScriptAuths"
	AgentAdminService_UpsertAgentScriptAuth_FullMethodName     = "/api.admin.v1.AgentAdminService/UpsertAgentScriptAuth"
	AgentAdminService_DeleteAgentScriptAuth_FullMethodName     = "/api.admin.v1.AgentAdminService/DeleteAgentScriptAuth"
	AgentAdminService_ListBomPlatforms_FullMethodName          = "/api.admin.v1.AgentAdminService/ListBomPlatforms"
	AgentAdminService_GetBomPlatform_FullMethodName            = "/api.admin.v1.AgentAdminService/GetBomPlatform"
	AgentAdminService_UpsertBomPlatform_FullMethodName         = "/api.admin.v1.AgentAdminService/UpsertBomPlatform"
	AgentAdminService_DeleteBomPlatform_FullMethodName         = "/api.admin.v1.AgentAdminService/DeleteBomPlatform"
)

// AgentAdminServiceClient is the client API for AgentAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentAdminService 运维查询：Agent 在线状态、租约中任务、已安装脚本（鉴权见 bootstrap.agent_admin.api_keys，与 Agent 采集 API 分离）。
type AgentAdminServiceClient interface {
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsReply, error)
	ListAgentLeasedTasks(ctx context.Context, in *ListAgentLeasedTasksRequest, opts ...grpc.CallOption) (*ListAgentLeasedTasksReply, error)
	ListAgentInstalledScripts(ctx context.Context, in *ListAgentInstalledScriptsRequest, opts ...grpc.CallOption) (*ListAgentInstalledScriptsReply, error)
	// Agent × script_id 登录凭据（密码不落库明文；下发见 TaskObject.params.platform_auth）
	ListAgentScriptAuths(ctx context.Context, in *ListAgentScriptAuthsRequest, opts ...grpc.CallOption) (*ListAgentScriptAuthsReply, error)
	UpsertAgentScriptAuth(ctx context.Context, in *UpsertAgentScriptAuthRequest, opts ...grpc.CallOption) (*UpsertAgentScriptAuthReply, error)
	DeleteAgentScriptAuth(ctx context.Context, in *DeleteAgentScriptAuthRequest, opts ...grpc.CallOption) (*DeleteAgentScriptAuthReply, error)
	// BOM 采集平台（platform_id 与 script_id 一一对应；run_params 为键值对象，服务端展开为 TaskObject.argv 前缀）
	ListBomPlatforms(ctx context.Context, in *ListBomPlatformsRequest, opts ...grpc.CallOption) (*ListBomPlatformsReply, error)
	GetBomPlatform(ctx context.Context, in *GetBomPlatformRequest, opts ...grpc.CallOption) (*GetBomPlatformReply, error)
	UpsertBomPlatform(ctx context.Context, in *UpsertBomPlatformRequest, opts ...grpc.CallOption) (*UpsertBomPlatformReply, error)
	DeleteBomPlatform(ctx context.Context, in *DeleteBomPlatformRequest, opts ...grpc.CallOption) (*DeleteBomPlatformReply, error)
}

type agentAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentAdminServiceClient(cc grpc.ClientConnInterface) AgentAdminServiceClient {
	return &agentAdminServiceClient{cc}
}

func (c *agentAdminServiceClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsReply)
	err := c.cc.Invoke(ctx, AgentAdminService_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAdminServiceClient) ListAgentLeasedTasks(ctx context.Context, in *ListAgentLeasedTasksRequest, opts ...grpc.CallOption) (*ListAgentLeasedTasksReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentLeasedTasksReply)
	err := c.cc.Invoke(ctx, AgentAdminService_ListAgentLeasedTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAdminServiceClient) ListAgentInstalledScripts(ctx context.Context, in *ListAgentInstalledScriptsRequest, opts ...grpc.CallOption) (*ListAgentInstalledScriptsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentInstalledScriptsReply)
	err := c.cc.Invoke(ctx, AgentAdminService_ListAgentInstalledScripts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAdminServiceClient) ListAgentScriptAuths(ctx context.Context, in *ListAgentScriptAuthsRequest, opts ...grpc.CallOption) (*ListAgentScriptAuthsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentScriptAuthsReply)
	err := c.cc.Invoke(ctx, AgentAdminService_ListAgentScriptAuths_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAdminServiceClient) UpsertAgentScriptAuth(ctx context.Context, in *UpsertAgentScriptAuthRequest, opts ...grpc.CallOption) (*UpsertAgentScriptAuthReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertAgentScriptAuthReply)
	err := c.cc.Invoke(ctx, AgentAdminService_UpsertAgentScriptAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAdminServiceClient) DeleteAgentScriptAuth(ctx context.Context, in *DeleteAgentScriptAuthRequest, opts ...grpc.CallOption) (*DeleteAgentScriptAuthReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAgentScriptAuthReply)
	err := c.cc.Invoke(ctx, AgentAdminService_DeleteAgentScriptAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAdminServiceClient) ListBomPlatforms(ctx context.Context, in *ListBomPlatformsRequest, opts ...grpc.CallOption) (*ListBomPlatformsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBomPlatformsReply)
	err := c.cc.Invoke(ctx, AgentAdminService_ListBomPlatforms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAdminServiceClient) GetBomPlatform(ctx context.Context, in *GetBomPlatformRequest, opts ...grpc.CallOption) (*GetBomPlatformReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBomPlatformReply)
	err := c.cc.Invoke(ctx, AgentAdminService_GetBomPlatform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAdminServiceClient) UpsertBomPlatform(ctx context.Context, in *UpsertBomPlatformRequest, opts ...grpc.CallOption) (*UpsertBomPlatformReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertBomPlatformReply)
	err := c.cc.Invoke(ctx, AgentAdminService_UpsertBomPlatform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAdminServiceClient) DeleteBomPlatform(ctx context.Context, in *DeleteBomPlatformRequest, opts ...grpc.CallOption) (*DeleteBomPlatformReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBomPlatformReply)
	err := c.cc.Invoke(ctx, AgentAdminService_DeleteBomPlatform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentAdminServiceServer is the server API for AgentAdminService service.
// All implementations must embed UnimplementedAgentAdminServiceServer
// for forward compatibility.
//
// AgentAdminService 运维查询：Agent 在线状态、租约中任务、已安装脚本（鉴权见 bootstrap.agent_admin.api_keys，与 Agent 采集 API 分离）。
type AgentAdminServiceServer interface {
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsReply, error)
	ListAgentLeasedTasks(context.Context, *ListAgentLeasedTasksRequest) (*ListAgentLeasedTasksReply, error)
	ListAgentInstalledScripts(context.Context, *ListAgentInstalledScriptsRequest) (*ListAgentInstalledScriptsReply, error)
	// Agent × script_id 登录凭据（密码不落库明文；下发见 TaskObject.params.platform_auth）
	ListAgentScriptAuths(context.Context, *ListAgentScriptAuthsRequest) (*ListAgentScriptAuthsReply, error)
	UpsertAgentScriptAuth(context.Context, *UpsertAgentScriptAuthRequest) (*UpsertAgentScriptAuthReply, error)
	DeleteAgentScriptAuth(context.Context, *DeleteAgentScriptAuthRequest) (*DeleteAgentScriptAuthReply, error)
	// BOM 采集平台（platform_id 与 script_id 一一对应；run_params 为键值对象，服务端展开为 TaskObject.argv 前缀）
	ListBomPlatforms(context.Context, *ListBomPlatformsRequest) (*ListBomPlatformsReply, error)
	GetBomPlatform(context.Context, *GetBomPlatformRequest) (*GetBomPlatformReply, error)
	UpsertBomPlatform(context.Context, *UpsertBomPlatformRequest) (*UpsertBomPlatformReply, error)
	DeleteBomPlatform(context.Context, *DeleteBomPlatformRequest) (*DeleteBomPlatformReply, error)
	mustEmbedUnimplementedAgentAdminServiceServer()
}

// UnimplementedAgentAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentAdminServiceServer struct{}

func (UnimplementedAgentAdminServiceServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedAgentAdminServiceServer) ListAgentLeasedTasks(context.Context, *ListAgentLeasedTasksRequest) (*ListAgentLeasedTasksReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgentLeasedTasks not implemented")
}
func (UnimplementedAgentAdminServiceServer) ListAgentInstalledScripts(context.Context, *ListAgentInstalledScriptsRequest) (*ListAgentInstalledScriptsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgentInstalledScripts not implemented")
}
func (UnimplementedAgentAdminServiceServer) ListAgentScriptAuths(context.Context, *ListAgentScriptAuthsRequest) (*ListAgentScriptAuthsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgentScriptAuths not implemented")
}
func (UnimplementedAgentAdminServiceServer) UpsertAgentScriptAuth(context.Context, *UpsertAgentScriptAuthRequest) (*UpsertAgentScriptAuthReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertAgentScriptAuth not implemented")
}
func (UnimplementedAgentAdminServiceServer) DeleteAgentScriptAuth(context.Context, *DeleteAgentScriptAuthRequest) (*DeleteAgentScriptAuthReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAgentScriptAuth not implemented")
}
func (UnimplementedAgentAdminServiceServer) ListBomPlatforms(context.Context, *ListBomPlatformsRequest) (*ListBomPlatformsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBomPlatforms not implemented")
}
func (UnimplementedAgentAdminServiceServer) GetBomPlatform(context.Context, *GetBomPlatformRequest) (*GetBomPlatformReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBomPlatform not implemented")
}
func (UnimplementedAgentAdminServiceServer) UpsertBomPlatform(context.Context, *UpsertBomPlatformRequest) (*UpsertBomPlatformReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertBomPlatform not implemented")
}
func (UnimplementedAgentAdminServiceServer) DeleteBomPlatform(context.Context, *DeleteBomPlatformRequest) (*DeleteBomPlatformReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBomPlatform not implemented")
}
func (UnimplementedAgentAdminServiceServer) mustEmbedUnimplementedAgentAdminServiceServer() {}
func (UnimplementedAgentAdminServiceServer) testEmbeddedByValue()                           {}

// UnsafeAgentAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentAdminServiceServer will
// result in compilation errors.
type UnsafeAgentAdminServiceServer interface {
	mustEmbedUnimplementedAgentAdminServiceServer()
}

func RegisterAgentAdminServiceServer(s grpc.ServiceRegistrar, srv AgentAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentAdminService_ServiceDesc, srv)
}

func _AgentAdminService_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAdminServiceServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAdminService_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAdminServiceServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAdminService_ListAgentLeasedTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentLeasedTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAdminServiceServer).ListAgentLeasedTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAdminService_ListAgentLeasedTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAdminServiceServer).ListAgentLeasedTasks(ctx, req.(*ListAgentLeasedTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAdminService_ListAgentInstalledScripts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentInstalledScriptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAdminServiceServer).ListAgentInstalledScripts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAdminService_ListAgentInstalledScripts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAdminServiceServer).ListAgentInstalledScripts(ctx, req.(*ListAgentInstalledScriptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAdminService_ListAgentScriptAuths_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentScriptAuthsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAdminServiceServer).ListAgentScriptAuths(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAdminService_ListAgentScriptAuths_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAdminServiceServer).ListAgentScriptAuths(ctx, req.(*ListAgentScriptAuthsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAdminService_UpsertAgentScriptAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertAgentScriptAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAdminServiceServer).UpsertAgentScriptAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAdminService_UpsertAgentScriptAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAdminServiceServer).UpsertAgentScriptAuth(ctx, req.(*UpsertAgentScriptAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAdminService_DeleteAgentScriptAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAgentScriptAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAdminServiceServer).DeleteAgentScriptAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAdminService_DeleteAgentScriptAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAdminServiceServer).DeleteAgentScriptAuth(ctx, req.(*DeleteAgentScriptAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAdminService_ListBomPlatforms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBomPlatformsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAdminServiceServer).ListBomPlatforms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAdminService_ListBomPlatforms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAdminServiceServer).ListBomPlatforms(ctx, req.(*ListBomPlatformsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAdminService_GetBomPlatform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBomPlatformRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAdminServiceServer).GetBomPlatform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAdminService_GetBomPlatform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAdminServiceServer).GetBomPlatform(ctx, req.(*GetBomPlatformRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAdminService_UpsertBomPlatform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertBomPlatformRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAdminServiceServer).UpsertBomPlatform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAdminService_UpsertBomPlatform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAdminServiceServer).UpsertBomPlatform(ctx, req.(*UpsertBomPlatformRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAdminService_DeleteBomPlatform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBomPlatformRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAdminServiceServer).DeleteBomPlatform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAdminService_DeleteBomPlatform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAdminServiceServer).DeleteBomPlatform(ctx, req.(*DeleteBomPlatformRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentAdminService_ServiceDesc is the grpc.ServiceDesc for AgentAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.admin.v1.AgentAdminService",
	HandlerType: (*AgentAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAgents",
			Handler:    _AgentAdminService_ListAgents_Handler,
		},
		{
			MethodName: "ListAgentLeasedTasks",
			Handler:    _AgentAdminService_ListAgentLeasedTasks_Handler,
		},
		{
			MethodName: "ListAgentInstalledScripts",
			Handler:    _AgentAdminService_ListAgentInstalledScripts_Handler,
		},
		{
			MethodName: "ListAgentScriptAuths",
			Handler:    _AgentAdminService_ListAgentScriptAuths_Handler,
		},
		{
			MethodName: "UpsertAgentScriptAuth",
			Handler:    _AgentAdminService_UpsertAgentScriptAuth_Handler,
		},
		{
			MethodName: "DeleteAgentScriptAuth",
			Handler:    _AgentAdminService_DeleteAgentScriptAuth_Handler,
		},
		{
			MethodName: "ListBomPlatforms",
			Handler:    _AgentAdminService_ListBomPlatforms_Handler,
		},
		{
			MethodName: "GetBomPlatform",
			Handler:    _AgentAdminService_GetBomPlatform_Handler,
		},
		{
			MethodName: "UpsertBomPlatform",
			Handler:    _AgentAdminService_UpsertBomPlatform_Handler,
		},
		{
			MethodName: "DeleteBomPlatform",
			Handler:    _AgentAdminService_DeleteBomPlatform_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/v1/agent_admin.proto",
}
