// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: admin/v1/agent_admin.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_admin_v1_agent_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_agent_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_agent_admin_proto_rawDescGZIP(), []int{0}
}

type AgentSummary struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AgentId             string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Queue               string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	Hostname            string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	LastTaskHeartbeatAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_task_heartbeat_at,json=lastTaskHeartbeatAt,proto3" json:"last_task_heartbeat_at,omitempty"`
	Online              bool                   `protobuf:"varint,5,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AgentSummary) Reset() {
	*x = AgentSummary{}
	mi := &file_admin_v1_agent_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSummary) ProtoMessage() {}

func (x *AgentSummary) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_agent_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSummary.ProtoReflect.Descriptor instead.
func (*AgentSummary) Descriptor() ([]byte, []int) {
	return file_admin_v1_agent_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AgentSummary) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentSummary) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *AgentSummary) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentSummary) GetLastTaskHeartbeatAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTaskHeartbeatAt
	}
	return nil
}

func (x *AgentSummary) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type ListAgentsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentSummary        `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsReply) Reset() {
	*x = ListAgentsReply{}
	mi := &file_admin_v1_agent_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsReply) ProtoMessage() {}

func (x *ListAgentsReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_agent_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsReply.ProtoReflect.Descriptor instead.
func (*ListAgentsReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_agent_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ListAgentsReply) GetAgents() []*AgentSummary {
	if x != nil {
		return x.Agents
	}
	return nil
}

type ListAgentLeasedTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentLeasedTasksRequest) Reset() {
	*x = ListAgentLeasedTasksRequest{}
	mi := &file_admin_v1_agent_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentLeasedTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentLeasedTasksRequest) ProtoMessage() {}

func (x *ListAgentLeasedTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_agent_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentLeasedTasksRequest.ProtoReflect.Descriptor instead.
func (*ListAgentLeasedTasksRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_agent_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ListAgentLeasedTasksRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type LeasedTaskRow struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ScriptId        string                 `protobuf:"bytes,2,opt,name=script_id,json=scriptId,proto3" json:"script_id,omitempty"`
	Version         string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	LeasedAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=leased_at,json=leasedAt,proto3" json:"leased_at,omitempty"`
	LeaseDeadlineAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=lease_deadline_at,json=leaseDeadlineAt,proto3" json:"lease_deadline_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LeasedTaskRow) Reset() {
	*x = LeasedTaskRow{}
	mi := &file_admin_v1_agent_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeasedTaskRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeasedTaskRow) ProtoMessage() {}

func (x *LeasedTaskRow) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_agent_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeasedTaskRow.ProtoReflect.Descriptor instead.
func (*LeasedTaskRow) Descriptor() ([]byte, []int) {
	return file_admin_v1_agent_admin_proto_rawDescGZIP(), []int{4}
}

func (x *LeasedTaskRow) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *LeasedTaskRow) GetScriptId() string {
	if x != nil {
		return x.ScriptId
	}
	return ""
}

func (x *LeasedTaskRow) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *LeasedTaskRow) GetLeasedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeasedAt
	}
	return nil
}

func (x *LeasedTaskRow) GetLeaseDeadlineAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseDeadlineAt
	}
	return nil
}

type ListAgentLeasedTasksReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*LeasedTaskRow       `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentLeasedTasksReply) Reset() {
	*x = ListAgentLeasedTasksReply{}
	mi := &file_admin_v1_agent_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentLeasedTasksReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentLeasedTasksReply) ProtoMessage() {}

func (x *ListAgentLeasedTasksReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_agent_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentLeasedTasksReply.ProtoReflect.Descriptor instead.
func (*ListAgentLeasedTasksReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_agent_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ListAgentLeasedTasksReply) GetTasks() []*LeasedTaskRow {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type ListAgentInstalledScriptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentInstalledScriptsRequest) Reset() {
	*x = ListAgentInstalledScriptsRequest{}
	mi := &file_admin_v1_agent_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentInstalledScriptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentInstalledScriptsRequest) ProtoMessage() {}

func (x *ListAgentInstalledScriptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_agent_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentInstalledScriptsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentInstalledScriptsRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_agent_admin_proto_rawDescGZIP(), []int{6}
}

func (x *ListAgentInstalledScriptsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type InstalledScriptRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScriptId      string                 `protobuf:"bytes,1,opt,name=script_id,json=scriptId,proto3" json:"script_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	EnvStatus     string                 `protobuf:"bytes,3,opt,name=env_status,json=envStatus,proto3" json:"env_status,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstalledScriptRow) Reset() {
	*x = InstalledScriptRow{}
	mi := &file_admin_v1_agent_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstalledScriptRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstalledScriptRow) ProtoMessage() {}

func (x *InstalledScriptRow) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_agent_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstalledScriptRow.ProtoReflect.Descriptor instead.
func (*InstalledScriptRow) Descriptor() ([]byte, []int) {
	return file_admin_v1_agent_admin_proto_rawDescGZIP(), []int{7}
}

func (x *InstalledScriptRow) GetScriptId() string {
	if x != nil {
		return x.ScriptId
	}
	return ""
}

func (x *InstalledScriptRow) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstalledScriptRow) GetEnvStatus() string {
	if x != nil {
		return x.EnvStatus
	}
	return ""
}

func (x *InstalledScriptRow) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListAgentInstalledScriptsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scripts       []*InstalledScriptRow  `protobuf:"bytes,1,rep,name=scripts,proto3" json:"scripts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentInstalledScriptsReply) Reset() {
	*x = ListAgentInstalledScriptsReply{}
	mi := &file_admin_v1_agent_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentInstalledScriptsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentInstalledScriptsReply) ProtoMessage() {}

func (x *ListAgentInstalledScriptsReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_agent_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentInstalledScriptsReply.ProtoReflect.Descriptor instead.
func (*ListAgentInstalledScriptsReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_agent_admin_proto_rawDescGZIP(), []int{8}
}

func (x *ListAgentInstalledScriptsReply) GetScripts() []*InstalledScriptRow {
	if x != nil {
		return x.Scripts
	}
	return nil
}

var File_admin_v1_agent_admin_proto protoreflect.FileDescriptor

const file_admin_v1_agent_admin_proto_rawDesc = "" +
	"\n" +
	"\x1aadmin/v1/agent_admin.proto\x12\fapi.admin.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x13\n" +
	"\x11ListAgentsRequest\"\xc4\x01\n" +
	"\fAgentSummary\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12O\n" +
	"\x16last_task_heartbeat_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x13lastTaskHeartbeatAt\x12\x16\n" +
	"\x06online\x18\x05 \x01(\bR\x06online\"E\n" +
	"\x0fListAgentsReply\x122\n" +
	"\x06agents\x18\x01 \x03(\v2\x1a.api.admin.v1.AgentSummaryR\x06agents\"8\n" +
	"\x1bListAgentLeasedTasksRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\xe0\x01\n" +
	"\rLeasedTaskRow\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tscript_id\x18\x02 \x01(\tR\bscriptId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x127\n" +
	"\tleased_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bleasedAt\x12F\n" +
	"\x11lease_deadline_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0fleaseDeadlineAt\"N\n" +
	"\x19ListAgentLeasedTasksReply\x121\n" +
	"\x05tasks\x18\x01 \x03(\v2\x1b.api.admin.v1.LeasedTaskRowR\x05tasks\"=\n" +
	" ListAgentInstalledScriptsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\xa5\x01\n" +
	"\x12InstalledScriptRow\x12\x1b\n" +
	"\tscript_id\x18\x01 \x01(\tR\bscriptId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"env_status\x18\x03 \x01(\tR\tenvStatus\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\\\n" +
	"\x1eListAgentInstalledScriptsReply\x12:\n" +
	"\ascripts\x18\x01 \x03(\v2 .api.admin.v1.InstalledScriptRowR\ascripts2\xd9\x03\n" +
	"\x11AgentAdminService\x12j\n" +
	"\n" +
	"ListAgents\x12\x1f.api.admin.v1.ListAgentsRequest\x1a\x1d.api.admin.v1.ListAgentsReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/admin/agents\x12\xa0\x01\n" +
	"\x14ListAgentLeasedTasks\x12).api.admin.v1.ListAgentLeasedTasksRequest\x1a'.api.admin.v1.ListAgentLeasedTasksReply\"4\x82\xd3\xe4\x93\x02.\x12,/api/v1/admin/agents/{agent_id}/leased-tasks\x12\xb4\x01\n" +
	"\x19ListAgentInstalledScripts\x12..api.admin.v1.ListAgentInstalledScriptsRequest\x1a,.api.admin.v1.ListAgentInstalledScriptsReply\"9\x82\xd3\xe4\x93\x023\x121/api/v1/admin/agents/{agent_id}/installed-scriptsB\x19Z\x17caichip/api/admin/v1;v1b\x06proto3"

var (
	file_admin_v1_agent_admin_proto_rawDescOnce sync.Once
	file_admin_v1_agent_admin_proto_rawDescData []byte
)

func file_admin_v1_agent_admin_proto_rawDescGZIP() []byte {
	file_admin_v1_agent_admin_proto_rawDescOnce.Do(func() {
		file_admin_v1_agent_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_agent_admin_proto_rawDesc), len(file_admin_v1_agent_admin_proto_rawDesc)))
	})
	return file_admin_v1_agent_admin_proto_rawDescData
}

var file_admin_v1_agent_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_admin_v1_agent_admin_proto_goTypes = []any{
	(*ListAgentsRequest)(nil),                // 0: api.admin.v1.ListAgentsRequest
	(*AgentSummary)(nil),                     // 1: api.admin.v1.AgentSummary
	(*ListAgentsReply)(nil),                  // 2: api.admin.v1.ListAgentsReply
	(*ListAgentLeasedTasksRequest)(nil),      // 3: api.admin.v1.ListAgentLeasedTasksRequest
	(*LeasedTaskRow)(nil),                    // 4: api.admin.v1.LeasedTaskRow
	(*ListAgentLeasedTasksReply)(nil),        // 5: api.admin.v1.ListAgentLeasedTasksReply
	(*ListAgentInstalledScriptsRequest)(nil), // 6: api.admin.v1.ListAgentInstalledScriptsRequest
	(*InstalledScriptRow)(nil),               // 7: api.admin.v1.InstalledScriptRow
	(*ListAgentInstalledScriptsReply)(nil),   // 8: api.admin.v1.ListAgentInstalledScriptsReply
	(*timestamppb.Timestamp)(nil),            // 9: google.protobuf.Timestamp
}
var file_admin_v1_agent_admin_proto_depIdxs = []int32{
	9,  // 0: api.admin.v1.AgentSummary.last_task_heartbeat_at:type_name -> google.protobuf.Timestamp
	1,  // 1: api.admin.v1.ListAgentsReply.agents:type_name -> api.admin.v1.AgentSummary
	9,  // 2: api.admin.v1.LeasedTaskRow.leased_at:type_name -> google.protobuf.Timestamp
	9,  // 3: api.admin.v1.LeasedTaskRow.lease_deadline_at:type_name -> google.protobuf.Timestamp
	4,  // 4: api.admin.v1.ListAgentLeasedTasksReply.tasks:type_name -> api.admin.v1.LeasedTaskRow
	9,  // 5: api.admin.v1.InstalledScriptRow.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 6: api.admin.v1.ListAgentInstalledScriptsReply.scripts:type_name -> api.admin.v1.InstalledScriptRow
	0,  // 7: api.admin.v1.AgentAdminService.ListAgents:input_type -> api.admin.v1.ListAgentsRequest
	3,  // 8: api.admin.v1.AgentAdminService.ListAgentLeasedTasks:input_type -> api.admin.v1.ListAgentLeasedTasksRequest
	6,  // 9: api.admin.v1.AgentAdminService.ListAgentInstalledScripts:input_type -> api.admin.v1.ListAgentInstalledScriptsRequest
	2,  // 10: api.admin.v1.AgentAdminService.ListAgents:output_type -> api.admin.v1.ListAgentsReply
	5,  // 11: api.admin.v1.AgentAdminService.ListAgentLeasedTasks:output_type -> api.admin.v1.ListAgentLeasedTasksReply
	8,  // 12: api.admin.v1.AgentAdminService.ListAgentInstalledScripts:output_type -> api.admin.v1.ListAgentInstalledScriptsReply
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_admin_v1_agent_admin_proto_init() }
func file_admin_v1_agent_admin_proto_init() {
	if File_admin_v1_agent_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_agent_admin_proto_rawDesc), len(file_admin_v1_agent_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_v1_agent_admin_proto_goTypes,
		DependencyIndexes: file_admin_v1_agent_admin_proto_depIdxs,
		MessageInfos:      file_admin_v1_agent_admin_proto_msgTypes,
	}.Build()
	File_admin_v1_agent_admin_proto = out.File
	file_admin_v1_agent_admin_proto_goTypes = nil
	file_admin_v1_agent_admin_proto_depIdxs = nil
}
