// Code generated by cmd/tools/gen_review_codes; DO NOT EDIT.
package hsclassifycodes

const DictionaryVersion = "2026-04-14-v1"

type ErrorCode string

const (
	ErrorCodeInvalidArgument         ErrorCode = "INVALID_ARGUMENT"
	ErrorCodeInternalError           ErrorCode = "INTERNAL_ERROR"
	ErrorCodePolicySourceUnavailable ErrorCode = "POLICY_SOURCE_UNAVAILABLE"
	ErrorCodePolicyVersionNotFound   ErrorCode = "POLICY_VERSION_NOT_FOUND"
	ErrorCodeRerankerUnavailable     ErrorCode = "RERANKER_UNAVAILABLE"
	ErrorCodeRetrievalTimeout        ErrorCode = "RETRIEVAL_TIMEOUT"
	ErrorCodeUnsupportedCategory     ErrorCode = "UNSUPPORTED_CATEGORY"
)

var AllErrorCodes = []ErrorCode{
	ErrorCodeInvalidArgument,
	ErrorCodeInternalError,
	ErrorCodePolicySourceUnavailable,
	ErrorCodePolicyVersionNotFound,
	ErrorCodeRerankerUnavailable,
	ErrorCodeRetrievalTimeout,
	ErrorCodeUnsupportedCategory,
}

var ErrorCodeMessageZH = map[ErrorCode]string{
	ErrorCodeInvalidArgument:         "入参不完整或格式错误，请检查后重试",
	ErrorCodeInternalError:           "系统异常，请稍后重试",
	ErrorCodePolicySourceUnavailable: "权威数据暂不可用，已转人工复核",
	ErrorCodePolicyVersionNotFound:   "未找到对应生效日税则版本",
	ErrorCodeRerankerUnavailable:     "重排服务暂不可用，已降级规则结果",
	ErrorCodeRetrievalTimeout:        "证据检索超时，请稍后重试",
	ErrorCodeUnsupportedCategory:     "当前品类暂不支持自动归类",
}

type ReviewReasonGroup string

const (
	ReviewReasonGroupHr ReviewReasonGroup = "HR"
	ReviewReasonGroupFr ReviewReasonGroup = "FR"
	ReviewReasonGroupQr ReviewReasonGroup = "QR"
)

var ReviewReasonPriorityOrder = []ReviewReasonGroup{
	ReviewReasonGroupHr,
	ReviewReasonGroupFr,
	ReviewReasonGroupQr,
}

type ReviewReasonCode string

const (
	ReviewReasonCodeFrHardRuleTriggered       ReviewReasonCode = "FR_HARD_RULE_TRIGGERED"
	ReviewReasonCodeFrLowCompleteness         ReviewReasonCode = "FR_LOW_COMPLETENESS"
	ReviewReasonCodeFrLowConfidence           ReviewReasonCode = "FR_LOW_CONFIDENCE"
	ReviewReasonCodeFrPolicySourceUnavailable ReviewReasonCode = "FR_POLICY_SOURCE_UNAVAILABLE"
	ReviewReasonCodeHrCategoryConflict        ReviewReasonCode = "HR_CATEGORY_CONFLICT"
	ReviewReasonCodeHrKeyFieldConflict        ReviewReasonCode = "HR_KEY_FIELD_CONFLICT"
	ReviewReasonCodeHrLowSourceTrust          ReviewReasonCode = "HR_LOW_SOURCE_TRUST"
	ReviewReasonCodeHrMissingGlobalRequired   ReviewReasonCode = "HR_MISSING_GLOBAL_REQUIRED"
	ReviewReasonCodeHrRegulatoryConflict      ReviewReasonCode = "HR_REGULATORY_CONFLICT"
	ReviewReasonCodeQrCompletenessRange       ReviewReasonCode = "QR_COMPLETENESS_RANGE"
	ReviewReasonCodeQrConfidenceRange         ReviewReasonCode = "QR_CONFIDENCE_RANGE"
	ReviewReasonCodeQrMissingCategoryRequired ReviewReasonCode = "QR_MISSING_CATEGORY_REQUIRED"
	ReviewReasonCodeQrTopGapLow               ReviewReasonCode = "QR_TOP_GAP_LOW"
)

var AllReviewReasonCodes = []ReviewReasonCode{
	ReviewReasonCodeFrHardRuleTriggered,
	ReviewReasonCodeFrLowCompleteness,
	ReviewReasonCodeFrLowConfidence,
	ReviewReasonCodeFrPolicySourceUnavailable,
	ReviewReasonCodeHrCategoryConflict,
	ReviewReasonCodeHrKeyFieldConflict,
	ReviewReasonCodeHrLowSourceTrust,
	ReviewReasonCodeHrMissingGlobalRequired,
	ReviewReasonCodeHrRegulatoryConflict,
	ReviewReasonCodeQrCompletenessRange,
	ReviewReasonCodeQrConfidenceRange,
	ReviewReasonCodeQrMissingCategoryRequired,
	ReviewReasonCodeQrTopGapLow,
}

var ReviewReasonCodeGroup = map[ReviewReasonCode]ReviewReasonGroup{
	ReviewReasonCodeFrHardRuleTriggered:       ReviewReasonGroupFr,
	ReviewReasonCodeFrLowCompleteness:         ReviewReasonGroupFr,
	ReviewReasonCodeFrLowConfidence:           ReviewReasonGroupFr,
	ReviewReasonCodeFrPolicySourceUnavailable: ReviewReasonGroupFr,
	ReviewReasonCodeHrCategoryConflict:        ReviewReasonGroupHr,
	ReviewReasonCodeHrKeyFieldConflict:        ReviewReasonGroupHr,
	ReviewReasonCodeHrLowSourceTrust:          ReviewReasonGroupHr,
	ReviewReasonCodeHrMissingGlobalRequired:   ReviewReasonGroupHr,
	ReviewReasonCodeHrRegulatoryConflict:      ReviewReasonGroupHr,
	ReviewReasonCodeQrCompletenessRange:       ReviewReasonGroupQr,
	ReviewReasonCodeQrConfidenceRange:         ReviewReasonGroupQr,
	ReviewReasonCodeQrMissingCategoryRequired: ReviewReasonGroupQr,
	ReviewReasonCodeQrTopGapLow:               ReviewReasonGroupQr,
}

var ReviewReasonCodeMessageZH = map[ReviewReasonCode]string{
	ReviewReasonCodeFrHardRuleTriggered:       "触发硬规则，需人工处理",
	ReviewReasonCodeFrLowCompleteness:         "信息不足，需人工补充后复核",
	ReviewReasonCodeFrLowConfidence:           "置信度低，禁止自动通过",
	ReviewReasonCodeFrPolicySourceUnavailable: "权威数据不可用，已强制人工",
	ReviewReasonCodeHrCategoryConflict:        "品类冲突，请人工确认品类",
	ReviewReasonCodeHrKeyFieldConflict:        "关键参数冲突，请确认权威来源",
	ReviewReasonCodeHrLowSourceTrust:          "参数来源可信度不足",
	ReviewReasonCodeHrMissingGlobalRequired:   "缺少核心字段，无法自动归类",
	ReviewReasonCodeHrRegulatoryConflict:      "监管条件存在冲突，需人工确认",
	ReviewReasonCodeQrCompletenessRange:       "关键要素不完整，建议补充参数后确认",
	ReviewReasonCodeQrConfidenceRange:         "置信度中等，建议人工快审",
	ReviewReasonCodeQrMissingCategoryRequired: "缺少品类关键字段，请补充",
	ReviewReasonCodeQrTopGapLow:               "候选分值接近，需人工判断",
}
