// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Server      *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data        *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Platform    *Platform              `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Agent       *Agent                 `protobuf:"bytes,4,opt,name=agent,proto3" json:"agent,omitempty"`
	ScriptStore *ScriptStore           `protobuf:"bytes,5,opt,name=script_store,json=scriptStore,proto3" json:"script_store,omitempty"`
	ScriptAdmin *ScriptAdmin           `protobuf:"bytes,6,opt,name=script_admin,json=scriptAdmin,proto3" json:"script_admin,omitempty"`
	// BOM 货源搜索任务回传（SubmitBomSearchResult），独立于 agent.api_keys
	BomSearchCallback *BomSearchCallback `protobuf:"bytes,7,opt,name=bom_search_callback,json=bomSearchCallback,proto3" json:"bom_search_callback,omitempty"`
	// Agent 运维查询 API（ListAgents / 租约任务 / 已装脚本），独立于 agent.api_keys
	AgentAdmin *AgentAdmin `protobuf:"bytes,8,opt,name=agent_admin,json=agentAdmin,proto3" json:"agent_admin,omitempty"`
	// OpenAI：BOM Upload parse_mode=llm 时推断列映射（github.com/sashabaranov/go-openai）
	Openai *OpenAI `protobuf:"bytes,9,opt,name=openai,proto3" json:"openai,omitempty"`
	// Agent 脚本登录凭据 AES-256-GCM 密钥（也可用环境变量 CAICHIP_AGENT_SCRIPT_AUTH_KEY）
	AgentScriptAuth *AgentScriptAuth `protobuf:"bytes,10,opt,name=agent_script_auth,json=agentScriptAuth,proto3" json:"agent_script_auth,omitempty"`
	// BOM 配单：基准币种、阶梯价解析、舍入（见 docs/superpowers/specs/2026-03-28-bom-match-currency-mfr-design.md）
	BomMatch      *BomMatch `protobuf:"bytes,11,opt,name=bom_match,json=bomMatch,proto3" json:"bom_match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetPlatform() *Platform {
	if x != nil {
		return x.Platform
	}
	return nil
}

func (x *Bootstrap) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *Bootstrap) GetScriptStore() *ScriptStore {
	if x != nil {
		return x.ScriptStore
	}
	return nil
}

func (x *Bootstrap) GetScriptAdmin() *ScriptAdmin {
	if x != nil {
		return x.ScriptAdmin
	}
	return nil
}

func (x *Bootstrap) GetBomSearchCallback() *BomSearchCallback {
	if x != nil {
		return x.BomSearchCallback
	}
	return nil
}

func (x *Bootstrap) GetAgentAdmin() *AgentAdmin {
	if x != nil {
		return x.AgentAdmin
	}
	return nil
}

func (x *Bootstrap) GetOpenai() *OpenAI {
	if x != nil {
		return x.Openai
	}
	return nil
}

func (x *Bootstrap) GetAgentScriptAuth() *AgentScriptAuth {
	if x != nil {
		return x.AgentScriptAuth
	}
	return nil
}

func (x *Bootstrap) GetBomMatch() *BomMatch {
	if x != nil {
		return x.BomMatch
	}
	return nil
}

// AgentScriptAuth 调度下发 platform_auth 时解密密码；未配置密钥时不可 Upsert，Pull 不注入。
type AgentScriptAuth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 32 字节原始密钥的 base64；与 env 二选一，env 优先
	AesKeyBase64  string `protobuf:"bytes,1,opt,name=aes_key_base64,json=aesKeyBase64,proto3" json:"aes_key_base64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentScriptAuth) Reset() {
	*x = AgentScriptAuth{}
	mi := &file_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentScriptAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentScriptAuth) ProtoMessage() {}

func (x *AgentScriptAuth) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentScriptAuth.ProtoReflect.Descriptor instead.
func (*AgentScriptAuth) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{1}
}

func (x *AgentScriptAuth) GetAesKeyBase64() string {
	if x != nil {
		return x.AesKeyBase64
	}
	return ""
}

// BomMatch 配单比价币种归一与数量/舍入相关部署配置（设计 §1、§1.10–§1.11）
type BomMatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 比较与排序基准币种，如 CNY、USD
	BaseCcy string `protobuf:"bytes,1,opt,name=base_ccy,json=baseCcy,proto3" json:"base_ccy,omitempty"`
	// 是否解析 price_tiers 等字符串阶梯价；默认 true（§1.5）
	ParsePriceTierStrings bool `protobuf:"varint,2,opt,name=parse_price_tier_strings,json=parsePriceTierStrings,proto3" json:"parse_price_tier_strings,omitempty"`
	// 舍入模式：minor_unit（最小货币单位整数）或 decimal6（十进制 6 位），§1.10
	RoundingMode string `protobuf:"bytes,3,opt,name=rounding_mode,json=roundingMode,proto3" json:"rounding_mode,omitempty"`
	// BOM 需求数量取整策略，如 ceil；未设置时由实现采用默认
	BomQtyRound   *string `protobuf:"bytes,4,opt,name=bom_qty_round,json=bomQtyRound,proto3,oneof" json:"bom_qty_round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BomMatch) Reset() {
	*x = BomMatch{}
	mi := &file_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BomMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BomMatch) ProtoMessage() {}

func (x *BomMatch) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BomMatch.ProtoReflect.Descriptor instead.
func (*BomMatch) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{2}
}

func (x *BomMatch) GetBaseCcy() string {
	if x != nil {
		return x.BaseCcy
	}
	return ""
}

func (x *BomMatch) GetParsePriceTierStrings() bool {
	if x != nil {
		return x.ParsePriceTierStrings
	}
	return false
}

func (x *BomMatch) GetRoundingMode() string {
	if x != nil {
		return x.RoundingMode
	}
	return ""
}

func (x *BomMatch) GetBomQtyRound() string {
	if x != nil && x.BomQtyRound != nil {
		return *x.BomQtyRound
	}
	return ""
}

// OpenAI 聊天补全（api_key 为空时不创建客户端，llm 模式将报错提示配置）
type OpenAI struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	ApiKey string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// 可选，兼容代理或 Azure OpenAI 风格网关；空则官方 https://api.openai.com/v1
	BaseUrl string `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	// 默认 gpt-4o-mini
	Model         string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAI) Reset() {
	*x = OpenAI{}
	mi := &file_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAI) ProtoMessage() {}

func (x *OpenAI) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAI.ProtoReflect.Descriptor instead.
func (*OpenAI) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{3}
}

func (x *OpenAI) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *OpenAI) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *OpenAI) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *ServerHTTP            `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *ServerGRPC            `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Server) GetHttp() *ServerHTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *ServerGRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type ServerHTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       int32                  `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"` // seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerHTTP) Reset() {
	*x = ServerHTTP{}
	mi := &file_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHTTP) ProtoMessage() {}

func (x *ServerHTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHTTP.ProtoReflect.Descriptor instead.
func (*ServerHTTP) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{5}
}

func (x *ServerHTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ServerHTTP) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type ServerGRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       int32                  `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"` // seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerGRPC) Reset() {
	*x = ServerGRPC{}
	mi := &file_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerGRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerGRPC) ProtoMessage() {}

func (x *ServerGRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerGRPC.ProtoReflect.Descriptor instead.
func (*ServerGRPC) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{6}
}

func (x *ServerGRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ServerGRPC) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *DataDatabase          `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis         *DataRedis             `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{7}
}

func (x *Data) GetDatabase() *DataDatabase {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetRedis() *DataRedis {
	if x != nil {
		return x.Redis
	}
	return nil
}

type DataDatabase struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Driver string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Dsn    string                 `protobuf:"bytes,2,opt,name=dsn,proto3" json:"dsn,omitempty"`
	// 未设置或 true：连接成功后执行 GORM AutoMigrate（建表/补列/补简单索引）；显式 false 时跳过（生产可用手工 SQL）。
	AutoMigrate *bool `protobuf:"varint,3,opt,name=auto_migrate,json=autoMigrate,proto3,oneof" json:"auto_migrate,omitempty"`
	// 为 true 时 GORM 将执行的 SQL 打印到标准输出（也可用环境变量 CAICHIP_GORM_LOG_SQL=1）
	LogSql *bool `protobuf:"varint,4,opt,name=log_sql,json=logSql,proto3,oneof" json:"log_sql,omitempty"`
	// go-sql-driver 的 loc：解析/写入 DATETIME 时使用的 IANA 时区，如 Asia/Shanghai、UTC。空则不在 DSN 追加 loc（驱动默认按 UTC 解析墙钟，易与「库内存本地时间」差 8h）。也可用环境变量 CAICHIP_MYSQL_LOC。
	MysqlLoc      *string `protobuf:"bytes,5,opt,name=mysql_loc,json=mysqlLoc,proto3,oneof" json:"mysql_loc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataDatabase) Reset() {
	*x = DataDatabase{}
	mi := &file_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataDatabase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataDatabase) ProtoMessage() {}

func (x *DataDatabase) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataDatabase.ProtoReflect.Descriptor instead.
func (*DataDatabase) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{8}
}

func (x *DataDatabase) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *DataDatabase) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

func (x *DataDatabase) GetAutoMigrate() bool {
	if x != nil && x.AutoMigrate != nil {
		return *x.AutoMigrate
	}
	return false
}

func (x *DataDatabase) GetLogSql() bool {
	if x != nil && x.LogSql != nil {
		return *x.LogSql
	}
	return false
}

func (x *DataDatabase) GetMysqlLoc() string {
	if x != nil && x.MysqlLoc != nil {
		return *x.MysqlLoc
	}
	return ""
}

type DataRedis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	ReadTimeout   int32                  `protobuf:"varint,2,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`    // seconds
	WriteTimeout  int32                  `protobuf:"varint,3,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"` // seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRedis) Reset() {
	*x = DataRedis{}
	mi := &file_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRedis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRedis) ProtoMessage() {}

func (x *DataRedis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRedis.ProtoReflect.Descriptor instead.
func (*DataRedis) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{9}
}

func (x *DataRedis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *DataRedis) GetReadTimeout() int32 {
	if x != nil {
		return x.ReadTimeout
	}
	return 0
}

func (x *DataRedis) GetWriteTimeout() int32 {
	if x != nil {
		return x.WriteTimeout
	}
	return 0
}

// Agent 分布式采集 Agent HTTP API（见 docs/分布式采集Agent需求与架构.md）
type Agent struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Enabled                    bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ApiKeys                    []string               `protobuf:"bytes,2,rep,name=api_keys,json=apiKeys,proto3" json:"api_keys,omitempty"`
	LongPollMaxSec             int32                  `protobuf:"varint,3,opt,name=long_poll_max_sec,json=longPollMaxSec,proto3" json:"long_poll_max_sec,omitempty"`                                   // 服务端单次挂起上限，默认 55
	DefaultTaskHeartbeatSec    int32                  `protobuf:"varint,4,opt,name=default_task_heartbeat_sec,json=defaultTaskHeartbeatSec,proto3" json:"default_task_heartbeat_sec,omitempty"`        // 用于 T_offline，默认 10
	OfflineMinSec              int32                  `protobuf:"varint,5,opt,name=offline_min_sec,json=offlineMinSec,proto3" json:"offline_min_sec,omitempty"`                                        // 默认 120
	OfflineHeartbeatMultiplier int32                  `protobuf:"varint,6,opt,name=offline_heartbeat_multiplier,json=offlineHeartbeatMultiplier,proto3" json:"offline_heartbeat_multiplier,omitempty"` // 默认 6，T_offline=max(min, k*interval)
	DevEnqueueEnabled          bool                   `protobuf:"varint,7,opt,name=dev_enqueue_enabled,json=devEnqueueEnabled,proto3" json:"dev_enqueue_enabled,omitempty"`                            // 仅开发：POST /api/v1/agent/dev/enqueue 入队任务
	// 任务队列：memory=纯内存 AgentHub；mysql=多实例共用 caichip_dispatch_task（须 MySQL8+）
	DispatchStore string `protobuf:"bytes,8,opt,name=dispatch_store,json=dispatchStore,proto3" json:"dispatch_store,omitempty"`
	// 租约 deadline 在任务 timeout_sec 基础上的额外秒数（0 表示仅用 timeout_sec）
	DispatchLeaseExtraSec int32 `protobuf:"varint,9,opt,name=dispatch_lease_extra_sec,json=dispatchLeaseExtraSec,proto3" json:"dispatch_lease_extra_sec,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{10}
}

func (x *Agent) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Agent) GetApiKeys() []string {
	if x != nil {
		return x.ApiKeys
	}
	return nil
}

func (x *Agent) GetLongPollMaxSec() int32 {
	if x != nil {
		return x.LongPollMaxSec
	}
	return 0
}

func (x *Agent) GetDefaultTaskHeartbeatSec() int32 {
	if x != nil {
		return x.DefaultTaskHeartbeatSec
	}
	return 0
}

func (x *Agent) GetOfflineMinSec() int32 {
	if x != nil {
		return x.OfflineMinSec
	}
	return 0
}

func (x *Agent) GetOfflineHeartbeatMultiplier() int32 {
	if x != nil {
		return x.OfflineHeartbeatMultiplier
	}
	return 0
}

func (x *Agent) GetDevEnqueueEnabled() bool {
	if x != nil {
		return x.DevEnqueueEnabled
	}
	return false
}

func (x *Agent) GetDispatchStore() string {
	if x != nil {
		return x.DispatchStore
	}
	return ""
}

func (x *Agent) GetDispatchLeaseExtraSec() int32 {
	if x != nil {
		return x.DispatchLeaseExtraSec
	}
	return 0
}

// ScriptStore 脚本制品落盘与对外 URL（见 docs/Agent脚本包分发-PRD与接口.md §7）
type ScriptStore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`                                   // 为 true 时 ScriptSyncHeartbeat 可按已发布 script_id 返回 sync_actions
	Root          string                 `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`                                          // 本地目录，如 /var/lib/caichip/agent-scripts
	UrlPrefix     string                 `protobuf:"bytes,3,opt,name=url_prefix,json=urlPrefix,proto3" json:"url_prefix,omitempty"`               // 主站路径前缀，如 /static/agent-scripts
	PublicBaseUrl string                 `protobuf:"bytes,4,opt,name=public_base_url,json=publicBaseUrl,proto3" json:"public_base_url,omitempty"` // 生成绝对下载 URL；空则仅返回相对路径（以 / 开头）
	MaxUploadMb   int32                  `protobuf:"varint,5,opt,name=max_upload_mb,json=maxUploadMb,proto3" json:"max_upload_mb,omitempty"`      // multipart 上限，默认 64
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptStore) Reset() {
	*x = ScriptStore{}
	mi := &file_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptStore) ProtoMessage() {}

func (x *ScriptStore) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptStore.ProtoReflect.Descriptor instead.
func (*ScriptStore) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{11}
}

func (x *ScriptStore) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ScriptStore) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *ScriptStore) GetUrlPrefix() string {
	if x != nil {
		return x.UrlPrefix
	}
	return ""
}

func (x *ScriptStore) GetPublicBaseUrl() string {
	if x != nil {
		return x.PublicBaseUrl
	}
	return ""
}

func (x *ScriptStore) GetMaxUploadMb() int32 {
	if x != nil {
		return x.MaxUploadMb
	}
	return 0
}

// ScriptAdmin 管理端上传/发布接口鉴权（独立于 agent.api_keys）
type ScriptAdmin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeys       []string               `protobuf:"bytes,1,rep,name=api_keys,json=apiKeys,proto3" json:"api_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptAdmin) Reset() {
	*x = ScriptAdmin{}
	mi := &file_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptAdmin) ProtoMessage() {}

func (x *ScriptAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptAdmin.ProtoReflect.Descriptor instead.
func (*ScriptAdmin) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{12}
}

func (x *ScriptAdmin) GetApiKeys() []string {
	if x != nil {
		return x.ApiKeys
	}
	return nil
}

// AgentAdmin Agent 运维只读 API（api/admin/v1）鉴权，与 agent.api_keys、script_admin 分离
type AgentAdmin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeys       []string               `protobuf:"bytes,1,rep,name=api_keys,json=apiKeys,proto3" json:"api_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentAdmin) Reset() {
	*x = AgentAdmin{}
	mi := &file_conf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentAdmin) ProtoMessage() {}

func (x *AgentAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentAdmin.ProtoReflect.Descriptor instead.
func (*AgentAdmin) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{13}
}

func (x *AgentAdmin) GetApiKeys() []string {
	if x != nil {
		return x.ApiKeys
	}
	return nil
}

// BomSearchCallback Agent 回写搜索结果的 HTTP/gRPC 鉴权
type BomSearchCallback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeys       []string               `protobuf:"bytes,1,rep,name=api_keys,json=apiKeys,proto3" json:"api_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BomSearchCallback) Reset() {
	*x = BomSearchCallback{}
	mi := &file_conf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BomSearchCallback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BomSearchCallback) ProtoMessage() {}

func (x *BomSearchCallback) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BomSearchCallback.ProtoReflect.Descriptor instead.
func (*BomSearchCallback) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{14}
}

func (x *BomSearchCallback) GetApiKeys() []string {
	if x != nil {
		return x.ApiKeys
	}
	return nil
}

type Platform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ickey         *PlatformConf          `protobuf:"bytes,1,opt,name=ickey,proto3" json:"ickey,omitempty"`
	Szlcsc        *PlatformConf          `protobuf:"bytes,2,opt,name=szlcsc,proto3" json:"szlcsc,omitempty"`
	Icgoo         *PlatformConf          `protobuf:"bytes,3,opt,name=icgoo,proto3" json:"icgoo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Platform) Reset() {
	*x = Platform{}
	mi := &file_conf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Platform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Platform) ProtoMessage() {}

func (x *Platform) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Platform.ProtoReflect.Descriptor instead.
func (*Platform) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{15}
}

func (x *Platform) GetIckey() *PlatformConf {
	if x != nil {
		return x.Ickey
	}
	return nil
}

func (x *Platform) GetSzlcsc() *PlatformConf {
	if x != nil {
		return x.Szlcsc
	}
	return nil
}

func (x *Platform) GetIcgoo() *PlatformConf {
	if x != nil {
		return x.Icgoo
	}
	return nil
}

type PlatformConf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchUrl     string                 `protobuf:"bytes,1,opt,name=search_url,json=searchUrl,proto3" json:"search_url,omitempty"`
	Timeout       int32                  `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	CrawlerPath   string                 `protobuf:"bytes,3,opt,name=crawler_path,json=crawlerPath,proto3" json:"crawler_path,omitempty"`
	CrawlerScript string                 `protobuf:"bytes,4,opt,name=crawler_script,json=crawlerScript,proto3" json:"crawler_script,omitempty"`
	WorkDir       string                 `protobuf:"bytes,5,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformConf) Reset() {
	*x = PlatformConf{}
	mi := &file_conf_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformConf) ProtoMessage() {}

func (x *PlatformConf) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformConf.ProtoReflect.Descriptor instead.
func (*PlatformConf) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{16}
}

func (x *PlatformConf) GetSearchUrl() string {
	if x != nil {
		return x.SearchUrl
	}
	return ""
}

func (x *PlatformConf) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *PlatformConf) GetCrawlerPath() string {
	if x != nil {
		return x.CrawlerPath
	}
	return ""
}

func (x *PlatformConf) GetCrawlerScript() string {
	if x != nil {
		return x.CrawlerScript
	}
	return ""
}

func (x *PlatformConf) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

var File_conf_proto protoreflect.FileDescriptor

const file_conf_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"conf.proto\x12\x04conf\"\x9e\x04\n" +
	"\tBootstrap\x12$\n" +
	"\x06server\x18\x01 \x01(\v2\f.conf.ServerR\x06server\x12\x1e\n" +
	"\x04data\x18\x02 \x01(\v2\n" +
	".conf.DataR\x04data\x12*\n" +
	"\bplatform\x18\x03 \x01(\v2\x0e.conf.PlatformR\bplatform\x12!\n" +
	"\x05agent\x18\x04 \x01(\v2\v.conf.AgentR\x05agent\x124\n" +
	"\fscript_store\x18\x05 \x01(\v2\x11.conf.ScriptStoreR\vscriptStore\x124\n" +
	"\fscript_admin\x18\x06 \x01(\v2\x11.conf.ScriptAdminR\vscriptAdmin\x12G\n" +
	"\x13bom_search_callback\x18\a \x01(\v2\x17.conf.BomSearchCallbackR\x11bomSearchCallback\x121\n" +
	"\vagent_admin\x18\b \x01(\v2\x10.conf.AgentAdminR\n" +
	"agentAdmin\x12$\n" +
	"\x06openai\x18\t \x01(\v2\f.conf.OpenAIR\x06openai\x12A\n" +
	"\x11agent_script_auth\x18\n" +
	" \x01(\v2\x15.conf.AgentScriptAuthR\x0fagentScriptAuth\x12+\n" +
	"\tbom_match\x18\v \x01(\v2\x0e.conf.BomMatchR\bbomMatch\"7\n" +
	"\x0fAgentScriptAuth\x12$\n" +
	"\x0eaes_key_base64\x18\x01 \x01(\tR\faesKeyBase64\"\xbe\x01\n" +
	"\bBomMatch\x12\x19\n" +
	"\bbase_ccy\x18\x01 \x01(\tR\abaseCcy\x127\n" +
	"\x18parse_price_tier_strings\x18\x02 \x01(\bR\x15parsePriceTierStrings\x12#\n" +
	"\rrounding_mode\x18\x03 \x01(\tR\froundingMode\x12'\n" +
	"\rbom_qty_round\x18\x04 \x01(\tH\x00R\vbomQtyRound\x88\x01\x01B\x10\n" +
	"\x0e_bom_qty_round\"R\n" +
	"\x06OpenAI\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\"T\n" +
	"\x06Server\x12$\n" +
	"\x04http\x18\x01 \x01(\v2\x10.conf.ServerHTTPR\x04http\x12$\n" +
	"\x04grpc\x18\x02 \x01(\v2\x10.conf.ServerGRPCR\x04grpc\":\n" +
	"\n" +
	"ServerHTTP\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x05R\atimeout\":\n" +
	"\n" +
	"ServerGRPC\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x05R\atimeout\"]\n" +
	"\x04Data\x12.\n" +
	"\bdatabase\x18\x01 \x01(\v2\x12.conf.DataDatabaseR\bdatabase\x12%\n" +
	"\x05redis\x18\x02 \x01(\v2\x0f.conf.DataRedisR\x05redis\"\xcb\x01\n" +
	"\fDataDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x10\n" +
	"\x03dsn\x18\x02 \x01(\tR\x03dsn\x12&\n" +
	"\fauto_migrate\x18\x03 \x01(\bH\x00R\vautoMigrate\x88\x01\x01\x12\x1c\n" +
	"\alog_sql\x18\x04 \x01(\bH\x01R\x06logSql\x88\x01\x01\x12 \n" +
	"\tmysql_loc\x18\x05 \x01(\tH\x02R\bmysqlLoc\x88\x01\x01B\x0f\n" +
	"\r_auto_migrateB\n" +
	"\n" +
	"\b_log_sqlB\f\n" +
	"\n" +
	"_mysql_loc\"g\n" +
	"\tDataRedis\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12!\n" +
	"\fread_timeout\x18\x02 \x01(\x05R\vreadTimeout\x12#\n" +
	"\rwrite_timeout\x18\x03 \x01(\x05R\fwriteTimeout\"\x9e\x03\n" +
	"\x05Agent\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x19\n" +
	"\bapi_keys\x18\x02 \x03(\tR\aapiKeys\x12)\n" +
	"\x11long_poll_max_sec\x18\x03 \x01(\x05R\x0elongPollMaxSec\x12;\n" +
	"\x1adefault_task_heartbeat_sec\x18\x04 \x01(\x05R\x17defaultTaskHeartbeatSec\x12&\n" +
	"\x0foffline_min_sec\x18\x05 \x01(\x05R\rofflineMinSec\x12@\n" +
	"\x1coffline_heartbeat_multiplier\x18\x06 \x01(\x05R\x1aofflineHeartbeatMultiplier\x12.\n" +
	"\x13dev_enqueue_enabled\x18\a \x01(\bR\x11devEnqueueEnabled\x12%\n" +
	"\x0edispatch_store\x18\b \x01(\tR\rdispatchStore\x127\n" +
	"\x18dispatch_lease_extra_sec\x18\t \x01(\x05R\x15dispatchLeaseExtraSec\"\xa6\x01\n" +
	"\vScriptStore\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x12\n" +
	"\x04root\x18\x02 \x01(\tR\x04root\x12\x1d\n" +
	"\n" +
	"url_prefix\x18\x03 \x01(\tR\turlPrefix\x12&\n" +
	"\x0fpublic_base_url\x18\x04 \x01(\tR\rpublicBaseUrl\x12\"\n" +
	"\rmax_upload_mb\x18\x05 \x01(\x05R\vmaxUploadMb\"(\n" +
	"\vScriptAdmin\x12\x19\n" +
	"\bapi_keys\x18\x01 \x03(\tR\aapiKeys\"'\n" +
	"\n" +
	"AgentAdmin\x12\x19\n" +
	"\bapi_keys\x18\x01 \x03(\tR\aapiKeys\".\n" +
	"\x11BomSearchCallback\x12\x19\n" +
	"\bapi_keys\x18\x01 \x03(\tR\aapiKeys\"\x8a\x01\n" +
	"\bPlatform\x12(\n" +
	"\x05ickey\x18\x01 \x01(\v2\x12.conf.PlatformConfR\x05ickey\x12*\n" +
	"\x06szlcsc\x18\x02 \x01(\v2\x12.conf.PlatformConfR\x06szlcsc\x12(\n" +
	"\x05icgoo\x18\x03 \x01(\v2\x12.conf.PlatformConfR\x05icgoo\"\xac\x01\n" +
	"\fPlatformConf\x12\x1d\n" +
	"\n" +
	"search_url\x18\x01 \x01(\tR\tsearchUrl\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x05R\atimeout\x12!\n" +
	"\fcrawler_path\x18\x03 \x01(\tR\vcrawlerPath\x12%\n" +
	"\x0ecrawler_script\x18\x04 \x01(\tR\rcrawlerScript\x12\x19\n" +
	"\bwork_dir\x18\x05 \x01(\tR\aworkDirB\x13Z\x11caichip/conf;confb\x06proto3"

var (
	file_conf_proto_rawDescOnce sync.Once
	file_conf_proto_rawDescData []byte
)

func file_conf_proto_rawDescGZIP() []byte {
	file_conf_proto_rawDescOnce.Do(func() {
		file_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_proto_rawDesc), len(file_conf_proto_rawDesc)))
	})
	return file_conf_proto_rawDescData
}

var file_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),         // 0: conf.Bootstrap
	(*AgentScriptAuth)(nil),   // 1: conf.AgentScriptAuth
	(*BomMatch)(nil),          // 2: conf.BomMatch
	(*OpenAI)(nil),            // 3: conf.OpenAI
	(*Server)(nil),            // 4: conf.Server
	(*ServerHTTP)(nil),        // 5: conf.ServerHTTP
	(*ServerGRPC)(nil),        // 6: conf.ServerGRPC
	(*Data)(nil),              // 7: conf.Data
	(*DataDatabase)(nil),      // 8: conf.DataDatabase
	(*DataRedis)(nil),         // 9: conf.DataRedis
	(*Agent)(nil),             // 10: conf.Agent
	(*ScriptStore)(nil),       // 11: conf.ScriptStore
	(*ScriptAdmin)(nil),       // 12: conf.ScriptAdmin
	(*AgentAdmin)(nil),        // 13: conf.AgentAdmin
	(*BomSearchCallback)(nil), // 14: conf.BomSearchCallback
	(*Platform)(nil),          // 15: conf.Platform
	(*PlatformConf)(nil),      // 16: conf.PlatformConf
}
var file_conf_proto_depIdxs = []int32{
	4,  // 0: conf.Bootstrap.server:type_name -> conf.Server
	7,  // 1: conf.Bootstrap.data:type_name -> conf.Data
	15, // 2: conf.Bootstrap.platform:type_name -> conf.Platform
	10, // 3: conf.Bootstrap.agent:type_name -> conf.Agent
	11, // 4: conf.Bootstrap.script_store:type_name -> conf.ScriptStore
	12, // 5: conf.Bootstrap.script_admin:type_name -> conf.ScriptAdmin
	14, // 6: conf.Bootstrap.bom_search_callback:type_name -> conf.BomSearchCallback
	13, // 7: conf.Bootstrap.agent_admin:type_name -> conf.AgentAdmin
	3,  // 8: conf.Bootstrap.openai:type_name -> conf.OpenAI
	1,  // 9: conf.Bootstrap.agent_script_auth:type_name -> conf.AgentScriptAuth
	2,  // 10: conf.Bootstrap.bom_match:type_name -> conf.BomMatch
	5,  // 11: conf.Server.http:type_name -> conf.ServerHTTP
	6,  // 12: conf.Server.grpc:type_name -> conf.ServerGRPC
	8,  // 13: conf.Data.database:type_name -> conf.DataDatabase
	9,  // 14: conf.Data.redis:type_name -> conf.DataRedis
	16, // 15: conf.Platform.ickey:type_name -> conf.PlatformConf
	16, // 16: conf.Platform.szlcsc:type_name -> conf.PlatformConf
	16, // 17: conf.Platform.icgoo:type_name -> conf.PlatformConf
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_conf_proto_init() }
func file_conf_proto_init() {
	if File_conf_proto != nil {
		return
	}
	file_conf_proto_msgTypes[2].OneofWrappers = []any{}
	file_conf_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_proto_rawDesc), len(file_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_proto_goTypes,
		DependencyIndexes: file_conf_proto_depIdxs,
		MessageInfos:      file_conf_proto_msgTypes,
	}.Build()
	File_conf_proto = out.File
	file_conf_proto_goTypes = nil
	file_conf_proto_depIdxs = nil
}
