// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.0
// source: agent/v1/agent.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAgentServiceScriptSyncHeartbeat = "/api.agent.v1.AgentService/ScriptSyncHeartbeat"
const OperationAgentServiceTaskHeartbeat = "/api.agent.v1.AgentService/TaskHeartbeat"
const OperationAgentServiceTaskResult = "/api.agent.v1.AgentService/TaskResult"

type AgentServiceHTTPServer interface {
	// ScriptSyncHeartbeat 脚本安装心跳
	ScriptSyncHeartbeat(context.Context, *ScriptSyncHeartbeatRequest) (*ScriptSyncHeartbeatReply, error)
	// TaskHeartbeat 任务心跳（长轮询拉任务）
	TaskHeartbeat(context.Context, *TaskHeartbeatRequest) (*TaskHeartbeatReply, error)
	// TaskResult 任务结果上报
	TaskResult(context.Context, *TaskResultRequest) (*TaskResultReply, error)
}

func RegisterAgentServiceHTTPServer(s *http.Server, srv AgentServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/agent/task/heartbeat", _AgentService_TaskHeartbeat0_HTTP_Handler(srv))
	r.POST("/api/v1/agent/script-sync/heartbeat", _AgentService_ScriptSyncHeartbeat0_HTTP_Handler(srv))
	r.POST("/api/v1/agent/task/result", _AgentService_TaskResult0_HTTP_Handler(srv))
}

func _AgentService_TaskHeartbeat0_HTTP_Handler(srv AgentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TaskHeartbeatRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentServiceTaskHeartbeat)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TaskHeartbeat(ctx, req.(*TaskHeartbeatRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TaskHeartbeatReply)
		return ctx.Result(200, reply)
	}
}

func _AgentService_ScriptSyncHeartbeat0_HTTP_Handler(srv AgentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ScriptSyncHeartbeatRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentServiceScriptSyncHeartbeat)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ScriptSyncHeartbeat(ctx, req.(*ScriptSyncHeartbeatRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ScriptSyncHeartbeatReply)
		return ctx.Result(200, reply)
	}
}

func _AgentService_TaskResult0_HTTP_Handler(srv AgentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TaskResultRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAgentServiceTaskResult)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TaskResult(ctx, req.(*TaskResultRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TaskResultReply)
		return ctx.Result(200, reply)
	}
}

type AgentServiceHTTPClient interface {
	// ScriptSyncHeartbeat 脚本安装心跳
	ScriptSyncHeartbeat(ctx context.Context, req *ScriptSyncHeartbeatRequest, opts ...http.CallOption) (rsp *ScriptSyncHeartbeatReply, err error)
	// TaskHeartbeat 任务心跳（长轮询拉任务）
	TaskHeartbeat(ctx context.Context, req *TaskHeartbeatRequest, opts ...http.CallOption) (rsp *TaskHeartbeatReply, err error)
	// TaskResult 任务结果上报
	TaskResult(ctx context.Context, req *TaskResultRequest, opts ...http.CallOption) (rsp *TaskResultReply, err error)
}

type AgentServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAgentServiceHTTPClient(client *http.Client) AgentServiceHTTPClient {
	return &AgentServiceHTTPClientImpl{client}
}

// ScriptSyncHeartbeat 脚本安装心跳
func (c *AgentServiceHTTPClientImpl) ScriptSyncHeartbeat(ctx context.Context, in *ScriptSyncHeartbeatRequest, opts ...http.CallOption) (*ScriptSyncHeartbeatReply, error) {
	var out ScriptSyncHeartbeatReply
	pattern := "/api/v1/agent/script-sync/heartbeat"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAgentServiceScriptSyncHeartbeat))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// TaskHeartbeat 任务心跳（长轮询拉任务）
func (c *AgentServiceHTTPClientImpl) TaskHeartbeat(ctx context.Context, in *TaskHeartbeatRequest, opts ...http.CallOption) (*TaskHeartbeatReply, error) {
	var out TaskHeartbeatReply
	pattern := "/api/v1/agent/task/heartbeat"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAgentServiceTaskHeartbeat))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// TaskResult 任务结果上报
func (c *AgentServiceHTTPClientImpl) TaskResult(ctx context.Context, in *TaskResultRequest, opts ...http.CallOption) (*TaskResultReply, error) {
	var out TaskResultReply
	pattern := "/api/v1/agent/task/result"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAgentServiceTaskResult))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
