// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: agent/v1/agent.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskHeartbeatRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion    string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	AgentId            string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Queue              string                 `protobuf:"bytes,3,opt,name=queue,proto3" json:"queue,omitempty"`
	Tags               []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	InstalledScripts   []*InstalledScript     `protobuf:"bytes,5,rep,name=installed_scripts,json=installedScripts,proto3" json:"installed_scripts,omitempty"`
	Hostname           string                 `protobuf:"bytes,6,opt,name=hostname,proto3" json:"hostname,omitempty"`
	ReportedAt         string                 `protobuf:"bytes,7,opt,name=reported_at,json=reportedAt,proto3" json:"reported_at,omitempty"`
	Runtime            *RuntimeInfo           `protobuf:"bytes,8,opt,name=runtime,proto3" json:"runtime,omitempty"`
	LongPollTimeoutSec int32                  `protobuf:"varint,9,opt,name=long_poll_timeout_sec,json=longPollTimeoutSec,proto3" json:"long_poll_timeout_sec,omitempty"`
	// 当前在本 Agent 上正在执行的任务（方案 A：必填语义由服务端强约束调度；Agent 无执行中时可传空数组）
	RunningTasks  []*RunningTask `protobuf:"bytes,10,rep,name=running_tasks,json=runningTasks,proto3" json:"running_tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskHeartbeatRequest) Reset() {
	*x = TaskHeartbeatRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskHeartbeatRequest) ProtoMessage() {}

func (x *TaskHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*TaskHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *TaskHeartbeatRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *TaskHeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TaskHeartbeatRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *TaskHeartbeatRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TaskHeartbeatRequest) GetInstalledScripts() []*InstalledScript {
	if x != nil {
		return x.InstalledScripts
	}
	return nil
}

func (x *TaskHeartbeatRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *TaskHeartbeatRequest) GetReportedAt() string {
	if x != nil {
		return x.ReportedAt
	}
	return ""
}

func (x *TaskHeartbeatRequest) GetRuntime() *RuntimeInfo {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *TaskHeartbeatRequest) GetLongPollTimeoutSec() int32 {
	if x != nil {
		return x.LongPollTimeoutSec
	}
	return 0
}

func (x *TaskHeartbeatRequest) GetRunningTasks() []*RunningTask {
	if x != nil {
		return x.RunningTasks
	}
	return nil
}

// RunningTask Agent 上报的进行中任务，用于避免长轮询重复派发、并与 script_id 串行语义对齐。
type RunningTask struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TaskId   string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	LeaseId  string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	ScriptId string                 `protobuf:"bytes,3,opt,name=script_id,json=scriptId,proto3" json:"script_id,omitempty"`
	// RFC3339Nano，可选
	StartedAt     string `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunningTask) Reset() {
	*x = RunningTask{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunningTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningTask) ProtoMessage() {}

func (x *RunningTask) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningTask.ProtoReflect.Descriptor instead.
func (*RunningTask) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RunningTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RunningTask) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *RunningTask) GetScriptId() string {
	if x != nil {
		return x.ScriptId
	}
	return ""
}

func (x *RunningTask) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

type InstalledScript struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScriptId      string                 `protobuf:"bytes,1,opt,name=script_id,json=scriptId,proto3" json:"script_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	EnvStatus     string                 `protobuf:"bytes,3,opt,name=env_status,json=envStatus,proto3" json:"env_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstalledScript) Reset() {
	*x = InstalledScript{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstalledScript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstalledScript) ProtoMessage() {}

func (x *InstalledScript) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstalledScript.ProtoReflect.Descriptor instead.
func (*InstalledScript) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *InstalledScript) GetScriptId() string {
	if x != nil {
		return x.ScriptId
	}
	return ""
}

func (x *InstalledScript) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstalledScript) GetEnvStatus() string {
	if x != nil {
		return x.EnvStatus
	}
	return ""
}

type RuntimeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PythonVersion string                 `protobuf:"bytes,1,opt,name=python_version,json=pythonVersion,proto3" json:"python_version,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeInfo) Reset() {
	*x = RuntimeInfo{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeInfo) ProtoMessage() {}

func (x *RuntimeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeInfo.ProtoReflect.Descriptor instead.
func (*RuntimeInfo) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *RuntimeInfo) GetPythonVersion() string {
	if x != nil {
		return x.PythonVersion
	}
	return ""
}

func (x *RuntimeInfo) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type TaskHeartbeatReply struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ServerTime         string                 `protobuf:"bytes,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	LongPollTimeoutSec int32                  `protobuf:"varint,2,opt,name=long_poll_timeout_sec,json=longPollTimeoutSec,proto3" json:"long_poll_timeout_sec,omitempty"`
	Tasks              []*TaskObject          `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TaskHeartbeatReply) Reset() {
	*x = TaskHeartbeatReply{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskHeartbeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskHeartbeatReply) ProtoMessage() {}

func (x *TaskHeartbeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskHeartbeatReply.ProtoReflect.Descriptor instead.
func (*TaskHeartbeatReply) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *TaskHeartbeatReply) GetServerTime() string {
	if x != nil {
		return x.ServerTime
	}
	return ""
}

func (x *TaskHeartbeatReply) GetLongPollTimeoutSec() int32 {
	if x != nil {
		return x.LongPollTimeoutSec
	}
	return 0
}

func (x *TaskHeartbeatReply) GetTasks() []*TaskObject {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type TaskObject struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ScriptId       string                 `protobuf:"bytes,2,opt,name=script_id,json=scriptId,proto3" json:"script_id,omitempty"`
	Version        string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	EntryFile      *string                `protobuf:"bytes,4,opt,name=entry_file,json=entryFile,proto3,oneof" json:"entry_file,omitempty"`
	Argv           []string               `protobuf:"bytes,5,rep,name=argv,proto3" json:"argv,omitempty"`
	Params         *structpb.Struct       `protobuf:"bytes,6,opt,name=params,proto3" json:"params,omitempty"`
	TimeoutSec     int32                  `protobuf:"varint,7,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`
	LeaseId        string                 `protobuf:"bytes,8,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,9,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	TraceId        string                 `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskObject) Reset() {
	*x = TaskObject{}
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskObject) ProtoMessage() {}

func (x *TaskObject) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskObject.ProtoReflect.Descriptor instead.
func (*TaskObject) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *TaskObject) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskObject) GetScriptId() string {
	if x != nil {
		return x.ScriptId
	}
	return ""
}

func (x *TaskObject) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TaskObject) GetEntryFile() string {
	if x != nil && x.EntryFile != nil {
		return *x.EntryFile
	}
	return ""
}

func (x *TaskObject) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *TaskObject) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *TaskObject) GetTimeoutSec() int32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

func (x *TaskObject) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *TaskObject) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *TaskObject) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type ScriptSyncHeartbeatRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion    string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	AgentId            string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Queue              string                 `protobuf:"bytes,3,opt,name=queue,proto3" json:"queue,omitempty"`
	Tags               []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Scripts            []*ScriptRow           `protobuf:"bytes,5,rep,name=scripts,proto3" json:"scripts,omitempty"`
	LongPollTimeoutSec int32                  `protobuf:"varint,6,opt,name=long_poll_timeout_sec,json=longPollTimeoutSec,proto3" json:"long_poll_timeout_sec,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ScriptSyncHeartbeatRequest) Reset() {
	*x = ScriptSyncHeartbeatRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptSyncHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptSyncHeartbeatRequest) ProtoMessage() {}

func (x *ScriptSyncHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptSyncHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*ScriptSyncHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ScriptSyncHeartbeatRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *ScriptSyncHeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ScriptSyncHeartbeatRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *ScriptSyncHeartbeatRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ScriptSyncHeartbeatRequest) GetScripts() []*ScriptRow {
	if x != nil {
		return x.Scripts
	}
	return nil
}

func (x *ScriptSyncHeartbeatRequest) GetLongPollTimeoutSec() int32 {
	if x != nil {
		return x.LongPollTimeoutSec
	}
	return 0
}

type ScriptRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScriptId      string                 `protobuf:"bytes,1,opt,name=script_id,json=scriptId,proto3" json:"script_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	PackageSha256 *string                `protobuf:"bytes,3,opt,name=package_sha256,json=packageSha256,proto3,oneof" json:"package_sha256,omitempty"`
	EnvStatus     string                 `protobuf:"bytes,4,opt,name=env_status,json=envStatus,proto3" json:"env_status,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	InstalledAt   *string                `protobuf:"bytes,7,opt,name=installed_at,json=installedAt,proto3,oneof" json:"installed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptRow) Reset() {
	*x = ScriptRow{}
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptRow) ProtoMessage() {}

func (x *ScriptRow) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptRow.ProtoReflect.Descriptor instead.
func (*ScriptRow) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ScriptRow) GetScriptId() string {
	if x != nil {
		return x.ScriptId
	}
	return ""
}

func (x *ScriptRow) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ScriptRow) GetPackageSha256() string {
	if x != nil && x.PackageSha256 != nil {
		return *x.PackageSha256
	}
	return ""
}

func (x *ScriptRow) GetEnvStatus() string {
	if x != nil {
		return x.EnvStatus
	}
	return ""
}

func (x *ScriptRow) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ScriptRow) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ScriptRow) GetInstalledAt() string {
	if x != nil && x.InstalledAt != nil {
		return *x.InstalledAt
	}
	return ""
}

type ScriptSyncHeartbeatReply struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ServerTime         string                 `protobuf:"bytes,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	LongPollTimeoutSec int32                  `protobuf:"varint,2,opt,name=long_poll_timeout_sec,json=longPollTimeoutSec,proto3" json:"long_poll_timeout_sec,omitempty"`
	SyncActions        []*SyncAction          `protobuf:"bytes,3,rep,name=sync_actions,json=syncActions,proto3" json:"sync_actions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ScriptSyncHeartbeatReply) Reset() {
	*x = ScriptSyncHeartbeatReply{}
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptSyncHeartbeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptSyncHeartbeatReply) ProtoMessage() {}

func (x *ScriptSyncHeartbeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptSyncHeartbeatReply.ProtoReflect.Descriptor instead.
func (*ScriptSyncHeartbeatReply) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ScriptSyncHeartbeatReply) GetServerTime() string {
	if x != nil {
		return x.ServerTime
	}
	return ""
}

func (x *ScriptSyncHeartbeatReply) GetLongPollTimeoutSec() int32 {
	if x != nil {
		return x.LongPollTimeoutSec
	}
	return 0
}

func (x *ScriptSyncHeartbeatReply) GetSyncActions() []*SyncAction {
	if x != nil {
		return x.SyncActions
	}
	return nil
}

type SyncAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	ScriptId      string                 `protobuf:"bytes,2,opt,name=script_id,json=scriptId,proto3" json:"script_id,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	PackageSha256 string                 `protobuf:"bytes,4,opt,name=package_sha256,json=packageSha256,proto3" json:"package_sha256,omitempty"`
	Download      *DownloadSpec          `protobuf:"bytes,5,opt,name=download,proto3" json:"download,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAction) Reset() {
	*x = SyncAction{}
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAction) ProtoMessage() {}

func (x *SyncAction) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAction.ProtoReflect.Descriptor instead.
func (*SyncAction) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *SyncAction) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SyncAction) GetScriptId() string {
	if x != nil {
		return x.ScriptId
	}
	return ""
}

func (x *SyncAction) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SyncAction) GetPackageSha256() string {
	if x != nil {
		return x.PackageSha256
	}
	return ""
}

func (x *SyncAction) GetDownload() *DownloadSpec {
	if x != nil {
		return x.Download
	}
	return nil
}

func (x *SyncAction) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DownloadSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpiresAt     string                 `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadSpec) Reset() {
	*x = DownloadSpec{}
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadSpec) ProtoMessage() {}

func (x *DownloadSpec) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadSpec.ProtoReflect.Descriptor instead.
func (*DownloadSpec) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *DownloadSpec) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *DownloadSpec) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DownloadSpec) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *DownloadSpec) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type TaskResultRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	AgentId         string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TaskId          string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt       string                 `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt      string                 `protobuf:"bytes,6,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	ExitCode        *int32                 `protobuf:"varint,7,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	Stdout          string                 `protobuf:"bytes,8,opt,name=stdout,proto3" json:"stdout,omitempty"`
	StderrTail      string                 `protobuf:"bytes,9,opt,name=stderr_tail,json=stderrTail,proto3" json:"stderr_tail,omitempty"`
	Result          *structpb.Struct       `protobuf:"bytes,10,opt,name=result,proto3" json:"result,omitempty"`
	Error           *structpb.Value        `protobuf:"bytes,11,opt,name=error,proto3" json:"error,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,12,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	LeaseId         string                 `protobuf:"bytes,13,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Attempt         int32                  `protobuf:"varint,14,opt,name=attempt,proto3" json:"attempt,omitempty"`
	TraceId         string                 `protobuf:"bytes,15,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskResultRequest) Reset() {
	*x = TaskResultRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultRequest) ProtoMessage() {}

func (x *TaskResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultRequest.ProtoReflect.Descriptor instead.
func (*TaskResultRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *TaskResultRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *TaskResultRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TaskResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResultRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskResultRequest) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *TaskResultRequest) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

func (x *TaskResultRequest) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *TaskResultRequest) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *TaskResultRequest) GetStderrTail() string {
	if x != nil {
		return x.StderrTail
	}
	return ""
}

func (x *TaskResultRequest) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *TaskResultRequest) GetError() *structpb.Value {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *TaskResultRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *TaskResultRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *TaskResultRequest) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *TaskResultRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type TaskResultReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ServerTime    string                 `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResultReply) Reset() {
	*x = TaskResultReply{}
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultReply) ProtoMessage() {}

func (x *TaskResultReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultReply.ProtoReflect.Descriptor instead.
func (*TaskResultReply) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *TaskResultReply) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *TaskResultReply) GetServerTime() string {
	if x != nil {
		return x.ServerTime
	}
	return ""
}

// 统一错误体（§1.4），用于文档与其它语言；HTTP 层仍可直接序列化同名 JSON。
type ErrorBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *ErrorDetail           `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorBody) Reset() {
	*x = ErrorBody{}
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorBody) ProtoMessage() {}

func (x *ErrorBody) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorBody.ProtoReflect.Descriptor instead.
func (*ErrorBody) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ErrorBody) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ErrorDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\fapi.agent.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xb7\x03\n" +
	"\x14TaskHeartbeatRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x14\n" +
	"\x05queue\x18\x03 \x01(\tR\x05queue\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12J\n" +
	"\x11installed_scripts\x18\x05 \x03(\v2\x1d.api.agent.v1.InstalledScriptR\x10installedScripts\x12\x1a\n" +
	"\bhostname\x18\x06 \x01(\tR\bhostname\x12\x1f\n" +
	"\vreported_at\x18\a \x01(\tR\n" +
	"reportedAt\x123\n" +
	"\aruntime\x18\b \x01(\v2\x19.api.agent.v1.RuntimeInfoR\aruntime\x121\n" +
	"\x15long_poll_timeout_sec\x18\t \x01(\x05R\x12longPollTimeoutSec\x12>\n" +
	"\rrunning_tasks\x18\n" +
	" \x03(\v2\x19.api.agent.v1.RunningTaskR\frunningTasks\"}\n" +
	"\vRunningTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12\x1b\n" +
	"\tscript_id\x18\x03 \x01(\tR\bscriptId\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\tR\tstartedAt\"g\n" +
	"\x0fInstalledScript\x12\x1b\n" +
	"\tscript_id\x18\x01 \x01(\tR\bscriptId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"env_status\x18\x03 \x01(\tR\tenvStatus\"Y\n" +
	"\vRuntimeInfo\x12%\n" +
	"\x0epython_version\x18\x01 \x01(\tR\rpythonVersion\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\"\x98\x01\n" +
	"\x12TaskHeartbeatReply\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\tR\n" +
	"serverTime\x121\n" +
	"\x15long_poll_timeout_sec\x18\x02 \x01(\x05R\x12longPollTimeoutSec\x12.\n" +
	"\x05tasks\x18\x03 \x03(\v2\x18.api.agent.v1.TaskObjectR\x05tasks\"\xd4\x02\n" +
	"\n" +
	"TaskObject\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tscript_id\x18\x02 \x01(\tR\bscriptId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\"\n" +
	"\n" +
	"entry_file\x18\x04 \x01(\tH\x00R\tentryFile\x88\x01\x01\x12\x12\n" +
	"\x04argv\x18\x05 \x03(\tR\x04argv\x12/\n" +
	"\x06params\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x06params\x12\x1f\n" +
	"\vtimeout_sec\x18\a \x01(\x05R\n" +
	"timeoutSec\x12\x19\n" +
	"\blease_id\x18\b \x01(\tR\aleaseId\x12'\n" +
	"\x0fidempotency_key\x18\t \x01(\tR\x0eidempotencyKey\x12\x19\n" +
	"\btrace_id\x18\n" +
	" \x01(\tR\atraceIdB\r\n" +
	"\v_entry_file\"\x85\x02\n" +
	"\x1aScriptSyncHeartbeatRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x14\n" +
	"\x05queue\x18\x03 \x01(\tR\x05queue\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x121\n" +
	"\ascripts\x18\x05 \x03(\v2\x17.api.agent.v1.ScriptRowR\ascripts\x121\n" +
	"\x15long_poll_timeout_sec\x18\x06 \x01(\x05R\x12longPollTimeoutSecJ\x04\b\a\x10\bR\vplatform_id\"\x92\x02\n" +
	"\tScriptRow\x12\x1b\n" +
	"\tscript_id\x18\x01 \x01(\tR\bscriptId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12*\n" +
	"\x0epackage_sha256\x18\x03 \x01(\tH\x00R\rpackageSha256\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"env_status\x18\x04 \x01(\tR\tenvStatus\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12&\n" +
	"\finstalled_at\x18\a \x01(\tH\x01R\vinstalledAt\x88\x01\x01B\x11\n" +
	"\x0f_package_sha256B\x0f\n" +
	"\r_installed_at\"\xab\x01\n" +
	"\x18ScriptSyncHeartbeatReply\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\tR\n" +
	"serverTime\x121\n" +
	"\x15long_poll_timeout_sec\x18\x02 \x01(\x05R\x12longPollTimeoutSec\x12;\n" +
	"\fsync_actions\x18\x03 \x03(\v2\x18.api.agent.v1.SyncActionR\vsyncActions\"\xd2\x01\n" +
	"\n" +
	"SyncAction\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1b\n" +
	"\tscript_id\x18\x02 \x01(\tR\bscriptId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12%\n" +
	"\x0epackage_sha256\x18\x04 \x01(\tR\rpackageSha256\x126\n" +
	"\bdownload\x18\x05 \x01(\v2\x1a.api.agent.v1.DownloadSpecR\bdownload\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"\xd6\x01\n" +
	"\fDownloadSpec\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12A\n" +
	"\aheaders\x18\x03 \x03(\v2'.api.agent.v1.DownloadSpec.HeadersEntryR\aheaders\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\tR\texpiresAt\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x04\n" +
	"\x11TaskResultRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\tR\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\x06 \x01(\tR\n" +
	"finishedAt\x12 \n" +
	"\texit_code\x18\a \x01(\x05H\x00R\bexitCode\x88\x01\x01\x12\x16\n" +
	"\x06stdout\x18\b \x01(\tR\x06stdout\x12\x1f\n" +
	"\vstderr_tail\x18\t \x01(\tR\n" +
	"stderrTail\x12/\n" +
	"\x06result\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\x06result\x12,\n" +
	"\x05error\x18\v \x01(\v2\x16.google.protobuf.ValueR\x05error\x12'\n" +
	"\x0fidempotency_key\x18\f \x01(\tR\x0eidempotencyKey\x12\x19\n" +
	"\blease_id\x18\r \x01(\tR\aleaseId\x12\x18\n" +
	"\aattempt\x18\x0e \x01(\x05R\aattempt\x12\x19\n" +
	"\btrace_id\x18\x0f \x01(\tR\atraceIdB\f\n" +
	"\n" +
	"_exit_code\"N\n" +
	"\x0fTaskResultReply\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\tR\n" +
	"serverTime\"<\n" +
	"\tErrorBody\x12/\n" +
	"\x05error\x18\x01 \x01(\v2\x19.api.agent.v1.ErrorDetailR\x05error\";\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9c\x03\n" +
	"\fAgentService\x12~\n" +
	"\rTaskHeartbeat\x12\".api.agent.v1.TaskHeartbeatRequest\x1a .api.agent.v1.TaskHeartbeatReply\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/agent/task/heartbeat\x12\x97\x01\n" +
	"\x13ScriptSyncHeartbeat\x12(.api.agent.v1.ScriptSyncHeartbeatRequest\x1a&.api.agent.v1.ScriptSyncHeartbeatReply\".\x82\xd3\xe4\x93\x02(:\x01*\"#/api/v1/agent/script-sync/heartbeat\x12r\n" +
	"\n" +
	"TaskResult\x12\x1f.api.agent.v1.TaskResultRequest\x1a\x1d.api.agent.v1.TaskResultReply\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/agent/task/resultB\x19Z\x17caichip/api/agent/v1;v1b\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_agent_v1_agent_proto_goTypes = []any{
	(*TaskHeartbeatRequest)(nil),       // 0: api.agent.v1.TaskHeartbeatRequest
	(*RunningTask)(nil),                // 1: api.agent.v1.RunningTask
	(*InstalledScript)(nil),            // 2: api.agent.v1.InstalledScript
	(*RuntimeInfo)(nil),                // 3: api.agent.v1.RuntimeInfo
	(*TaskHeartbeatReply)(nil),         // 4: api.agent.v1.TaskHeartbeatReply
	(*TaskObject)(nil),                 // 5: api.agent.v1.TaskObject
	(*ScriptSyncHeartbeatRequest)(nil), // 6: api.agent.v1.ScriptSyncHeartbeatRequest
	(*ScriptRow)(nil),                  // 7: api.agent.v1.ScriptRow
	(*ScriptSyncHeartbeatReply)(nil),   // 8: api.agent.v1.ScriptSyncHeartbeatReply
	(*SyncAction)(nil),                 // 9: api.agent.v1.SyncAction
	(*DownloadSpec)(nil),               // 10: api.agent.v1.DownloadSpec
	(*TaskResultRequest)(nil),          // 11: api.agent.v1.TaskResultRequest
	(*TaskResultReply)(nil),            // 12: api.agent.v1.TaskResultReply
	(*ErrorBody)(nil),                  // 13: api.agent.v1.ErrorBody
	(*ErrorDetail)(nil),                // 14: api.agent.v1.ErrorDetail
	nil,                                // 15: api.agent.v1.DownloadSpec.HeadersEntry
	(*structpb.Struct)(nil),            // 16: google.protobuf.Struct
	(*structpb.Value)(nil),             // 17: google.protobuf.Value
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	2,  // 0: api.agent.v1.TaskHeartbeatRequest.installed_scripts:type_name -> api.agent.v1.InstalledScript
	3,  // 1: api.agent.v1.TaskHeartbeatRequest.runtime:type_name -> api.agent.v1.RuntimeInfo
	1,  // 2: api.agent.v1.TaskHeartbeatRequest.running_tasks:type_name -> api.agent.v1.RunningTask
	5,  // 3: api.agent.v1.TaskHeartbeatReply.tasks:type_name -> api.agent.v1.TaskObject
	16, // 4: api.agent.v1.TaskObject.params:type_name -> google.protobuf.Struct
	7,  // 5: api.agent.v1.ScriptSyncHeartbeatRequest.scripts:type_name -> api.agent.v1.ScriptRow
	9,  // 6: api.agent.v1.ScriptSyncHeartbeatReply.sync_actions:type_name -> api.agent.v1.SyncAction
	10, // 7: api.agent.v1.SyncAction.download:type_name -> api.agent.v1.DownloadSpec
	15, // 8: api.agent.v1.DownloadSpec.headers:type_name -> api.agent.v1.DownloadSpec.HeadersEntry
	16, // 9: api.agent.v1.TaskResultRequest.result:type_name -> google.protobuf.Struct
	17, // 10: api.agent.v1.TaskResultRequest.error:type_name -> google.protobuf.Value
	14, // 11: api.agent.v1.ErrorBody.error:type_name -> api.agent.v1.ErrorDetail
	0,  // 12: api.agent.v1.AgentService.TaskHeartbeat:input_type -> api.agent.v1.TaskHeartbeatRequest
	6,  // 13: api.agent.v1.AgentService.ScriptSyncHeartbeat:input_type -> api.agent.v1.ScriptSyncHeartbeatRequest
	11, // 14: api.agent.v1.AgentService.TaskResult:input_type -> api.agent.v1.TaskResultRequest
	4,  // 15: api.agent.v1.AgentService.TaskHeartbeat:output_type -> api.agent.v1.TaskHeartbeatReply
	8,  // 16: api.agent.v1.AgentService.ScriptSyncHeartbeat:output_type -> api.agent.v1.ScriptSyncHeartbeatReply
	12, // 17: api.agent.v1.AgentService.TaskResult:output_type -> api.agent.v1.TaskResultReply
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	file_agent_v1_agent_proto_msgTypes[5].OneofWrappers = []any{}
	file_agent_v1_agent_proto_msgTypes[7].OneofWrappers = []any{}
	file_agent_v1_agent_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
