truncate bom_match.t_bom_quote_cache;
truncate bom_match.t_bom_quote_item;
truncate bom_match.t_bom_search_task;
truncate bom_match.t_bom_session;
truncate bom_match.t_bom_session_line;
truncate bom_match.t_caichip_dispatch_task;