-- 种子数据：来自仓库根目录《电子元器件常见厂牌和缩写.xlsx》
-- 由 scripts/gen_bom_manufacturer_alias_seed.py 生成；请勿手改大段，改 xlsx 后重跑脚本。
-- alias_norm 与 internal/biz/bom_mfr_normalize.go NormalizeMfrString 一致。

INSERT INTO t_bom_manufacturer_alias (canonical_id, display_name, alias, alias_norm) VALUES
  ('MFR_ABRACON', 'Abracon', 'Abracon', 'ABRACON'),
  ('MFR_ADESTO', 'Adesto', 'Adesto', 'ADESTO'),
  ('MFR_ALLEGRO', 'Allegro', 'Allegro', 'ALLEGRO'),
  ('MFR_AMD', 'AMD', 'AMD', 'AMD'),
  ('MFR_ANALOG_DEVICES', 'Analog Devices', 'AD', 'AD'),
  ('MFR_ANALOG_DEVICES', 'Analog Devices', 'ADI', 'ADI'),
  ('MFR_ANALOG_DEVICES', 'Analog Devices', 'Analog Devices', 'ANALOG DEVICES'),
  ('MFR_AVX', 'AVX', 'AVX', 'AVX'),
  ('MFR_BOURNS', 'Bourns', 'Bourns', 'BOURNS'),
  ('MFR_CORNELL_DUBILIER', 'Cornell Dubilier', 'CDE', 'CDE'),
  ('MFR_CORNELL_DUBILIER', 'Cornell Dubilier', 'Cornell Dubilier', 'CORNELL DUBILIER'),
  ('MFR_CYPRESS', 'Cypress', 'CY', 'CY'),
  ('MFR_CYPRESS', 'Cypress', 'Cypress', 'CYPRESS'),
  ('MFR_DIALOG', 'Dialog', 'Dialog', 'DIALOG'),
  ('MFR_DIODES_INC', 'Diodes Inc.', 'Diodes', 'DIODES'),
  ('MFR_DIODES_INC', 'Diodes Inc.', 'Diodes Inc.', 'DIODES INC.'),
  ('MFR_EON_SILICON', 'Eon Silicon', 'EON', 'EON'),
  ('MFR_EON_SILICON', 'Eon Silicon', 'Eon Silicon', 'EON SILICON'),
  ('MFR_EPCOS', 'EPCOS', 'EPCOS', 'EPCOS'),
  ('MFR_EPSON', 'Epson', 'Epson', 'EPSON'),
  ('MFR_ESPRESSIF', 'Espressif', 'ESP', 'ESP'),
  ('MFR_ESPRESSIF', 'Espressif', 'Espressif', 'ESPRESSIF'),
  ('MFR_EXAR', 'Exar', 'Exar', 'EXAR'),
  ('MFR_FAIRCHILD', 'Fairchild', 'Fairchild', 'FAIRCHILD'),
  ('MFR_FAIRCHILD', 'Fairchild', 'FSC', 'FSC'),
  ('MFR_GIGADEVICE', 'GigaDevice', 'GD', 'GD'),
  ('MFR_GIGADEVICE', 'GigaDevice', 'GigaDevice', 'GIGADEVICE'),
  ('MFR_INFINEON', 'Infineon', 'IFX', 'IFX'),
  ('MFR_INFINEON', 'Infineon', 'Inf', 'INF'),
  ('MFR_INFINEON', 'Infineon', 'Infineon', 'INFINEON'),
  ('MFR_INTEL', 'Intel', 'Altera', 'ALTERA'),
  ('MFR_INTEL', 'Intel', 'Int', 'INT'),
  ('MFR_INTEL', 'Intel', 'Intel', 'INTEL'),
  ('MFR_INTERSIL', 'Intersil', 'Intersil', 'INTERSIL'),
  ('MFR_ISSI', 'ISSI', 'ISSI', 'ISSI'),
  ('MFR_KEC', 'KEC', 'KEC', 'KEC'),
  ('MFR_KEMET', 'Kemet', 'Kemet', 'KEMET'),
  ('MFR_KIOXIA', 'Kioxia', 'Kioxia', 'KIOXIA'),
  ('MFR_LATTICE', 'Lattice', 'Lattice', 'LATTICE'),
  ('MFR_LINEAR_TECHNOLOGY', 'Linear Technology', 'Linear Technology', 'LINEAR TECHNOLOGY'),
  ('MFR_LINEAR_TECHNOLOGY', 'Linear Technology', 'LT', 'LT'),
  ('MFR_LINEAR_TECHNOLOGY', 'Linear Technology', 'LTC', 'LTC'),
  ('MFR_LITTELFUSE', 'Littelfuse', 'Littelfuse', 'LITTELFUSE'),
  ('MFR_MACRONIX', 'Macronix', 'Macronix', 'MACRONIX'),
  ('MFR_MACRONIX', 'Macronix', 'MXIC', 'MXIC'),
  ('MFR_MAXIM_INTEGRATED', 'Maxim Integrated', 'Maxim', 'MAXIM'),
  ('MFR_MAXIM_INTEGRATED', 'Maxim Integrated', 'Maxim Integrated', 'MAXIM INTEGRATED'),
  ('MFR_MEDIATEK', 'MediaTek', 'MediaTek', 'MEDIATEK'),
  ('MFR_MEDIATEK', 'MediaTek', 'MTK', 'MTK'),
  ('MFR_MICROCHIP', 'Microchip', 'MCHP', 'MCHP'),
  ('MFR_MICROCHIP', 'Microchip', 'Microchip', 'MICROCHIP'),
  ('MFR_MICROCHIP', 'Microchip', 'Microsemi', 'MICROSEMI'),
  ('MFR_MICRON', 'Micron', 'Micron', 'MICRON'),
  ('MFR_MINI_CIRCUITS', 'Mini-Circuits', 'Mini', 'MINI'),
  ('MFR_MINI_CIRCUITS', 'Mini-Circuits', 'Mini-Circuits', 'MINI-CIRCUITS'),
  ('MFR_MPS', 'MPS', 'MPS', 'MPS'),
  ('MFR_MURATA', 'Murata', 'Murata', 'MURATA'),
  ('MFR_NATIONAL_SEMICONDUCTOR', 'National Semiconductor', 'National Semiconductor', 'NATIONAL SEMICONDUCTOR'),
  ('MFR_NATIONAL_SEMICONDUCTOR', 'National Semiconductor', 'NS', 'NS'),
  ('MFR_NATIONAL_SEMICONDUCTOR', 'National Semiconductor', 'NSC', 'NSC'),
  ('MFR_NDK', 'NDK', 'NDK', 'NDK'),
  ('MFR_NEXPERIA', 'Nexperia', 'Nexperia', 'NEXPERIA'),
  ('MFR_NICHICON', 'Nichicon', 'Nichicon', 'NICHICON'),
  ('MFR_NVIDIA', 'NVIDIA', 'NVIDIA', 'NVIDIA'),
  ('MFR_NXP', 'NXP', 'NXP', 'NXP'),
  ('MFR_ON_SEMICONDUCTOR', 'ON Semiconductor', 'ON', 'ON'),
  ('MFR_ON_SEMICONDUCTOR', 'ON Semiconductor', 'ON Semi', 'ON SEMI'),
  ('MFR_ON_SEMICONDUCTOR', 'ON Semiconductor', 'ON Semiconductor', 'ON SEMICONDUCTOR'),
  ('MFR_PANASONIC', 'Panasonic', 'Panasonic', 'PANASONIC'),
  ('MFR_POWER_INTEGRATIONS', 'Power Integrations', 'PI', 'PI'),
  ('MFR_POWER_INTEGRATIONS', 'Power Integrations', 'Power Integrations', 'POWER INTEGRATIONS'),
  ('MFR_QORVO', 'Qorvo', 'Qorvo', 'QORVO'),
  ('MFR_QUALCOMM', 'Qualcomm', 'QCOM', 'QCOM'),
  ('MFR_QUALCOMM', 'Qualcomm', 'Qualcomm', 'QUALCOMM'),
  ('MFR_RENESAS', 'Renesas', 'Renesas', 'RENESAS'),
  ('MFR_RICHTEK', 'Richtek', 'Richtek', 'RICHTEK'),
  ('MFR_ROHM', 'Rohm', 'RHM', 'RHM'),
  ('MFR_ROHM', 'Rohm', 'Rohm', 'ROHM'),
  ('MFR_RUBYCON', 'Rubycon', 'Rubycon', 'RUBYCON'),
  ('MFR_SAMSUNG', 'Samsung', 'Sam', 'SAM'),
  ('MFR_SAMSUNG', 'Samsung', 'Samsung', 'SAMSUNG'),
  ('MFR_SAMSUNG', 'Samsung', 'SEC', 'SEC'),
  ('MFR_SAMSUNG_ELECTRO_MECHANICS', 'Samsung Electro-Mechanics', 'Samsung Electro-Mechanics', 'SAMSUNG ELECTRO-MECHANICS'),
  ('MFR_SAMSUNG_ELECTRO_MECHANICS', 'Samsung Electro-Mechanics', 'SEMCO', 'SEMCO'),
  ('MFR_SEIKO_EPSON', 'Seiko Epson', 'Seiko', 'SEIKO'),
  ('MFR_SEIKO_EPSON', 'Seiko Epson', 'Seiko Epson', 'SEIKO EPSON'),
  ('MFR_SEMTECH', 'Semtech', 'Semtech', 'SEMTECH'),
  ('MFR_SILICON_LABS', 'Silicon Labs', 'Silabs', 'SILABS'),
  ('MFR_SILICON_LABS', 'Silicon Labs', 'Silicon Labs', 'SILICON LABS'),
  ('MFR_SINOWEALTH', 'SinoWealth', 'SH', 'SH'),
  ('MFR_SINOWEALTH', 'SinoWealth', 'SinoWealth', 'SINOWEALTH'),
  ('MFR_SITIME', 'SiTime', 'SiTime', 'SITIME'),
  ('MFR_SKYWORKS', 'Skyworks', 'Skyworks', 'SKYWORKS'),
  ('MFR_SK_HYNIX', 'SK Hynix', 'Hynix', 'HYNIX'),
  ('MFR_SK_HYNIX', 'SK Hynix', 'SK Hynix', 'SK HYNIX'),
  ('MFR_STMICROELECTRONICS', 'STMicroelectronics', 'ST', 'ST'),
  ('MFR_STMICROELECTRONICS', 'STMicroelectronics', 'STM', 'STM'),
  ('MFR_STMICROELECTRONICS', 'STMicroelectronics', 'STMicroelectronics', 'STMICROELECTRONICS'),
  ('MFR_TAIYO_YUDEN', 'Taiyo Yuden', 'Taiyo', 'TAIYO'),
  ('MFR_TAIYO_YUDEN', 'Taiyo Yuden', 'Taiyo Yuden', 'TAIYO YUDEN'),
  ('MFR_TDK', 'TDK', 'TDK', 'TDK'),
  ('MFR_TEXAS_INSTRUMENTS', 'Texas Instruments', 'Texas Instruments', 'TEXAS INSTRUMENTS'),
  ('MFR_TEXAS_INSTRUMENTS', 'Texas Instruments', 'TI', 'TI'),
  ('MFR_TE_CONNECTIVITY', 'TE Connectivity', 'TE', 'TE'),
  ('MFR_TE_CONNECTIVITY', 'TE Connectivity', 'TE Connectivity', 'TE CONNECTIVITY'),
  ('MFR_TOSHIBA', 'Toshiba', 'Tosh', 'TOSH'),
  ('MFR_TOSHIBA', 'Toshiba', 'Toshiba', 'TOSHIBA'),
  ('MFR_TXC', 'TXC', 'TXC', 'TXC'),
  ('MFR_VISHAY', 'Vishay', 'Vishay', 'VISHAY'),
  ('MFR_WALSIN', 'Walsin', 'Walsin', 'WALSIN'),
  ('MFR_WESTERN_DIGITAL', 'Western Digital', 'WD', 'WD'),
  ('MFR_WESTERN_DIGITAL', 'Western Digital', 'Western Digital', 'WESTERN DIGITAL'),
  ('MFR_WINBOND', 'Winbond', 'Winbond', 'WINBOND'),
  ('MFR_XILINX', 'Xilinx', 'Xilinx', 'XILINX'),
  ('MFR_YAGEO', 'Yageo', 'Yageo', 'YAGEO');
