// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"caichip/internal/biz"
	"caichip/internal/conf"
	"caichip/internal/data"
	"caichip/internal/server"
	"caichip/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

func wireApp(bootstrap *conf.Bootstrap, bootstrapProxy *conf.BootstrapProxy, logger log.Logger) (*kratos.App, func(), error) {
	agentHub := biz.NewAgentHub(bootstrap)
	dataData, cleanup, err := data.NewData(bootstrap)
	if err != nil {
		return nil, nil, err
	}
	agentScriptAuthRepo := data.NewAgentScriptAuthRepo(bootstrap, dataData)
	inprocKV := data.NewInprocKV()
	cachedAgentScriptAuthRepo := data.NewCachedAgentScriptAuthRepo(agentScriptAuthRepo, inprocKV)
	dispatchTaskRepo := data.NewDispatchTaskRepo(dataData, cachedAgentScriptAuthRepo)
	agentRegistryRepo := data.NewAgentRegistryRepo(dataData)
	cachedAgentRegistryRepo := data.NewCachedAgentRegistryRepo(agentRegistryRepo, inprocKV)
	taskScheduler := biz.NewAgentTaskScheduler(agentHub, dispatchTaskRepo, cachedAgentRegistryRepo, bootstrap)
	agentScriptPackageRepo := data.NewAgentScriptPackageRepo(dataData)
	bomManufacturerAliasRepo := data.NewBomManufacturerAliasRepo(dataData)
	cachedBomManufacturerAliasRepo := data.NewCachedBomManufacturerAliasRepo(bomManufacturerAliasRepo, inprocKV)
	bomSearchTaskRepo := data.NewBOMSearchTaskRepo(dataData, cachedBomManufacturerAliasRepo)
	bomSessionRepo := data.NewBomSessionRepo(dataData)
	agentService := service.NewAgentService(agentHub, taskScheduler, dispatchTaskRepo, cachedAgentRegistryRepo, agentScriptPackageRepo, bomSearchTaskRepo, bomSessionRepo, bootstrap, logger)
	scriptPackageAdmin := service.NewScriptPackageAdmin(bootstrap, agentScriptPackageRepo, logger)
	bomPlatformScriptRepo := data.NewBomPlatformScriptRepo(dataData)
	cachedBomPlatformScriptRepo := data.NewCachedBomPlatformScriptRepo(bomPlatformScriptRepo, inprocKV)
	bomMergeProxyWaitRepo := data.NewBomMergeProxyWaitRepo(dataData)
	client := data.NewKuaidailiClient(bootstrapProxy, logger)
	bomMergeDispatch := data.NewBomMergeDispatch(dataData, dispatchTaskRepo, bomSearchTaskRepo, bomSessionRepo, agentScriptPackageRepo, cachedBomPlatformScriptRepo, bomMergeProxyWaitRepo, client, bootstrapProxy)
	openAIChat := data.NewOpenAIChat(bootstrap)
	bomFxRateRepo := data.NewBomFxRateRepoFromData(dataData, logger)
	hsModelMappingRepo := data.NewHsModelMappingRepo(dataData, cachedBomManufacturerAliasRepo)
	hsItemReadRepo := data.NewHsItemReadRepo(dataData)
	hsTaxRateDailyRepo := data.NewHsTaxRateDailyRepo(dataData)
	hsTaxRateAPIRepo := data.NewHsTaxRateAPIRepo(bootstrap)
	taxRateAPIBizAdapter := data.NewTaxRateAPIBizAdapter(hsTaxRateAPIRepo)
	bomService := service.NewBomService(bomSessionRepo, bomSearchTaskRepo, bomMergeDispatch, openAIChat, bomFxRateRepo, cachedBomManufacturerAliasRepo, hsModelMappingRepo, hsItemReadRepo, hsTaxRateDailyRepo, taxRateAPIBizAdapter, bootstrap, logger)
	agentAdminService := service.NewAgentAdminService(bootstrap, cachedAgentRegistryRepo, dispatchTaskRepo, cachedAgentScriptAuthRepo, cachedBomPlatformScriptRepo, logger)
	hsDatasheetAssetRepo := data.NewHsDatasheetAssetRepo(dataData)
	hsModelRecommendationRepo := data.NewHsModelRecommendationRepo(dataData)
	hsItemQueryRepo := data.NewHsItemQueryRepo(dataData)
	hsModelTaskRepo := data.NewHsModelTaskRepo(dataData)
	hsModelFeaturesRepo := data.NewHsModelFeaturesRepo(dataData)
	hsManualDatasheetUploadRepo := data.NewHsManualDatasheetUploadRepo(dataData)
	hsResolveService := service.NewDefaultHsResolveService(bootstrap, logger, hsModelMappingRepo, hsDatasheetAssetRepo, hsModelRecommendationRepo, hsItemQueryRepo, hsModelTaskRepo, openAIChat, hsModelFeaturesRepo, cachedBomManufacturerAliasRepo, hsManualDatasheetUploadRepo)
	hsMetaRepo := data.NewHsMetaRepo(dataData)
	hsMetaService := service.NewHsMetaService(hsMetaRepo)
	hsItemWriteRepo := data.NewHsItemWriteRepo(dataData)
	hsQueryAPIRepo := data.NewHsQueryAPIRepo(bootstrap)
	hsSyncService := service.NewHsSyncService(hsMetaRepo, hsItemReadRepo, hsItemWriteRepo, hsQueryAPIRepo)
	httpServer := server.NewHTTPServer(bootstrap, logger, agentService, scriptPackageAdmin, bomService, agentAdminService, hsResolveService, hsMetaService, hsSyncService)
	tableCacheRefresher := data.NewTableCacheRefresher(inprocKV, dataData, bootstrap, logger, bomPlatformScriptRepo, bomManufacturerAliasRepo)
	mergeProxyRetryWorker := data.NewMergeProxyRetryWorker(bootstrapProxy, logger, dataData, bomMergeDispatch, bomMergeProxyWaitRepo)
	hsManualDatasheetJanitor := data.NewHsManualDatasheetJanitor(hsManualDatasheetUploadRepo, logger)
	app := newApp(bootstrap, logger, httpServer, tableCacheRefresher, mergeProxyRetryWorker, hsManualDatasheetJanitor)
	return app, func() {
		cleanup()
	}, nil
}
